In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os
import re
import time
from selenium import webdriver

In [2]:
driver = webdriver.Safari()

base = 'https://ftc-events.firstinspires.org/2022/'


driver.get(base)
time.sleep(3)
page = driver.page_source

soup = BeautifulSoup(page, 'lxml')

In [3]:
soup

<html lang="en"><!--  PLEASE DO NOT SCRAPE WEBPAGES FOR EVENT DATA!
We have an API that allows easy access to event and team
data! It is easier for developers, and helps keep this server
available for the public who are seeking basic event information.
More info: https://ftc-events.firstinspires.org/services/API
____ ____ ___   ____ ______
/ __//  _// _ \ / __//_  __/ (R)
/ _/ _/ / / , _/_\ \   / /
/_/  /___//_/|_|/___/  /_/

--><head>
<title>
		FTC Event Web : Home
	</title>
<meta content="Official source of event information, results and webcasts from the FIRST FIRST Tech Challenge " name="description"/>
<link href="https://ftc-events-cdn.global-prod.ftclive.org/evtwebextFTC/app.48544bfc62deef954ddd.css" rel="stylesheet"/>
<meta content="width=device-width, initial-scale=1,user-scalable=no" name="viewport"/>
<link href="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_common/favicon/first.ico" rel="icon" type="image/x-icon"/>
<link href="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/apple/apple-touch-icon-72.png" rel="apple-touch-icon"/>
<link href="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/apple/apple-touch-icon-144.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/apple/apple-touch-icon-180.png" rel="apple-touch-icon" sizes="180x180"/>
<script data-cookieconsent="ignore" data-hs-ignore="true" data-hsjs-env="prod" data-hsjs-hublet="na1" data-hsjs-portal="1747660" data-loader="hs-scriptloader" id="cookieBanner-1747660" src="https://js.hs-banner.com/1747660.js" type="text/javascript"></script><script data-ads-env="prod" data-ads-portal-id="1747660" data-hsjs-env="prod" data-hsjs-hublet="na1" data-hsjs-portal="1747660" data-loader="hs-scriptloader" id="hs-ads-pixel-1747660" src="https://js.hsadspixel.net/fb.js" type="text/javascript"></script><script crossorigin="anonymous" data-hsjs-env="prod" data-hsjs-hublet="na1" data-hsjs-portal="1747660" data-leadin-env="prod" data-leadin-portal-id="1747660" data-loader="hs-scriptloader" id="LeadFlows-1747660" src="https://js.hsleadflows.net/leadflows.js" type="text/javascript"></script><script id="hs-analytics" src="https://js.hs-analytics.net/analytics/1685583000000/1747660.js" type="text/javascript"></script><script crossorigin="anonymous" data-hsjs-env="prod" data-hsjs-hublet="na1" data-hsjs-portal="1747660" data-loader="hs-scriptloader" id="hubspot-web-interactives-loader" src="https://js.hubspot.com/web-interactives-embed.js" type="text/javascript"></script><script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0L3H4S6BRJ&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-60219656-7"></script>
<script>
			window.dataLayer = window.dataLayer || [];
			function gtag() { dataLayer.push(arguments); }
			gtag('js', new Date());

			gtag('config', 'UA-60219656-7');
		</script>
<!-- Start of HubSpot Embed Code MKT -->
<script async="" defer="" id="hs-script-loader" src="//js.hs-scripts.com/1747660.js" type="text/javascript"></script>
<!-- End of HubSpot Embed Code MKT -->
<script src="https://ftc-events-cdn.global-prod.ftclive.org/evtwebextFTC/runtime.889693517ce2edf3fc3b.bundle.js"></script>
<script src="https://ftc-events-cdn.global-prod.ftclive.org/evtwebextFTC/app.610ceeddcfea5c1efcdc.js"></script>
<style>body.tablesorter-disableSelection { -ms-user-select: none; -moz-user-select: -moz-none;-khtml-user-select: none; -webkit-user-select: none; user-select: none; }.tablesorter-resizable-container { position: relative; height: 1px; }.tablesorter-resizable-handle { position: absolute; display: inline-block; width: 8px;top: 1px; cursor: ew-resize; z-index: 3; user-select: none; -moz-user-select: none; }</style><style id="_goober"> .go2933276541{position:fixed;display:block;width:100%;height:0px;margin:0px;padding:0px;overflow:visible;transform-style:preserve-3d;background:transparent;backface-visibility:hidden;pointer-events:none;left:0px;z-index:9998;}.go2369186930{top:0px;z-index:9999;height:100%;width:100%;}.go1348078617{bottom:0px;}.go2417249464{position:fixed;z-index:9989;}.go3921366393{left:0;bottom:0;}.go3967842156{right:0;bottom:0;}.go613305155{left:0;top:0;}.go471583506{right:0;top:0;}.go3670563033{position:relative;overflow:hidden;display:none;}.go1041095097{display:block;}.go1632949049{position:absolute;pointer-events:none;width:101vw;height:101vh;background:rgba(0,0,0,0.7);opacity:0;z-index:-1;}.go1366308204{z-index:99998;opacity:0.5;visibility:visible;pointer-events:all;cursor:pointer;}.go812842568{display:block !important;position:static !important;box-sizing:border-box !important;background:transparent !important;border:none;min-height:0px !important;max-height:none !important;margin:0px;padding:0px !important;height:100% !important;width:1px !important;max-width:100% !important;min-width:100% !important;}.go2729809544{z-index:99999;visibility:hidden;position:absolute;inset:50vh auto auto 50%;transform:translate(-50%,-50%);left:50%;top:50%;opacity:0;pointer-events:none;max-height:95%;max-width:95%;}.go1011812720{pointer-events:auto !important;visibility:visible;opacity:1;transition:opacity 1s ease-in;}.go3128134379{pointer-events:auto !important;visibility:visible !important;max-height:95vh !important;transition:max-height 1s ease-in;}.go494047706{z-index:9999;width:100%;max-height:95%;position:fixed;visibility:hidden;}.go2481764524{z-index:9999;width:100%;max-height:95%;position:fixed;visibility:hidden;bottom:0px;}.go2685733372{visibility:hidden;}.go2985984737{visibility:visible !important;}.go3281949485{pointer-events:auto !important;visibility:visible !important;max-height:95vh !important;transform:none !important;}.go3539422596{z-index:9999;width:100%;max-height:95%;position:fixed;visibility:hidden;transition:transform 0.5s cubic-bezier(0.31,-0.2,0.04,1.47);}.go988075951{z-index:9999;position:fixed;left:10px;top:10px;max-height:95vh !important;max-width:95%;visibility:hidden;}.go2699082514{z-index:9999;position:fixed;right:10px;top:10px;max-height:95vh !important;max-width:95%;visibility:hidden;}.go1595992025{z-index:9999;position:fixed;left:10px;bottom:10px;max-height:95vh !important;max-width:95%;visibility:hidden;}.go1222083472{z-index:9999;position:fixed;right:10px;bottom:10px;max-height:95vh !important;max-width:95%;visibility:hidden;}.go26732895{cursor:pointer;}.go2083580917{display:flex;justify-content:center;align-items:center;}</style></head>
<body><div class="go3670563033" id="hs-web-interactives-top-push-anchor"></div><style type="text/css">div#hs-eu-cookie-confirmation{background:#fff;height:auto;left:0;position:absolute;top:0;width:100%;z-index:100000000!important;border-bottom:1px solid #cbd6e2;border-top:1px solid #cbd6e2;box-shadow:0 1px 5px #eaf0f6;color:#33475b;font-family:inherit;font-size:inherit;font-weight:400!important;line-height:inherit;text-align:left;text-shadow:none!important;font-size:12px;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;line-height:18px}div#hs-eu-cookie-confirmation.hs-cookie-notification-position-bottom{position:fixed;border-bottom:0;bottom:0;top:auto;box-shadow:0 -1px 3px #eaf0f6}div#hs-eu-cookie-confirmation *{box-sizing:border-box!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner{background:#fff;margin:0 auto;max-width:1000px;padding:20px}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a{text-decoration:none!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a,div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a:hover{background:none!important;border:none!important;box-shadow:none!important;color:#0091ae;font-family:inherit;font-size:inherit;font-weight:400!important;line-height:inherit;text-align:left;text-shadow:none!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a:hover{text-decoration:underline!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner div#hs-eu-policy-wording{margin-bottom:12px}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner div#hs-en-cookie-confirmation-buttons-area,div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner div#hs-eu-cookie-confirmation-button-group{display:flex;flex-direction:row;flex-wrap:wrap;align-items:center}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner div#hs-en-cookie-confirmation-buttons-area{margin-right:72px;justify-content:flex-end;align-items:center}@media (max-width:800px){div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner div#hs-en-cookie-confirmation-buttons-area{justify-content:center;margin-right:0}}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner div#hs-eu-cookie-confirmation-button-group{justify-content:center}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-confirmation-button,div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-cookie-settings-button,div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-decline-button{margin:6px!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-confirmation-button,div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-decline-button{border-radius:3px;display:inline-block;padding:10px 16px!important;text-decoration:none!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-confirmation-button{background-color:#0066b3!important;border:1px solid #0066b3!important;color:#fff;font-family:inherit;font-size:inherit;font-weight:400!important;line-height:inherit;text-align:left;text-shadow:none!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-decline-button{border:1px solid #0066b3!important;color:#0066b3;font-family:inherit;font-size:inherit;font-weight:400!important;line-height:inherit;text-align:left;text-shadow:none!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-cookie-settings-button{color:#0066b3!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner p{margin:0 72px 12px;color:#33475b;font-family:inherit;font-size:inherit;font-weight:400!important;line-height:inherit;text-align:left;text-shadow:none!important}@media (max-width:800px){div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner p{margin:0 20px 12px}}#hs-eu-close-button-container{display:flex;justify-content:end;margin-top:8px;margin-right:8px}#hs-eu-close-button-container a#hs-eu-close-button[role=button]{float:right;width:1.5rem;font-size:40px!important;text-align:center!important;cursor:pointer;color:#8b8589!important}#hs-eu-close-button-container a#hs-eu-close-button[role=button]:hover{background:none!important;border:none!important;box-shadow:none!important;color:#0091ae;font-family:inherit;font-size:inherit;font-weight:400!important;line-height:inherit;text-align:left;text-shadow:none!important;text-decoration:none!important}@media (max-width:800px){#hs-eu-close-button-container a#hs-eu-close-button[role=button]{margin-right:10px;font-size:30px;line-height:50px}}@media (min-width:800px){#hs-eu-close-button-container a#hs-eu-close-button[role=button]{margin-bottom:10px}}@media print{div#hs-eu-cookie-confirmation{display:none!important}}@media screen and (max-width:480px){div#hs-eu-cookie-confirmation{font-size:12px!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner{padding:8px 14px 14px!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a,div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner a#hs-eu-confirmation-button{font-size:12px!important}div#hs-eu-cookie-confirmation div#hs-eu-cookie-confirmation-inner p{font-size:12px!important;margin-bottom:12px!important;line-height:15px!important}}@media only screen and (min-width:960px){div#hs-eu-cookie-confirmation{position:fixed}}</style><div class="" data-nosnippet="" id="hs-eu-cookie-confirmation">
<div id="hs-eu-cookie-confirmation-inner">
<div id="hs-eu-policy-wording"><p>This website uses cookies to improve user experience. By using our website you consent to all cookies in accordance with the <a href="https://www.firstinspires.org/about/privacy-policy">FIRST Privacy Policy</a>.</p></div>
<div id="hs-en-cookie-confirmation-buttons-area">
<div id="hs-eu-cookie-confirmation-button-group">
<a href="javascript:void(0);" id="hs-eu-confirmation-button" role="button">
    Accept
  </a>
<a href="javascript:void(0);" id="hs-eu-decline-button" role="button">Decline</a>
</div>
</div>
</div>
</div>
<script>
			var showYear = function () {
				$(this).find("#gamename").show();
				$(this).find("#gameimage").hide();
			}
			var showLogo = function () {
				$(this).find("#gameimage").show();
				$(this).find("#gamename").hide();
			}
			$(function () {
				$('td.games').hover(showYear, showLogo);
			});
		</script>
<style>
			.seasontable a:hover {
				text-decoration: none;
				color: #337ab7 !important;
			}

			.seasontable div {
				height: 65px;
			}

			ul.nav td a:hover {
				color: #337ab7 !important; /*Override Site for Nav*/
			}
		</style>
<nav class="navbar navbar-inverse navbar-fixed-top">
<!-- Color Strip -->
<div class="color-strip">
<div class="fgreen"></div>
<div class="fred"></div>
<div class="forange"></div>
<div class="fblue"></div>
</div>
<div class="container">
<div class="navbar-header">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar-collapse" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a href="/2022" title="Home">
<div class="navbar-brand"><strong><span class="hidden-sm">Event</span> Results</strong></div>
</a>
</div>
<div class="navbar-collapse collapse" id="navbar-collapse">
<form action="/search" class="navbar-form navbar-left hidden-sm">
<div class="form-group">
<div class="col-md-1"><input name="season" type="hidden" value="2022"/></div>
<input autocomplete="off" class="form-control event_code_form" maxlength="12" name="jump" placeholder="Team # / Event Code" required="" type="text" width="12"/>
</div>
<button class="btn btn-default hidden-md" type="submit">Jump</button>
</form>
<ul class="nav navbar-nav">
</ul>
<ul class="nav navbar-nav navbar-right topnavbar" id="login-dropdown-list">
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown">Seasons<b class="caret"></b></a>
<ul class="dropdown-menu">
<li>
<table class="seasontable" style="table-layout:fixed;text-align:center;vertical-align:middle;">
<tbody><tr> <td class="games" style="width:135px;border-right:1px solid #AEB6Bf;">
<a href="/2022" title="View POWERPLAY Results">
<div>
<img alt="POWERPLAY" id="gameimage" src="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/GameLogos/2022.png" style="max-width:120px;max-height:45px;margin:8px;"/>
<div id="gamename" style="height:100%;line-height:60px;display:none;">
<span style="font-weight:bold;vertical-align:middle;display:inline-block;line-height:normal;"><em>2022:</em><br/>POWERPLAY</span>
</div>
</div>
</a>
</td>
<td class="games" style="width:135px;">
<a href="/2021" title="View FREIGHT FRENZY Results">
<div>
<img alt="FREIGHT FRENZY" id="gameimage" src="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/GameLogos/2021.png" style="max-width:120px;max-height:45px;margin:8px;"/>
<div id="gamename" style="height:100%;line-height:60px;display:none;">
<span style="font-weight:bold;vertical-align:middle;display:inline-block;line-height:normal;"><em>2021:</em><br/>FREIGHT FRENZY</span>
</div>
</div>
</a>
</td>
</tr> <tr style="height:1px;line-height:0px;">
<td colspan="2" style="background-color:#AEB6BF;"> </td>
</tr>
<tr> <td class="games" style="width:135px;border-right:1px solid #AEB6Bf;">
<a href="/2020" title="View ULTIMATE GOAL Results">
<div>
<img alt="ULTIMATE GOAL" id="gameimage" src="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/GameLogos/2020.png" style="max-width:120px;max-height:45px;margin:8px;"/>
<div id="gamename" style="height:100%;line-height:60px;display:none;">
<span style="font-weight:bold;vertical-align:middle;display:inline-block;line-height:normal;"><em>2020:</em><br/>ULTIMATE GOAL</span>
</div>
</div>
</a>
</td>
<td class="games" style="width:135px;">
<a href="/2019" title="View SKYSTONE Results">
<div>
<img alt="SKYSTONE" id="gameimage" src="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/GameLogos/2019.png" style="max-width:120px;max-height:45px;margin:8px;"/>
<div id="gamename" style="height:100%;line-height:60px;display:none;">
<span style="font-weight:bold;vertical-align:middle;display:inline-block;line-height:normal;"><em>2019:</em><br/>SKYSTONE</span>
</div>
</div>
</a>
</td>
</tr> <tr style="height:1px;line-height:0px;">
<td colspan="2" style="background-color:#AEB6BF;"> </td>
</tr>
<tr> <td class="games" style="width:135px;border-right:1px solid #AEB6Bf;">
<a href="/seasons" title="View All Seasons Results">
<div>
<img alt="All Seasons" id="gameimage" src="https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/GameLogos/all-seasons.png" style="max-width:120px;max-height:45px;margin:8px;"/>
<div id="gamename" style="height:100%;line-height:60px;display:none;">
<span style="font-weight:bold;vertical-align:middle;display:inline-block;line-height:normal;">All Seasons</span>
</div>
</div>
</a>
</td>
<td style="width:135px;height:50px;"> </td></tr> </tbody></table>
</li>
</ul>
</li>
</ul>
<ul class="nav navbar-nav navbar-right topnavbar">
<li class="dropdown dropdown-large">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">This Week's Events <span class="badge">1</span> <b class="caret"></b></a>
<ul class="dropdown-menu dropdown-menu-large row top-row-dropdown">
<li class="col-sm-12" style="width: 260px;"><ul> <li class="divider" role="separator"></li>
<li class="dropdown-header">Washington Region</li>
<li title="WA Spartan Showdown"><a href="/2022/USWASAOS">WA Spartan Showdown</a></li>
</ul></li> </ul>
</li>
</ul>
</div>
</div>
</nav>
<div class="flex" id="flex">
<div class="whitebg">
<div class="hidden-xs" style="height: 300px; background-size: cover; background-image: url(https://ftc-events-cdn.global-prod.ftclive.org/eventweb_ftc/banners/2022/2.jpg)">
</div>
<div class="container">
<input id="kickoffDateStringJS" name="kickoffDateStringJS" type="hidden" value="0001-01-01T00:00:00.0000000"/>
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"/>
<div class="container" style="margin-left: -15px;">
<!--
     <ul class="nav nav-tabs" role="tablist">
       <li class="active">
           <a href="#allevents" role="tab" data-toggle="tab">
               <icon class="fa fa-home"></icon> All Events
           </a>
       </li>
       <li><a href="#thisweek" role="tab" data-toggle="tab">
           <i class="fa fa-user"></i> This Weeks Events
           </a>
       </li>
       <li>
           <a href="#statistics" role="tab" data-toggle="tab">
               <i class="fa fa-envelope"></i> Statistics
           </a>
       </li>
     </ul>
     <div class="tab-content">
     <div class="tab-pane fade active in" id="allevents"-->
<p class="lead">
             Please select an event to view official results from the 2022-2023 <em>FIRST</em> Tech Challenge.
         </p>
<div class="row">
<!--div class="col-lg-3">
             <div class="regionView">
                 <b>View by:
                     <span id="regionViewButton" class="link">Region View</span> /
                     <span id="weekViewButton" class="link">Week View</span>
                 </b>
             </div>
             </div-->
<div class="col-md-2"></div>

In [14]:
scripts = soup.find_all('script')

In [16]:
for s in scripts:
    print(scripts.string)

AttributeError: ResultSet object has no attribute 'string'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [37]:
stuff = [{"Wt":"of 05/01/2023","Ws":"2023-05-01T00:00:00","We":"2023-05-07T23:59:59","Wn":34,"Ec":4,"E":[{"Tc":"USARLCMP","S":2022,"En":"Adventist Robotics League Championship","Ev":"Forest Lake Academy","Ea":"500 Education Loop","Ec":"Apopka","Es":"FL","Ect":"USA","Dn":"Adventist Robotics League","Sd":"2023-05-07T00:00:00","Ed":"2023-05-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USMIAAOS","S":2022,"En":"Girls R GRAYT All Girls Event","Ev":"Rudolf Steiner School","Ea":"2230 Pontiac Trail","Ec":"Ann Arbor","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-05T00:00:00","Ed":"2023-05-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USMIGIOS","S":2022,"En":"Gibraltar FTC Spring Showdown","Ev":"Carlson High School","Ea":"30550 W Jefferson Avenue","Ec":"Gibraltar","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-05T00:00:00","Ed":"2023-05-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USPAPHOS","S":2022,"En":"PA FTC RoboJawn","Ev":"Central High School","Ea":"1700 West Olney Ave","Ec":"Philadelphia","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-05-06T00:00:00","Ed":"2023-05-06T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 05/08/2023","Ws":"2023-05-08T00:00:00","We":"2023-05-14T23:59:59","Wn":35,"Ec":7,"E":[{"Tc":"FRLEOS","S":2022,"En":"FR Le D\u00E9fi Robotique \u2013 Lyon 2023","Ev":"Hotel de R\u00E9gion - R\u00E9gion Auvergne-Rh\u00F4ne-Alpes","Ea":"101 Cours Charlemagne","Ec":"Lyon","Es":"69","Ect":"France","Dn":"France","Sd":"2023-05-13T00:00:00","Ed":"2023-05-13T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USMITCOS2","S":2022,"En":"MI TC West Remote Event","Ev":"Traverse City West Middle School","Ea":"3950 Silver Lake Rd.","Ec":"Traverse City","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-07T00:00:00","Ed":"2023-05-13T00:00:00","Ew":"","Hmd":False,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USMIKIOS","S":2022,"En":"Kingsford Spring Event","Ev":"Kingsford Middle School","Ea":"431 Hamilton Avenue","Ec":"Kingsford","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-12T00:00:00","Ed":"2023-05-13T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USMIRCOS","S":2022,"En":"Reed City Spring Event","Ev":"Reed City Middle School","Ea":"233 W Church Avenue","Ec":"Reed City","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-12T00:00:00","Ed":"2023-05-13T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USMIJAOS","S":2022,"En":"Jackson FTC Spring Event","Ev":"Jackson College Victor Cuiss Fieldhouse","Ea":"2111 Emmons Road","Ec":"Jackson","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-12T00:00:00","Ed":"2023-05-13T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USORROOS","S":2022,"En":"OR Spring Showcase","Ev":"Roseburg High School","Ea":"400 W Harvard Ave","Ec":"Roseburg","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-05-13T00:00:00","Ed":"2023-05-13T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USTXWPROS","S":2022,"En":"TX- WP CEN Exhibition","Ev":"Roscoe Collegiate ISD","Ea":"P. O. Box 579","Ec":"Roscoe","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-05-13T00:00:00","Ed":"2023-05-13T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 05/15/2023","Ws":"2023-05-15T00:00:00","We":"2023-05-21T23:59:59","Wn":36,"Ec":4,"E":[{"Tc":"USAZFLOS","S":2022,"En":"AZ Lunar Legacy Invitational","Ev":"Northern Arizona University Fieldhouse","Ea":"1050 Knoles Dr","Ec":"Flagstaff","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-05-20T00:00:00","Ed":"2023-05-21T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"https://www.youtube.com/@firsttechchallengearizona6515","eventType":7},{"Tc":"USMIFROS","S":2022,"En":"Freeland FTC Gear-Up!","Ev":"Freeland High School","Ea":"8250 Webster Road","Ec":"Freeland","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-19T00:00:00","Ed":"2023-05-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USORGLOS","S":2022,"En":"OR Spring Showcase 2","Ev":"Gladstone High School","Ea":"18800 Portland Ave","Ec":"Gladstone","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-05-20T00:00:00","Ed":"2023-05-20T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USORMLS","S":2022,"En":"OR Spring Scrimmage and Showcase","Ev":"Multiple Locations","Ea":"Multiple Locations","Ec":"Multiple Locations","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-05-20T00:00:00","Ed":"2023-05-20T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 05/22/2023","Ws":"2023-05-22T00:00:00","We":"2023-05-28T23:59:59","Wn":37,"Ec":2,"E":[{"Tc":"USIADMOS","S":2022,"En":"IA CelebrAsian Off-Season Event","Ev":"Western Gateway Park","Ea":"1205 Locust St","Ec":"Des Moines","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-05-27T00:00:00","Ed":"2023-05-27T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USTXCESAOS","S":2022,"En":"2023 Blackout Battle Royale","Ev":"NA","Ea":"NA","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-05-27T00:00:00","Ed":"2023-05-27T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 05/29/2023","Ws":"2023-05-29T00:00:00","We":"2023-06-04T23:59:59","Wn":38,"Ec":2,"E":[{"Tc":"USMITCOS1","S":2022,"En":"MI TC East Remote Event","Ev":"Traverse City East Middle School","Ea":"1776 N Three Mile Rd.","Ec":"Traverse City","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-28T00:00:00","Ed":"2023-06-03T00:00:00","Ew":"","Hmd":False,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USWASAOS","S":2022,"En":"WA Spartan Showdown","Ev":"Skyline High School","Ea":"1122 228th Ave SE","Ec":"Sammamish","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2023-06-03T00:00:00","Ed":"2023-06-03T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 06/05/2023","Ws":"2023-06-05T00:00:00","We":"2023-06-11T23:59:59","Wn":39,"Ec":1,"E":[{"Tc":"USMIBHOS1","S":2022,"En":"MI FiM Remote Event","Ev":"Remote","Ea":"Remote","Ec":"Bloomfield Hills","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2023-05-30T00:00:00","Ed":"2023-06-05T00:00:00","Ew":"","Hmd":False,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 06/12/2023","Ws":"2023-06-12T00:00:00","We":"2023-06-18T23:59:59","Wn":40,"Ec":1,"E":[{"Tc":"USCTSTOS","S":2022,"En":"CT Husky Robotics Invitational","Ev":"University of Connecticut (UCONN) - Lawrence D. McHugh Hall","Ea":"Fairfield Way","Ec":"Storrs","Es":"CT","Ect":"USA","Dn":"Connecticut","Sd":"2023-06-17T00:00:00","Ed":"2023-06-17T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 06/19/2023","Ws":"2023-06-19T00:00:00","We":"2023-06-25T23:59:59","Wn":41,"Ec":4,"E":[{"Tc":"GBCAOS","S":2022,"En":"GB New Teams Regional","Ev":"University of Cambridge- Sports Centre","Ea":"Philippa Fawcett Dr,","Ec":"Cambridge","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-06-23T00:00:00","Ed":"2023-06-23T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"GBCMP","S":2022,"En":"Championship- United Kingdom","Ev":"University of Cambridge- Sports Centre","Ea":"Philippa Fawcett Dr,","Ec":"Cambridge","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-06-23T00:00:00","Ed":"2023-06-23T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USALHUOS","S":2022,"En":"AL betaSEIT","Ev":"New Century High School","Ea":"2500 Meridian St N","Ec":"Huntsville","Es":"AL","Ect":"USA","Dn":"Alabama","Sd":"2023-06-22T00:00:00","Ed":"2023-06-24T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USOKMUOS","S":2022,"En":"OK-Northeast (NEO) Invitational","Ev":"Muskogee High School","Ea":"3200 E Shawnee Rd","Ec":"Muskogee","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-06-24T00:00:00","Ed":"2023-06-24T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 06/26/2023","Ws":"2023-06-26T00:00:00","We":"2023-07-02T23:59:59","Wn":42,"Ec":1,"E":[{"Tc":"USCHSLAOS","S":2022,"En":"Maryland Tech Invitational","Ev":"Kossiakoff Center","Ea":"11100 John Hopkins Rd","Ec":"laurel","Es":"MD","Ect":"USA","Dn":"Chesapeake","Sd":"2023-06-23T00:00:00","Ed":"2023-06-26T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 07/03/2023","Ws":"2023-07-03T00:00:00","We":"2023-07-09T23:59:59","Wn":43,"Ec":1,"E":[{"Tc":"USCANOSMOS","S":2022,"En":"Lobster Cup International","Ev":"San Mateo County Event Center","Ea":"1346 Saratoga Drive","Ec":"San Mateo","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-07-09T00:00:00","Ed":"2023-07-09T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 07/10/2023","Ws":"2023-07-10T00:00:00","We":"2023-07-16T23:59:59","Wn":44,"Ec":2,"E":[{"Tc":"AUMPOS1","S":2022,"En":"AU APOC 2023","Ev":"Macquarie University","Ea":"Balaclava Road, Macquarie Park, NSW","Ec":"Macquarie Park","Es":"NSW","Ect":"Australia","Dn":"Australia","Sd":"2023-07-14T00:00:00","Ed":"2023-07-16T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7},{"Tc":"USILCHOS","S":2022,"En":"IL Chicago Robotics Invitational","Ev":"Francis W. Parker School","Ea":"330 W Webster Ave","Ec":"chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-07-14T00:00:00","Ed":"2023-07-16T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]},{"Wt":"of 07/24/2023","Ws":"2023-07-24T00:00:00","We":"2023-07-30T23:59:59","Wn":46,"Ec":1,"E":[{"Tc":"USOHAKOS","S":2022,"En":"OH KSS Robotics Turtle Friendly","Ev":"Central-Hower High School","Ea":"123 S. Forge Street","Ec":"Akron","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-07-29T00:00:00","Ed":"2023-07-29T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":7}]}]
others=  [{"Wt":"of 09/05/2022","Ws":"2022-09-05T00:00:00","We":"2022-09-11T23:59:59","Wn":1,"Ec":1,"E":[{"Tc":"USNDBIS","S":2022,"En":"ND Scrimmage","Ev":"Bismarck Career Academy","Ea":"1221 College Dr","Ec":"Bismarck","Es":"ND","Ect":"USA","Dn":"North Dakota","Sd":"2022-09-10T00:00:00","Ed":"2022-09-11T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 09/19/2022","Ws":"2022-09-19T00:00:00","We":"2022-09-25T23:59:59","Wn":2,"Ec":2,"E":[{"Tc":"USAZTUS","S":2022,"En":"AZ Tucson \u0022Meet the Field\u0022 Day","Ev":"San Miguel High School","Ea":"6601 San Fernando Ave","Ec":"Tucson","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2022-09-24T00:00:00","Ed":"2022-09-24T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USOKOCS","S":2022,"En":"OK Tinkerfest","Ev":"Science Museum Oklahoma","Ea":"2020 Remington Pl","Ec":"Oklahoma City","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-09-24T00:00:00","Ed":"2022-09-24T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 09/26/2022","Ws":"2022-09-26T00:00:00","We":"2022-10-02T23:59:59","Wn":3,"Ec":2,"E":[{"Tc":"USMNSPS","S":2022,"En":"MN Cass Lake League Meet 0","Ev":"St. Paul Academy","Ea":"1712 Randolph Ave","Ec":"St. Paul","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-09-29T00:00:00","Ed":"2022-09-29T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USMSBCS1","S":2022,"En":"MS Bogue Chitto Build-it Day/Scrimmage","Ev":"Reggie Wise","Ea":"478 Fairlawn Trail NE","Ec":"Bogue Chitto","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2022-10-01T00:00:00","Ed":"2022-10-01T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 10/03/2022","Ws":"2022-10-03T00:00:00","We":"2022-10-09T23:59:59","Wn":4,"Ec":2,"E":[{"Tc":"USAKAKSCM1","S":2022,"En":"AK Southcentral Alaska League Meet #1","Ev":"West High School","Ea":"1700 Hillcrest Drive","Ec":"Anchorage","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-10-07T00:00:00","Ed":"2022-10-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIDPFS1","S":2022,"En":"ID North Idaho Scrimmage #1","Ev":"4-H University of Idaho Research Park","Ea":"721 S. Lochsa Street","Ec":"Post Falls","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2022-10-08T00:00:00","Ed":"2022-10-08T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 10/10/2022","Ws":"2022-10-10T00:00:00","We":"2022-10-16T23:59:59","Wn":5,"Ec":10,"E":[{"Tc":"USAKJUS2","S":2022,"En":"AK Southeast Scrimmage #1","Ev":"Thunder Mountain High School","Ea":"3101 Diamond Pk Loop","Ec":"Juneau","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-10-15T00:00:00","Ed":"2022-10-15T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLS","S":2022,"En":"FL South Florida League Scrimmage and Volunteer Training","Ev":"St. Anthony Catholic School","Ea":"820 NE 3rd Street","Ec":"Fort Lauderdale","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-10-15T00:00:00","Ed":"2022-10-15T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USGAGAS","S":2022,"En":"GA N Georgia League Scrimmage","Ev":"Lakeview Academy","Ea":"796 Lakeview Drive","Ec":"Gainesville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-10-15T00:00:00","Ed":"2022-10-15T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USMNAVS","S":2022,"En":"MN FTC Mille Lacs / Pepin League Meet 0","Ev":"Eastview High School","Ea":"6200 140th St W","Ec":"Apple Valley","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-10-16T00:00:00","Ed":"2022-10-16T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USMNBES","S":2022,"En":"MN FTC Vermillion League Meet 0","Ev":"Becker Primary School","Ea":"12050 Hancock Street","Ec":"Becker","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-10-14T00:00:00","Ed":"2022-10-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USMSLAS","S":2022,"En":"MS LCS Build-it Day/Scrimmage","Ev":"Laurel Christian School","Ea":"1200 Highway 15","Ec":"Laurel","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2022-10-15T00:00:00","Ed":"2022-10-15T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USNYNYNYS","S":2022,"En":"NY-NYC Scrimmage","Ev":"Browning School","Ea":"52 E 62nd St, New York, NY 10065","Ec":"New York","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2022-10-15T00:00:00","Ed":"2022-10-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USORRBS","S":2022,"En":"OR North Coast League Meet 0","Ev":"Neah-Kah-Nie High School","Ea":"24705 Hwy 101 N","Ec":"Rockaway Beach","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-10-15T00:00:00","Ed":"2022-10-15T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXWPAMS","S":2022,"En":"TX-W\u0026P Amarillo Scrimmage","Ev":"AmTech Career Academy","Ea":"3601 Plains Boulevard","Ec":"Amarillo","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-10-15T00:00:00","Ed":"2022-10-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXWPMIS","S":2022,"En":"TX-W\u0026P Midland Scrimmage","Ev":"Midland College Athletic Building","Ea":"3600 N Garfield St","Ec":"Midland","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-10-15T00:00:00","Ed":"2022-10-15T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 10/17/2022","Ws":"2022-10-17T00:00:00","We":"2022-10-23T23:59:59","Wn":6,"Ec":19,"E":[{"Tc":"USFLSPS","S":2022,"En":"FL Gulf Coast League Scrimmage","Ev":"Hollins High School","Ea":"4940 62nd Street N","Ec":"St. Petersburg","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLACM1","S":2022,"En":"FL AeroCoast League Meet #1","Ev":"Gadsden County High School","Ea":"27001 Blue Star Hwy","Ec":"Havana","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAETOWM1","S":2022,"En":"GA Etowah Meet 1","Ev":"North Paulding High School","Ea":"300 N Paulding Dr #6675","Ec":"Dallas","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATHM1","S":2022,"En":"GA Caterpillar Meet 1","Ev":"Oconee County High School","Ea":"2721 Hog Mountain Rd","Ec":"Watkinsville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAWIM4","S":2022,"En":"IA Wind_Meet_2022-10-22","Ev":"Manson Northwest Webster School","Ea":"1601 15th St.","Ec":"Manson","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USKYKYM4","S":2022,"En":"KY Beaker Meet #1","Ev":"Morehead State University","Ea":"150 University Blvd","Ec":"Morehead","Es":"KY","Ect":"USA","Dn":"Kentucky","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIOCM1","S":2022,"En":"MI OCCRA Meet 1","Ev":"Marian High School","Ea":"7225 Lahser Road","Ec":"Bloomfield Hills","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIDHS1","S":2022,"En":"MI Detroit Metro Scrimmage","Ev":"Riverside Middle School","Ea":"25900 W. Warren Road","Ec":"Dearborn Heights","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USOHNAS","S":2022,"En":"OH Central Ohio League Meet 0","Ev":"Marburn Academy","Ea":"9555 Johnstown Rd","Ec":"New Albany","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USORROS","S":2022,"En":"OR SOAR League Meet 0","Ev":"Fremont Middle School","Ea":"850 W Keady Ct","Ec":"Roseburg","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USORSPS","S":2022,"En":"OR Midwestern League Meet 0","Ev":"Thurston High School","Ea":"333 58th St","Ec":"Springfield","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXCEGCM8","S":2022,"En":"TX-Central Sylvia Earle Scrimmage 1","Ev":"Gregory-Portland High School","Ea":"4601 Wildcat Dr","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXWPLUS","S":2022,"En":"TX-W\u0026P Lubbock-A Scrimmage","Ev":"Estacado High School","Ea":"1504 E Itasca St","Ec":"Lubbock","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNONLM1","S":2022,"En":"TX-North N-League Meet 1","Ev":"Boys \u0026 Girls Club of McKinney","Ea":"701 S Church St, McKinney, TX 75069","Ec":"McKinney, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOCLM1","S":2022,"En":"TX-North C-League Meet 1","Ev":"Conrad High School, DISD","Ea":"7502 Fair Oaks Ave, Dallas, TX 75231","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOHAM1","S":2022,"En":"TX-South Hawking Meet 1","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOBLM1","S":2022,"En":"TX-North B-League Meet 1","Ev":"W.G. Thomas Coliseum, Birdville ISD","Ea":"6108 Broadway Avenue, Haltom City, TX 76117","Ec":"Haltom City, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOCUM1","S":2022,"En":"TX-South Curie Meet 1","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGCM7","S":2022,"En":"TX-Central Daphne Koller Scrimmage 1","Ev":"Gregory-Portland High School","Ea":"4601 Wildcat Dr","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-10-22T00:00:00","Ed":"2022-10-22T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 10/24/2022","Ws":"2022-10-24T00:00:00","We":"2022-10-30T23:59:59","Wn":7,"Ec":36,"E":[{"Tc":"USAKAKSCM2","S":2022,"En":"AK Southcentral Alaska League Meet #2","Ev":"Bettye Davis East Anchorage High School","Ea":"4025 E Northern Lights Boulevard","Ec":"Anchorage","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-10-25T00:00:00","Ed":"2022-10-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAOJS","S":2022,"En":"CA-SoCal League V - Meet 0","Ev":"Ojai Valley School \u2013 Littlefield Student Commons","Ea":"10820 Revees Road","Ec":"Ojai","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLNEM1","S":2022,"En":"FL North East League Meet #1","Ev":"Bolles Bartram Campus","Ea":"2264 Bartram Road","Ec":"Jacksonville","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLOCM1","S":2022,"En":"FL ONECLAY League Meet #1","Ev":"Wilkinson Junior High Cafeteria","Ea":"5025 Co Rd 218","Ec":"Middleburg","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLORS","S":2022,"En":"FL Orlando Robotics League Scrimmage","Ev":"Lake Highland Preparatory School","Ea":"901 Highland Avenue","Ec":"Orlando","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USGADOUGM1","S":2022,"En":"GA Douglasville Meet 1","Ev":"Douglas County High School","Ea":"8705 Campbellton Street","Ec":"Douglasville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAMACM1","S":2022,"En":"GA Macon Meet 1","Ev":"First Presbyterian Day School","Ea":"5671 Calvin Dr","Ec":"Macon","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAMARIM1","S":2022,"En":"GA Marietta Meet 1","Ev":"Wheeler High School","Ea":"375 Holt Rd.","Ec":"Marietta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATLM1","S":2022,"En":"GA Atlanta Meet 1","Ev":"Marist School","Ea":"3790 ASHFORD DUNWOODY ROAD NE","Ec":"Atlanta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USHI01M6","S":2022,"En":"HI Iolani School","Ev":"Iolani School","Ea":"563 Kamoku St.","Ec":"Honolulu","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM11","S":2022,"En":"Hydro_Meet_2022-10-29","Ev":"West Burlington Jr/Sr High","Ea":"408 W. Van Weiss Blvd.","Ec":"West Burlington","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAMAM5","S":2022,"En":"IA Magnetic_Meet_2022-10-29","Ev":"Sergent Bluff Middle School","Ea":"208 Port Neal Rd","Ec":"Sergent Bluff","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIASOM8","S":2022,"En":"IA Solar_Meet_2022-10-29","Ev":"Lakewood Elementary","Ea":"9210 Happy Hollow Dr.","Ec":"Norwalk","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIWCM1","S":2022,"En":"MI Metro Detroit Meet 1","Ev":"Plymouth Christian Academy","Ea":"43065 Joy Rd.","Ec":"Canton","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMISCM1","S":2022,"En":"MI South Central Meet 1","Ev":"Mason High School","Ea":"1001 S. Barnes St.","Ec":"Mason","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-10-27T00:00:00","Ed":"2022-10-27T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIOCM5","S":2022,"En":"MI OCCRA Meet 2","Ev":"Clarkston Jr. High School","Ea":"6595 Waldon Rd.","Ec":"Clarkston","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-10-28T00:00:00","Ed":"2022-10-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMISCM2","S":2022,"En":"MI South Central Meet 2","Ev":"Chelsea Robotics Center","Ea":"500 Washington Street","Ec":"Chelsea","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNCM1","S":2022,"En":"MN FTC Cass Lake League Meet 1","Ev":"St. Paul Academy","Ea":"1712 Randolph Ave","Ec":"St. Paul","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-10-26T00:00:00","Ed":"2022-10-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNMM1","S":2022,"En":"MN FTC Mille Lacs League Meet 1","Ev":"DACS Building","Ea":"630 1st Avenue NW","Ec":"Byron","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNPM1","S":2022,"En":"MN FTC Pepin League Meet 1","Ev":"DACS Building","Ea":"630 1st Avenue NW","Ec":"Byron","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMSWVS1","S":2022,"En":"MS Water Valley Build-it Day/Scrimmage","Ev":"Water Valley High School","Ea":"550 Market St","Ec":"Water Valley","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USNCRAS","S":2022,"En":"NC Robot in 6 Weeks","Ev":"Cardinal Gibbons High School","Ea":"1401 Edwards Mill Rd","Ec":"Raleigh","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USNHMAS","S":2022,"En":"NH Derryfield Scrimmage #1","Ev":"The Derryfield School","Ea":"2108 River Road, Manchester, NH 03104","Ec":"Manchester","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USNJNEM3","S":2022,"En":"NJ 1029-P1  NE Edge League Meet (Saturday)","Ev":"Governer Livingston High School","Ea":"175 Watchung Blvd","Ec":"Berkeley Heights","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJNOM3","S":2022,"En":"NJ 1030-P1  Northern League meet (Sunday)","Ev":"Bergen Catholic High School","Ea":"1040 Oradell Ave","Ec":"Oradell","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-10-30T00:00:00","Ed":"2022-10-30T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNVLVS","S":2022,"En":"NV Southern Scrimmage","Ev":"Pinecrest Academy of Nevada - Sloan Canyon","Ea":"675 E Dale Ave","Ec":"Henderson","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":0},{"Tc":"USNVRES","S":2022,"En":"NV Northern Scrimmage","Ev":"Boys And Girls Club of Truckee Meadows - Carano Facility","Ea":"1090 Bresson Ave","Ec":"Reno","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":0},{"Tc":"USOKOKLAM3","S":2022,"En":"OK Mustang - October","Ev":"Mustang High School","Ea":"801 S Snyder Dr","Ec":"Mustang","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORPES","S":2022,"En":"OR Columbia Basin League Meet 0","Ev":"Pendleton High School","Ea":"1800 NW Carden Ave","Ec":"Pendleton","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-10-26T00:00:00","Ed":"2022-10-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USORHIS","S":2022,"En":"OR Silicon Forest League Meet 0","Ev":"Hillsboro High School","Ea":"3285 SE Rood Bridge Rd","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USORPOS","S":2022,"En":"OR Rose City League Meet 0","Ev":"TBD","Ea":"TBD","Ec":"Portland","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USORNCM1","S":2022,"En":"OR North Coast League Meet 1","Ev":"Neah-Kah-Nie High School","Ea":"24705 Hwy 101 N","Ec":"Rockaway Beach","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPWOS","S":2022,"En":"TX-W\u0026P Lubbock-B Scrimmage","Ev":"Frenship High School Student Center","Ea":"902 Dowden Rd","Ec":"Wolfforth","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXCEAUS1","S":2022,"En":"TX-Central X-STREAM Scrimmage 1","Ev":"Kipp Austin Collegiate","Ea":"8004 Cameron Road","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNOFMS","S":2022,"En":"TX-North The Screamage","Ev":"The Roboplex at Marcus HS","Ea":"5707 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-10-29T00:00:00","Ed":"2022-10-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXCEWAS","S":2022,"En":"TX-Central Waco Scrimmage 1","Ev":"TBD","Ea":"TBD","Ec":"Waco","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-10-27T00:00:00","Ed":"2022-10-27T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 10/31/2022","Ws":"2022-10-31T00:00:00","We":"2022-11-06T23:59:59","Wn":8,"Ec":57,"E":[{"Tc":"AUCAQ","S":2022,"En":"AU Queensland qualifier","Ev":"Grace Lutheran College","Ea":"129 Toohey St","Ec":"Caboolture","Es":"QLD","Ect":"Australia","Dn":"Australia","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"CAABABNAM1","S":2022,"En":"AB Northern Alberta Round #1","Ev":"\u00C9cole Maurice-Lavall\u00E9e","Ea":"8828 95 St","Ec":"Edmonton","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"USAZFLS","S":2022,"En":"AZ Northern Scrimmage","Ev":"Coconino High School","Ea":"2801 N. Izabel St.","Ec":"Flagstaff","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAZCHS","S":2022,"En":"AZ First Look - Chandler Scrimmage","Ev":"Valley Christian High School","Ea":"6900 W Galveston St","Ec":"Chandler","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAZGOS","S":2022,"En":"AZ Goodyear Scrimmage","Ev":"Trivium Preparatory Academy","Ea":"2001 N Bullard Ave","Ec":"Goodyear","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALALCS2","S":2022,"En":"CA-SoCal League C1 - Meet 0","Ev":"La Ca\u00F1ada High School","Ea":"4463 Oak Grove Drive","Ec":"La Canada","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALASOS","S":2022,"En":"CA-SoCal League D - Meet 0","Ev":"Notre Dame High School","Ea":"13645 Riverside Drive","Ec":"Sherman Oaks","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALAROS1","S":2022,"En":"CA-SoCal League F2 - Meet 0","Ev":"Heritage High School","Ea":"26001 Briggs Road","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALAROS2","S":2022,"En":"CA-SoCal League F1 - Meet 0","Ev":"Heritage High School","Ea":"26001 Briggs Road","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLOLM1","S":2022,"En":"FL Orlando Robotics League Meet #1","Ev":"Lake Highland Preparatory School","Ea":"741 N Mills Ave","Ec":"Orlando","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLROM2","S":2022,"En":"FL ROBOT League McKeel Academy Robotics Spectacular","Ev":"Mckeel Academy of Science \u0026 Technology Gym","Ea":"1810 West Parker Street","Ec":"Lakeland","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLSPM3","S":2022,"En":"FL Space Coast League Meet #1","Ev":"Oviedo High School","Ea":"601 King Street","Ec":"Oviedo","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLACM2","S":2022,"En":"FL AeroCoast League Meet #2","Ev":"Montford Middle School","Ea":"5789 Pimlico Dr","Ec":"Tallahassee","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATLM2","S":2022,"En":"GA Atlanta Meet 2","Ev":"The Walker School","Ea":"700 Cobb Pkwy North","Ec":"Marietta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAALBM1","S":2022,"En":"GA Albany Meet 1","Ev":"4C Academy","Ea":"1615 Newton Rd.","Ec":"Albany","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGANORTM2","S":2022,"En":"GA N Georgia Meet 2","Ev":"Towns Co. High School","Ea":"1400 US-76","Ec":"Hiawassee","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGANORTM1","S":2022,"En":"GA N Georgia Meet 1","Ev":"Towns Co. High School","Ea":"1400 US-76","Ec":"Hiawassee","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USHI01M5","S":2022,"En":"HI Island School","Ev":"Island School","Ea":"3-1875 Kaumuali\u0027i Hwy","Ec":"Lihue, Kauai","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAWIM6","S":2022,"En":"IA Wind_Meet_2022-11-05","Ev":"Ames High School","Ea":"1801 Ridgewood Ave","Ec":"Ames","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM10","S":2022,"En":"IA Hydro_Meet_2022-11-05","Ev":"City High School","Ea":"Lower Commons","Ec":"Iowa City","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAMAM3","S":2022,"En":"IA Magnetic_Meet_2022-11-05","Ev":"MOC-FV High School","Ea":"708 8th St. SE","Ec":"Orange City","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIASOM7","S":2022,"En":"IA Solar_Meet_2022-11-05","Ev":"PCM Middle School","Ea":"407 East Plainsmen Road","Ec":"Prairie City","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/PLwyAT5ACFw","eventType":1000},{"Tc":"USIDPFS2","S":2022,"En":"ID North Idaho Scrimmage #2","Ev":"4-H University of Idaho Research Park","Ea":"721 S. Lochsa St.","Ec":"Post Falls","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USILNEM1","S":2022,"En":"IL Northeast Lake Meet 1","Ev":"Deerfield High School","Ea":"1959 Waukegan Rd","Ec":"Deerfield","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-06T00:00:00","Ed":"2022-11-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILNSM1","S":2022,"En":"IL North Shore Meet 1","Ev":"Grainger","Ea":"100 Grainger Parkway","Ec":"Lake Forest","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCMM1A","S":2022,"En":"IL Chicago Meet 1A","Ev":"Excel Academy of the SouthWest","Ea":"7050 S. Washtenaw Ave.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILPM1","S":2022,"En":"IL Peoria Meet 1","Ev":"Dunlap High School","Ea":"5220 Legion Hall Rd","Ec":"Dunlap","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIOCM2","S":2022,"En":"MI OCCRA Meet 3","Ev":"Walled Lake Western High School","Ea":"600 Beck Road","Ec":"Commerce Charter Twp,","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIKEQ","S":2022,"En":"MI Kentwood FTC Qualifier","Ev":"East Kentwood Freshman Campus","Ea":"6170 Valley Lane Dr SE","Ec":"Kentwood","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-04T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMIHAQ","S":2022,"En":"MI Hartland FTC Qualifier","Ev":"Hartland Middle School at Ore Creek","Ea":"3250 Hartland Road","Ec":"Hartland","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-04T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMIFRQ2","S":2022,"En":"MI Freeland FTC Qualifier","Ev":"Freeland Middle/High School","Ea":"8250 Webster Road","Ec":"Freeland","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-04T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMISCM7","S":2022,"En":"MI South Central Meet 3","Ev":"Bert Walker Hall, Jackson College","Ea":"2111 Emmons Rd.","Ec":"Jackson","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-01T00:00:00","Ed":"2022-11-01T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIWCM2","S":2022,"En":"MI Metro Detroit Meet 2","Ev":"Riverside Middle School","Ea":"25900 W. Warren Road","Ec":"Dearborn Hts.","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSWMIM6","S":2022,"En":"MOKS-MO Camdenton","Ev":"Camdenton Middle School","Ea":"88 Laker Dr","Ec":"Camdenton","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIACHM5","S":2022,"En":"IA Chemical_Meet_2022-11-05","Ev":"Marian High School","Ea":"Gymnasium","Ec":"Omaha","Es":"NE","Ect":"USA","Dn":"Iowa","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJNOM7","S":2022,"En":"NJ 1105-P1-PM Northern League Meet (Saturday)","Ev":"Don Bosco Prep High School","Ea":"492 Franklin Turnpike","Ec":"Ramsey","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJNOM2","S":2022,"En":"NJ 1105-P1-AM   Northern League meet (Saturday)","Ev":"Don Bosco Prep High School","Ea":"492 Franklin Turnpike","Ec":"Ramsey","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJUCM2","S":2022,"En":"NJ 1106-P1 Upper Central League Meet (Sunday)","Ev":"Hillsbourgh High School","Ea":"466 Raider Blvd","Ec":"Hillsborough","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-06T00:00:00","Ed":"2022-11-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNYNYQUQ1","S":2022,"En":"NY-NYC Qualifier 1","Ev":"High School For Construction Trade Engineering \u0026 Architecture","Ea":"94-06 104th street","Ec":"Queens","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYNYOPQ","S":2022,"En":"NY-NYC Qualifier 2","Ev":"High School For Construction Trade Engineering \u0026 Architecture","Ea":"94-06 104th street","Ec":"Ozone Park","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2022-11-06T00:00:00","Ed":"2022-11-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHCOHLM1","S":2022,"En":"OH Central Ohio League Meet 1","Ev":"Centennial High School","Ea":"1441 Bethel Rd","Ec":"Columbus","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2022-11-02T00:00:00","Ed":"2022-11-02T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOKOKLAM5","S":2022,"En":"OK Muskogee November - afternoon","Ev":"Muskogee High School","Ea":"3200 E Shawnee Rd","Ec":"Muskogee","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOKOKLAM4","S":2022,"En":"OK Muskogee November - morning","Ev":"Muskogee High School","Ea":"3200 E Shawnee Rd","Ec":"Muskogee","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCESTM3","S":2022,"En":"TX-Central SSTallions Meet 1","Ev":"SST (San Antonio)","Ea":"4410 David Edwards Dr","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNODLM1","S":2022,"En":"TX-North D-League Meet 1","Ev":"Dealey Montessori Academy, DISD","Ea":"6501 Royal Ln, Dallas, TX 75230","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOSLM1","S":2022,"En":"TX-Houston S Meet 1","Ev":"Palacios High School","Ea":"100 Shark Dr.","Ec":"Palacios","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOPAS","S":2022,"En":"TX-Houston South League Practice Session","Ev":"Palacios High School","Ea":"1000 Shark Dr","Ec":"Palacios","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2022-11-02T00:00:00","Ed":"2022-11-04T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXWPEPM1","S":2022,"En":"TX-W\u0026P El Paso League Meet #1","Ev":"Da Vinci School for Science and the Arts","Ea":"785 Southwestern Dr","Ec":"El Paso","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWAHOM1","S":2022,"En":"WA Hopper League Meet 1","Ev":"St. George\u0027s School","Ea":"2929 W Waikiki Rd","Ec":"Spokane","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWATUM1","S":2022,"En":"WA Turing League Meet 1","Ev":"Bellevue International School","Ea":"445 128th Ave SE","Ec":"Bellevue","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-06T00:00:00","Ed":"2022-11-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWAAGM1","S":2022,"En":"WA Agnesi League Meet 1","Ev":"Hanford High School","Ea":"450 Hanford Street","Ec":"Richland","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWASAM1","S":2022,"En":"WA Salk League Meet 1","Ev":"Charles Wright Academy","Ea":"7723 Chambers Creek Rd W","Ec":"University Place","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWABRM1","S":2022,"En":"WA Brattain League Meet 1","Ev":"The Overlake School","Ea":"20301 NE 108th St","Ec":"Redmond","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-06T00:00:00","Ed":"2022-11-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWASPM1","S":2022,"En":"WA Spencer League Meet 1","Ev":"Mt. Si High School","Ea":"8651 Meadowbrook Way SE","Ec":"Snoqualmie","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-06T00:00:00","Ed":"2022-11-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWASHM1","S":2022,"En":"WA Shockley League Meet 1","Ev":"Lower Columbia College","Ea":"1600 Maple St","Ec":"Longview","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWABAM1","S":2022,"En":"WA Bardeen League Meet 1","Ev":"Cedarcrest High School","Ea":"29000 NE 150th St","Ec":"Duvall","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWALOM1","S":2022,"En":"WA Lovelace League Meet 1","Ev":"Capital High School","Ea":"2707 Conger Ave NW","Ec":"Olympia","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-05T00:00:00","Ed":"2022-11-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000}]},{"Wt":"of 11/07/2022","Ws":"2022-11-07T00:00:00","We":"2022-11-13T23:59:59","Wn":9,"Ec":86,"E":[{"Tc":"CAONSCS","S":2022,"En":"ON Fall Fiesta @ Bethune CI","Ev":"Dr. Norman Bethune Collegiate Institute","Ea":"200 Fundy Bay Blvd","Ec":"Scarborough","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAKJUS1","S":2022,"En":"AK Southeast Scrimmage #2","Ev":"Thunder Mountain High School","Ea":"3101 Diamond Pk Loop","Ec":"Juneau","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAKAKSCM3","S":2022,"En":"AK Southcentral Alaska League Meet #3","Ev":"Colony High School","Ea":"9550 East Bogard Road","Ec":"Palmer","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALASMS","S":2022,"En":"CA- SoCal League W - Meet 0","Ev":"Crossroads Elementary School","Ea":"1715 Olympic Blvd","Ec":"Santa Monica","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALALAS","S":2022,"En":"CA-SoCal League A1 - Meet 0","Ev":"Marlborough School","Ea":"250 South Rossmore Avenue","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALAVM1","S":2022,"En":"CA-SoCal League V - Meet 1","Ev":"Ojai Valley School \u2013 Littlefield Student Commons","Ea":"10820 Revees Road","Ec":"Ojai","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALACOS","S":2022,"En":"CA-SoCal League B - Meet 0","Ev":"Dominguez High School,","Ea":"15301 San Jose Avenue","Ec":"Compton","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALALCS1","S":2022,"En":"CA-SoCal League C2 - Meet 0","Ev":"Santa Fe Middle School","Ea":"148 W Duarte Rd","Ec":"Monrovia","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALACLS","S":2022,"En":"CA-SoCal League E - Meet 0","Ev":"The Webb Schools","Ea":"1175 W Baseline Road","Ec":"Claremont","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCOFCS","S":2022,"En":"CO Poudre High School","Ev":"Poudre High School","Ea":"201 Impala Drive","Ec":"Ft. Collins","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCODES","S":2022,"En":"CO University of Colorado Denver","Ev":"University of Colorado Denver","Ea":"1201 Larimer Street","Ec":"Denver","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLOCM2","S":2022,"En":"FL ONECLAY League Meet #2","Ev":"Orange Park Junior High : Cafeteria","Ea":"1500 Gano Avenue","Ec":"Orange Park","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLGCM1","S":2022,"En":"FL Gulf Coast League Meet #1","Ev":"Seminole High School","Ea":"8401 131st N","Ec":"Seminole","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLSFM1","S":2022,"En":"FL South Florida League Meet #1","Ev":"Coral Springs High School","Ea":"3205 N. University Drive","Ec":"Coral Springs","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATLM3","S":2022,"En":"GA Atlanta Meet 3","Ev":"Marist School","Ea":"3790 ASHFORD DUNWOODY ROAD NE","Ec":"Atlanta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAJACKM2","S":2022,"En":"GA Jackson Meet 2","Ev":"East Jackson High School","Ea":"1435 Hoods Mill Road","Ec":"Commerce","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATHM2","S":2022,"En":"GA Caterpillar Meet 2","Ev":"Oconee County High School","Ea":"2721 Hog Mountain Road","Ec":"Watkinsville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-08T00:00:00","Ed":"2022-11-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAETOWM2","S":2022,"En":"GA Etowah Meet 2","Ev":"North Paulding High School","Ea":"300 N Paulding Dr #6675","Ec":"Dallas","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAJACKM1","S":2022,"En":"GA Jackson Meet 1","Ev":"East Jackson High School","Ea":"1435 Hoods Mill Road","Ec":"Commerce","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAALBM2","S":2022,"En":"GA Albany Meet 2","Ev":"4C Academy","Ea":"1615 Newton Rd.","Ec":"Albany","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAMARIM2","S":2022,"En":"GA Marietta Meet 2","Ev":"Wheeler High School","Ea":"375 Holt Rd.","Ec":"Marietta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAETOWM3","S":2022,"En":"GA Etowah Meet 3","Ev":"North Paulding High School","Ea":"300 N Paulding Dr #6675","Ec":"Dallas","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USHI01M1","S":2022,"En":"HI Kalani High School","Ev":"Kalani High School","Ea":"4680 Kalaniana\u0027ole Highway","Ec":"Honolulu","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIASOM5","S":2022,"En":"IA Solar_Meet_2022-11-12","Ev":"Lakewood Elementary","Ea":"9210 Happy Hollow Dr.","Ec":"Norwalk","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/_nAa5vPzYjs","eventType":1000},{"Tc":"USIACRS","S":2022,"En":"IA Geothermal_Scrimmage_2022-11-09","Ev":"Trinity Lutheran School","Ea":"1361 7th Ave SW","Ec":"Cedar Rapids","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-09T00:00:00","Ed":"2022-11-09T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USIAGEM6","S":2022,"En":"IA Geothermal_Meet_2022-11-12","Ev":"Center Point-Urbana Middle School","Ea":"613 Summit St","Ec":"Center Point","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIANUM5","S":2022,"En":"IA Nuclear_Meet_2022-11-12","Ev":"Waverly-Shell Rock High School","Ea":"1405 4th St. SW","Ec":"Waverly","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM4","S":2022,"En":"IA Hydro_Meet_2022-11-12","Ev":"Sudlow Intermediat School","Ea":"1414 East Locust Street","Ec":"Davenport","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIACHM3","S":2022,"En":"IA Chemical_Meet_2022-11-12","Ev":"St. Alberts High School","Ea":"400 Gleason Ave","Ec":"Council Bluffs","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILFSM1","S":2022,"En":"IL Fox Valley South Meet 1","Ev":"Wheaton Academy","Ea":"900 Prince Crossing Road","Ec":"Wheaton","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCMM1B","S":2022,"En":"IL Chicago Meet 1B","Ev":"Hancock College Prep","Ea":"5437 West 64th Pl.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILFNM1","S":2022,"En":"IL Fox Valley North Meet 1","Ev":"Barrington High School,","Ea":"616 West Main Street","Ec":"Barrington","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCM1","S":2022,"En":"IL Central Meet 1","Ev":"Siebel Center for Design","Ea":"1208 S. Fourth St.","Ec":"Champaign","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILSSM1","S":2022,"En":"IL South Suburbs Meet 1","Ev":"Bradley-Bourbonnais Community High School","Ea":"700 W. North Street","Ec":"Bradley","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USKYKYM3","S":2022,"En":"KY Dunker Meet #1","Ev":"Murray State University","Ea":"1604 Olive St.","Ec":"Murray","Es":"KY","Ect":"USA","Dn":"Kentucky","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USLABRS","S":2022,"En":"LA Dark Matter and LSU SPM Scrimmage","Ev":"Patrick F Taylor Hall","Ea":"3304 S Quad Dr","Ec":"Baton Rouge","Es":"LA","Ect":"USA","Dn":"Louisiana","Sd":"2022-11-11T00:00:00","Ed":"2022-11-13T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USMIRHQ","S":2022,"En":"MI Rochester Hills FTC Qualifier","Ev":"Rochester High School","Ea":"1361 Walton Blvd.","Ec":"Rochester Hills","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-11T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMISCM3","S":2022,"En":"MI South Central Meet 4","Ev":"Mason High School","Ea":"1001 S. Barnes St.","Ec":"Mason","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-10T00:00:00","Ed":"2022-11-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIOCM4","S":2022,"En":"MI OCCRA Meet 4","Ev":"International Academy Okma","Ea":"1020 E Square Lake Rd.","Ec":"Bloomfield Hills","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-10T00:00:00","Ed":"2022-11-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIAHQ","S":2022,"En":"MI Avondale FTC Qualifier","Ev":"Avondale High School","Ea":"2800 Waukegan Street","Ec":"Auburn Hills","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-11T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMIWCM4","S":2022,"En":"MI Metro Detroit Meet 3","Ev":"Riverside Middle School","Ea":"25900 W. Warren Road","Ec":"Dearborn Hts.","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-10T00:00:00","Ed":"2022-11-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMISCM4","S":2022,"En":"MI South Central Meet 6","Ev":"Chelsea Robotics Center","Ea":"500 Washington Street","Ec":"Chelsea","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMILAQ","S":2022,"En":"MI Lakeview FTC Qualifier","Ev":"Lakeview Middle School","Ea":"300 S 28th Street","Ec":"Battle Creek","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-11T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMISCM8","S":2022,"En":"MI South Central Meet 5","Ev":"Bert Walker Hall, Jackson College","Ea":"2111 Emmons Rd.","Ec":"Jackson","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-11T00:00:00","Ed":"2022-11-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIKIQ","S":2022,"En":"MI Kingsford FTC Qualifier","Ev":"Kingsford Middle School","Ea":"431 Hamilton Avenue","Ec":"Kingsford","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-11T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMINBQ","S":2022,"En":"MI North Branch FTC Qualifier","Ev":"North Branch High School","Ea":"6598 Brush St, North","Ec":"North Branch","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-11T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMNCM2","S":2022,"En":"MN FTC Cass Lake League Meet 2","Ev":"St. Paul Academy","Ea":"1712 Randolph Ave","Ec":"St. Paul","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-11-10T00:00:00","Ed":"2022-11-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNEAQ","S":2022,"En":"MN FTC Eagan Sat. Nov. 12","Ev":"Eagan High School","Ea":"4185 Braddock Trail","Ec":"Eagan","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSSTLSM5","S":2022,"En":"MOKS-MO Oakville AM","Ev":"Oakville High School","Ea":"5557 Milburn Rd","Ec":"St. Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLSM6","S":2022,"En":"MOKS-MO Oakville PM","Ev":"Oakville High School","Ea":"5557 Milburn Rd","Ec":"St. Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSPS","S":2022,"En":"MOKS-MO Kickapoo Scrimmage","Ev":"Kickapoo High School","Ea":"3710 S Jefferson Ave","Ec":"Springfield","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USMTEHQ","S":2022,"En":"MT East Helena Qualifier","Ev":"East Helena High School","Ea":"2760 Valley Dr.","Ec":"East Helena","Es":"MT","Ect":"USA","Dn":"Montana","Sd":"2022-11-11T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USIAMAM8","S":2022,"En":"IA-NE Magnetic_Meet_2022-11-12","Ev":"South Sioux City High School","Ea":"3301 G Street","Ec":"South Sioux City","Es":"NE","Ect":"USA","Dn":"Iowa","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJSOM2","S":2022,"En":"NJ 1112-P1  Southern League Meet (Saturday)","Ev":"Howell High School","Ea":"405 Squankum Yellowbrook Rd","Ec":"Farmingdale","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJNEM2","S":2022,"En":"NJ 1113-P1  Northeast Edge League (Sunday)","Ev":"Westfield High School","Ea":"550 Dorian Road","Ec":"Westfield","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-13T00:00:00","Ed":"2022-11-13T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOHCIS","S":2022,"En":"OH Summit Country Day School Scrimmage","Ev":"Summit Country Day School","Ea":"2161 Grandin Rd","Ec":"Cincinnati","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USOHCOHLM2","S":2022,"En":"OH Central Ohio League Meet 2","Ev":"Newark Catholic High School","Ea":"1 Green Wave Drive","Ec":"Newark","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORSOM1","S":2022,"En":"OR SOAR League Meet 1","Ev":"Fremont Middle School","Ea":"850 W Keady Ct","Ec":"Roseburg","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORRCM1","S":2022,"En":"OR Rose City League Meet 1","Ev":"Franklin HS","Ea":"5405 SE Woodward St","Ec":"Portland","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORSFM1","S":2022,"En":"OR Silicon Forest League Meet 1","Ev":"Hillsboro High School","Ea":"3285 SE Rood Bridge Rd","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USPAKSS","S":2022,"En":"PA UCFSD FTC Scrimmage","Ev":"Patton Middle School","Ea":"760 Unionville Road","Ec":"Kennett Square","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2022-11-13T00:00:00","Ed":"2022-11-13T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":0},{"Tc":"USSCCHS","S":2022,"En":"SC Lowcountry Scrimmage 1","Ev":"Citadel Mall - Center Court","Ea":"2070 Sam Rittenburg Blvd","Ec":"Charleston","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNOULM1","S":2022,"En":"TX-North U-League Meet 1","Ev":"UME Preparatory Academy","Ea":"3838 TX-408 Spur, Dallas, TX 75236","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEKWM1","S":2022,"En":"TX-Central Kwolek Meet 1","Ev":"Judson Middle School","Ea":"9695 Schaefer Rd","Ec":"Converse","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCENSAM2","S":2022,"En":"TX-Central North San Field Meet 1","Ev":"Brandeis High School","Ea":"13011 Kyle Seale Pkwy","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPMDM1","S":2022,"En":"TX-W\u0026P Midland League Meet #1","Ev":"First Baptist Church Fellowship Hall","Ea":"2104 W Louisiana Ave","Ec":"Midland","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPAMM1","S":2022,"En":"TX-W\u0026P Amarillo League Meet #1","Ev":"Boys \u0026 Girls Club of Vernon","Ea":"2015 Yamparika St","Ec":"Vernon","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEXSTM6","S":2022,"En":"TX-Central X-STREAM A Meet 1","Ev":"Kipp Collegiate HS","Ea":"8004 Cameron Road","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEOH90M1","S":2022,"En":"TX- Central Old Highway 90 Meet 1","Ev":"Brentwood MS","Ea":"1626 W. Thompson Pl","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEAUS","S":2022,"En":"TX-Central Vandegrift HS Scrimmage","Ev":"Vandegrift HS","Ea":"9500 McNeil Drive","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-09T00:00:00","Ed":"2022-11-09T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNOMLM1","S":2022,"En":"TX-North M-League Meet 1","Ev":"MAS DFW","Ea":"1515 Blake Dr, Richardson, TX 75081","Ec":"Richardson, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEXSTM5","S":2022,"En":"TX-Central X-STREAM B Meet 1","Ev":"Kipp Collegiate HS","Ea":"8004 Cameron Road","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOCLM2","S":2022,"En":"TX-North C-League Meet 2","Ev":"Conrad High School, DISD","Ea":"7503 Fair Oaks Ave, Dallas, TX 75231","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOHAM2","S":2022,"En":"TX-South Hawking Meet 2","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGMM6","S":2022,"En":"TX-Central Diamonds Meet 1","Ev":"Westwood HS","Ea":"12400 Mellow Meadow Dr.","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOCUM2","S":2022,"En":"TX-South Curie Meet 2","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNONLM2","S":2022,"En":"TX-North N-League Meet 2","Ev":"Boys \u0026 Girls Club of McKinney","Ea":"702 S Church St, McKinney, TX 75069","Ec":"McKinney, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOTLM1","S":2022,"En":"TX-North T-League Meet 1","Ev":"New Tech High @ Coppell","Ea":"113 Samuel Blvd, Coppell, TX 75019","Ec":"Coppell, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCENSAM1","S":2022,"En":"TX-Central Hill Country Field Meet 1","Ev":"Brandeis High School","Ea":"13011 Kyle Seale Pkwy","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGCM6","S":2022,"En":"TX-Central Sylvia Earle Meet 2","Ev":"Gregory-Portland High School","Ea":"4601 Wildcat Dr","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOFLM1","S":2022,"En":"TX-North F-League Meet 1","Ev":"QD Academy","Ea":"4100 Legacy Dr, Plano, TX 75024","Ec":"Plano, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGCM5","S":2022,"En":"TX-Central Daphne Koller Meet 2","Ev":"Gregory-Portland High School","Ea":"4601 Wildcat Dr","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPLAM1","S":2022,"En":"TX-W\u0026P Lubbock-A League Meet #1","Ev":"Talkington School for Young Women Leaders","Ea":"415 N Ivory Ave","Ec":"Lubbock","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGMM5","S":2022,"En":"TX-Central Emeralds Meet 1","Ev":"Westwood HS","Ea":"12400 Mellow Meadow Dr","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPLBM1","S":2022,"En":"TX-W\u0026P Lubbock-B League Meet #1","Ev":"Floydada Collegiate Jr. High/High School","Ea":"215 N. White Street","Ec":"Floydada","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWAKNM1","S":2022,"En":"WA Knuth League Meet 1","Ev":"Weston High School","Ea":"4407 172nd St NE","Ec":"Arlington","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-11-12T00:00:00","Ed":"2022-11-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000}]},{"Wt":"of 11/14/2022","Ws":"2022-11-14T00:00:00","We":"2022-11-20T23:59:59","Wn":10,"Ec":80,"E":[{"Tc":"AUWOQ","S":2022,"En":"AU Wollongong Qualifier","Ev":"Wollongong TAFE","Ea":"Foleys Ln","Ec":"Wollongong","Es":"NSW","Ect":"Australia","Dn":"Australia","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"CAABABSAM1B","S":2022,"En":"AB Southern Alberta Round 1B","Ev":"Joane Cardinal Schubert High School","Ea":"19480 45 St SE","Ec":"Calgary","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2022-11-18T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"CAABABSAM1A","S":2022,"En":"AB Southern Alberta Round 1A","Ev":"Joane Cardinal Schubert High School","Ea":"19480 45 St SE","Ec":"Calgary","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2022-11-18T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"CAONAUQ","S":2022,"En":"ON Aurora Qualifier","Ev":"St. Maximilian Kolbe Catholic High School","Ea":"278 Wellington St E","Ec":"Aurora","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USAKAKSCLT","S":2022,"En":"AK Southcentral Alaska League Tournament","Ev":"Dimond High School","Ea":"2909 W 88th Avenue","Ec":"Anchorage","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-11-18T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USAZPHQ","S":2022,"En":"AZ Petrified Wood - Phoenix Qualifier","Ev":"Brophy College Preparatory","Ea":"4701 N. Central Ave.","Ec":"Phoenix","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1004},{"Tc":"USAZGIQ","S":2022,"En":"AZ Roadrunner - Gilbert Qualifier","Ev":"Gilbert Christian High School","Ea":"3632 E. Jasper Dr.","Ec":"Gilbert","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1004},{"Tc":"USCANOPNM1","S":2022,"En":"CA-NorCal Peninsula League Meet 1","Ev":"Jefferson High School","Ea":"6996 Mission Street","Ec":"Daly City","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDGAM1","S":2022,"En":"CA- San Diego Gauss Meet #1, Francis Parker","Ev":"Francis Parker School","Ea":"6501 Linda Vista Rd","Ec":"San Diego","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALADM1","S":2022,"En":"CA-SoCal League D - Meet 1","Ev":"Notre Dame High School","Ea":"13645 Riverside Drive","Ec":"Sherman Oaks","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSBM1A","S":2022,"En":"CA-NorCal South Bay Metro League Meet 1a","Ev":"Wilcox High School","Ea":"3250 Monroe Street","Ec":"Santa Clara","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDEUM1","S":2022,"En":"CA- San Diego Euclid Meet #1, Francis Parker","Ev":"Francis Parker School","Ea":"6501 Linda Vista Rd","Ec":"San Diego","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDDEM1","S":2022,"En":"CA- San Diego Descartes Meet #1, Francis Parker","Ev":"Francis Parker School","Ea":"6501 Linda Vista Rd","Ec":"San Diego","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDTUM1","S":2022,"En":"CA- San Diego Turing Meet #1, Francis Parker","Ev":"Francis Parker School","Ea":"6501 Linda Vista Rd","Ec":"San Diego","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANONEM1","S":2022,"En":"CA-NorCal North East League Meet 1","Ev":"Einstein Middle School","Ea":"9325 Mirandy Drive","Ec":"Sacramento","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAORS","S":2022,"En":"CA-SoCal League O1 - Meet 0","Ev":"Arena Soccer Park of Orange","Ea":"2190 N Canal St","Ec":"Orange","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALALAS2","S":2022,"En":"CA-SoCal League A2 - Meet 0","Ev":"YULA Boys School","Ea":"9760 Pico Blvd.","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCANOSBM1B","S":2022,"En":"CA-NorCal South Bay Metro League Meet 1b","Ev":"Wilcox High School","Ea":"3250 Monroe Street","Ec":"Santa Clara","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCOMOS","S":2022,"En":"CO Monumental Impact","Ev":"Monumental Impact","Ea":"55 Adams Street","Ec":"Monument","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLNEM2","S":2022,"En":"FL North East League Meet #2","Ev":"Bolles Bartram Campus","Ea":"2264 Bartram Road","Ec":"Jacksonville","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLSPM5","S":2022,"En":"FL Space Coast Cone Wars-May the Power be with You","Ev":"Seminole High School","Ea":"2701 Ridgewood Ave","Ec":"Sanford","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGADOUGM2","S":2022,"En":"GA Douglasville Meet 2","Ev":"Douglas County High School","Ea":"8705 Campbellton Street","Ec":"Douglasville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAMACM2","S":2022,"En":"GA Macon Meet 2","Ev":"First Presbyterian Day School","Ea":"5671 Calvin Dr","Ec":"Macon","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAMACM3","S":2022,"En":"GA Macon Meet 3","Ev":"First Presbyterian Day School","Ea":"5671 Calvin Dr","Ec":"Macon","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATLM4","S":2022,"En":"GA Atlanta Meet 4","Ev":"Marist School","Ea":"3790 ASHFORD DUNWOODY ROAD NE","Ec":"Atlanta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USHI01M3","S":2022,"En":"HI Kukui Grove Mall - Lihue","Ev":"Kukui Grove Mall - Lihue","Ea":"3-2600 Kaumualii Hwy","Ec":"Lihue, Kauai","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USHI01M2","S":2022,"En":"HI Le Jardin Academy","Ev":"Le Jardin Academy","Ea":"917 Kalanianaole Hwy","Ec":"Kailua","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM9","S":2022,"En":"IA Hydro_Meet_2022-11-19_IowaCity","Ev":"City High School","Ea":"Lower Commons Area","Ec":"Iowa City","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIACHM4","S":2022,"En":"IA Chemical_Meet_2022-11-19","Ev":"Creighton Prep High School","Ea":"7400 Western Ave","Ec":"Omaha","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIANUM3","S":2022,"En":"IA Nuclear_Meet_2022-11-19","Ev":"Wapsie Valley Jr/Sr High","Ea":"2535 Viking Ave","Ec":"Fairbank","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAGEM3","S":2022,"En":"IA Geothermal_Meet_2022-11-19","Ev":"Regis Middle School","Ea":"735 Prairie Dr. NE","Ec":"Cedar Rapids","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAGEM7","S":2022,"En":"IA Geothermal_Meet_2022-11-17","Ev":"Washington High School","Ea":"2205 Forest Dr","Ec":"Cedar Rapids","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-17T00:00:00","Ed":"2022-11-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAWIM7","S":2022,"En":"IA Wind_Meet_2022-11-19","Ev":"Southview Middle School","Ea":"1020 SW Cherry St","Ec":"Ankeny","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIASOM6","S":2022,"En":"IA Solar_Meet_2022-11-19","Ev":"DMACC Urban Campus","Ea":"1144 7th St.","Ec":"Des Moines","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/9gYKX1_NpQg","eventType":1000},{"Tc":"USIAMAM9","S":2022,"En":"IA Magnetic_Meet_2022-11-19","Ev":"Sioux City East Middle School","Ea":"5401 Lorraine Ave","Ec":"Sioux City","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM8","S":2022,"En":"IA Hydro_Meet_2022-11-19_Davenport","Ev":"Central High School","Ea":"Performing Arts Center","Ec":"Davenport","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM5","S":2022,"En":"IA Hydro_Meet_2022-11-17","Ev":"Solon Community Rec Center","Ea":"313 S. Iowa Street","Ec":"Solon","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-17T00:00:00","Ed":"2022-11-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILSM1","S":2022,"En":"IL Southern Meet 1","Ev":"SIUE Engineering Bldg","Ea":"61 Circle Dr","Ec":"Edwardsville","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILWM1","S":2022,"En":"IL Western Meet 1","Ev":"Riverdale High School","Ea":"9622 256th St N","Ec":"Port Byron","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILRM1","S":2022,"En":"IL Rockford Meet 1","Ev":"Rockford Christian High School","Ea":"1401 N Bell School Rd","Ec":"Rockford","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCMM1C","S":2022,"En":"IL Chicago Meet 1C","Ev":"Lindblom HS","Ea":"6130 S Wolcott Ave.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCWM3","S":2022,"En":"MOKS-KS Schlagle KC West AM","Ev":"F. L. Schlagle High School","Ea":"2214 N 59 St","Ec":"Kansas City","Es":"KS","Ect":"USA","Dn":"Missouri","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCEM4","S":2022,"En":"MOKS-KS Schlagle KC East PM","Ev":"F. L. Schlagle High School","Ea":"2214 N 59 St","Ec":"Kansas City","Es":"KS","Ect":"USA","Dn":"Missouri","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMISCM5","S":2022,"En":"MI South Central Meet 7","Ev":"Mason High School","Ea":"1001 S. Barnes St.","Ec":"Mason","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-17T00:00:00","Ed":"2022-11-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMILOQ2","S":2022,"En":"MI Lake Orion FTC Qualifier","Ev":"Waldon Middle School","Ea":"2509 Waldon Road","Ec":"Lake Orion","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-18T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMIHOQ","S":2022,"En":"MI Howell FTC Qualifier","Ev":"Parker Middle School","Ea":"400 Wright Road","Ec":"Howell","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-18T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMIOCM3","S":2022,"En":"MI OCCRA Meet 5","Ev":"Birmingham Seaholm High School","Ea":"2436 W Lincoln Street","Ec":"Birmingham","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMINOQ","S":2022,"En":"MI Novi FTC Qualifier","Ev":"Novi Middle School","Ea":"49000 11 Mile Road","Ec":"Novi","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-18T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMITEQ","S":2022,"En":"MI Bedford FTC Qualifier","Ev":"Bedford Senior HIgh School","Ea":"8285 Jackman Road","Ec":"Temperance","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-18T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMISCM9","S":2022,"En":"MI South Central Meet 8","Ev":"Bert Walker Hall, Jackson College","Ea":"2111 Emmons Rd.","Ec":"Jackson","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-18T00:00:00","Ed":"2022-11-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIFRQ","S":2022,"En":"MI Fruitport FTC Qualifier","Ev":"Fruitport High School","Ea":"357 N. Sixth Avenue","Ec":"Fruitport","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-18T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMISCM6","S":2022,"En":"MI South Central Meet 9","Ev":"Chelsea Robotics Center","Ea":"500 Washington Street","Ec":"Chelsea","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIWCM3","S":2022,"En":"MI Metro Detroit Meet 4","Ev":"Unis Middle School","Ea":"7801 Maple St.","Ec":"Dearborn","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-16T00:00:00","Ed":"2022-11-16T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNPM2","S":2022,"En":"MN FTC Pepin League Meet 2","Ev":"MURA Field","Ea":"2131 N. 12th Ave.","Ec":"Minneapolis","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNVM1","S":2022,"En":"MN FTC Vermillion League Meet 1","Ev":"Prairie View Elementary School","Ea":"12220 80th St NE","Ec":"Otsego","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-11-18T00:00:00","Ed":"2022-11-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNPLQ1","S":2022,"En":"MN FTC Prior Lake Sat. Nov. 19","Ev":"Prior Lake High School","Ea":"7575 150th St W","Ec":"Prior Lake","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMNMM2","S":2022,"En":"MN FTC Mille Lacs League Meet 2","Ev":"MURA Field","Ea":"2131 N. 12th Ave.","Ec":"Minneapolis","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNPLQ2","S":2022,"En":"MN FTC Prior Lake Sun. Nov. 20","Ev":"Prior Lake High School","Ea":"7575 150th St W","Ec":"Prior Lake","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSSTLSM7","S":2022,"En":"MOKS-MO Lutheran Church of the Resurrection","Ev":"Lutheran Church of the Resurrection","Ea":"9907 Sappington Road","Ec":"Saint Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM8","S":2022,"En":"MOKS-MO McCluer South-Berkeley STEAM Academy","Ev":"STEAM Academy at McCluer South-Berkeley High School","Ea":"201 Brotherton Ln","Ec":"Ferguson","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMSOXS1","S":2022,"En":"MS Gulf Coast Scrimmage","Ev":"West Harrison High School","Ea":"1111 Jackson Ave W","Ec":"Oxford","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USNHHUS2","S":2022,"En":"NH Alvirne Scrimmage #2","Ev":"Alvirne High School","Ea":"200 Derry Rd, Hudson, NH 03051","Ec":"Hudson","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USNJUCM8","S":2022,"En":"NJ 1120-P2 PM Upper Central League Meet (Sunday)","Ev":"Dicherson School","Ea":"250 Rt 24","Ec":"Chester","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJUCM5","S":2022,"En":"NJ 1120-P2  AM Upper Central League Meet (Sunday)","Ev":"Dickerson School","Ea":"250 Rpite 24","Ec":"Chester","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJNOM1","S":2022,"En":"NJ 1119-P2  Northern League meet (Saturday)","Ev":"Ridgewood High School","Ea":"627 E Ridgewood Ave","Ec":"Ridgewood","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNVNOM1N","S":2022,"En":"NV Northern League Meet # 1N","Ev":"Truckee High School - Cafeteria","Ea":"11725 Donner Pass Rd","Ec":"Truckee","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNVSOM1S","S":2022,"En":"NV Southern League Meet # 1S","Ev":"The Meadows School","Ea":"8601 Scholar Ln","Ec":"Las Vegas","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USOHLOS","S":2022,"En":"OH Loveland Scrimmage","Ev":"Loveland High School","Ea":"1 Tiger Trail","Ec":"Loveland","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2022-11-20T00:00:00","Ed":"2022-11-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USOKOKLAM7","S":2022,"En":"OK Bishop Kelley - afternoon","Ev":"Bishop Kelley High School","Ea":"3905 S Hudson Ave","Ec":"Tulsa","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOKOKLAM6","S":2022,"En":"OK Bishop Kelley - morning","Ev":"Bishop Kelley High School","Ea":"3905 S Hudson Ave","Ec":"Tulsa","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORMWM1","S":2022,"En":"OR Midwestern League Meet 1","Ev":"Thurston High School","Ea":"333 58th St","Ec":"Springfield","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORNCM3","S":2022,"En":"OR North Coast League Meet 2","Ev":"Neah-Kah-Nie High School","Ea":"24705 Hwy 101 N","Ec":"Rockaway Beach","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORCBM1","S":2022,"En":"OR Columbia Basin League Meet 1","Ev":"Pendleton High School","Ea":"1800 NW Carden Ave","Ec":"Pendleton","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-11-16T00:00:00","Ed":"2022-11-16T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USRINKS","S":2022,"En":"RI Holiday Battle Scrimmage","Ev":"North Kingstown High School","Ea":"150 Fairway Drive","Ec":"North Kingstown","Es":"RI","Ect":"USA","Dn":"Rhode Island","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNOBLM2","S":2022,"En":"TX-North B-League Meet 2","Ev":"W.G. Thomas Coliseum, Birdville ISD","Ea":"6108 Broadway Avenue, Haltom City, TX 76117","Ec":"Haltom City, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOXMLM1B","S":2022,"En":"TX-North X-League Metro Meet 1B","Ev":"Roboplex at Marcus HS, LISD","Ea":"5708 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOTEM1","S":2022,"En":"TX-South Tesla Meet 1 (Laredo)","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOXMLM1A","S":2022,"En":"TX-North X-League Metro Meet 1A","Ev":"Roboplex at Marcus HS, LISD","Ea":"5707 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOSELM1","S":2022,"En":"TX-Houston SE Meet 1","Ev":"Lutheran South Academy","Ea":"12555 Ryewater Dr.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2022-11-19T00:00:00","Ed":"2022-11-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEWAM1","S":2022,"En":"TX-Central Waco League Meet 1","Ev":"TBD","Ea":"TBD","Ec":"Waco","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-17T00:00:00","Ed":"2022-11-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000}]},{"Wt":"of 11/21/2022","Ws":"2022-11-21T00:00:00","We":"2022-11-27T23:59:59","Wn":11,"Ec":17,"E":[{"Tc":"AUPYQ","S":2022,"En":"AU Sydney Qualifier","Ev":"Pymble Ladies College","Ea":"20-64 Avon Rd","Ec":"Pymble","Es":"NSW","Ect":"Australia","Dn":"Australia","Sd":"2022-11-27T00:00:00","Ed":"2022-11-27T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"AUTOQ","S":2022,"En":"AU Adelaide Qualifier","Ev":"The Student Robotics Club of South Australia, Inc (the RoboRoos)","Ea":"1 Tonsley Boulevard, Tonsley Innovation District","Ec":"Tonsley","Es":"SA","Ect":"Australia","Dn":"Australia","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"CAABABNAM2","S":2022,"En":"AB Northern Alberta Round #2","Ev":"Lindsay Thurber Comprehensive High School","Ea":"4204 58 St","Ec":"Red Deer","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"CABCVAS2","S":2022,"En":"BC Vancouver Scrimmage 2","Ev":"St. Patrick\u0027s Regional Secondary","Ea":"115 E 11th Ave, Vancouver, BC","Ec":"Vancouver","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2022-11-27T00:00:00","Ed":"2022-11-27T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"CABCVAS3","S":2022,"En":"BC Victoria Scrimmage 3","Ev":"St. Margaret\u0027s School","Ea":"1080 Lucas Ave, Victoria,","Ec":"Vancouver","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"CABCVAS","S":2022,"En":"BC Vancouver Scrimmage 1","Ev":"St. Patrick\u0027s Regional Secondary","Ea":"115 E 11th Ave, Vancouver, BC","Ec":"Vancouver","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"CAONSCQ2","S":2022,"En":"ON Central Scarborough Qualifier","Ev":"David \u0026 Mary Thomson CI","Ea":"125 Brockley Dr.","Ec":"Scarborough","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"KZALQ1","S":2022,"En":"KZ Haileybury","Ev":"Al Farabi","Ea":"112","Ec":"Almaty","Es":"ALA","Ect":"Kazakhstan","Dn":"Kazakhstan","Sd":"2022-11-26T00:00:00","Ed":"2022-11-27T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"NLNLM6","S":2022,"En":"NL League Meet Eindhoven","Ev":"Lorentz Casimir Lyceum","Ea":"Celebeslaan 10","Ec":"Eindhoven","Es":"NB","Ect":"Netherlands","Dn":"Netherlands","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/ftcnetherlands","eventType":1000},{"Tc":"USGAALBM3","S":2022,"En":"GA Albany Meet 3","Ev":"4C Academy","Ea":"1615 Newton Rd.","Ec":"Albany","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USHI01M4","S":2022,"En":"HI Mililani High School","Ev":"Mililani High School","Ea":"95-1200 Meheula Parkway","Ec":"Mililani","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAGEM4","S":2022,"En":"IA Geothermal_Meet_2022-11-21","Ev":"Marion High School","Ea":"675 South 15th St","Ec":"Marion","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-11-21T00:00:00","Ed":"2022-11-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIOCM6","S":2022,"En":"MI OCCRA Meet 6","Ev":"Baker MIddle School","Ea":"1359 Torpey Rd.","Ec":"Troy","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-11-22T00:00:00","Ed":"2022-11-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJUCM7","S":2022,"En":"NJ 1126-P1-PM  Upper Central League Meet (Saturday)","Ev":"Grace Church on the Mount","Ea":"758 NJ-10 Randolph Campus","Ec":"Randolph","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJUCM1","S":2022,"En":"NJ 1126-P1-AM  Upper Central League Meet (Saturday)","Ev":"Grace Church on the mount - Randolph Campus","Ea":"758 NJ 10","Ec":"Randolph","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-26T00:00:00","Ed":"2022-11-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJSOM3","S":2022,"En":"NJ 1127-P1  AM Southern League Meet (Sunday)","Ev":"Girl Scouts of Jersey Shore PAC","Ea":"127 Yellowbrook Rd","Ec":"Farmingdale","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-27T00:00:00","Ed":"2022-11-27T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJSOM7","S":2022,"En":"NJ 1127-P1 PM Southern League Meet (Sunday)","Ev":"Girl Scouts of Jersey Shore PAC","Ea":"127 Yellowbrook Rd","Ec":"Farmingdale","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-11-27T00:00:00","Ed":"2022-11-27T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000}]},{"Wt":"of 11/28/2022","Ws":"2022-11-28T00:00:00","We":"2022-12-04T23:59:59","Wn":12,"Ec":95,"E":[{"Tc":"CAONSUQ","S":2022,"En":"ON Sudbury Qualifier","Ev":"Lo-Ellen Park Secondary School","Ea":"275 Loachs Rd","Ec":"Sudbury","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"CAONWIQ","S":2022,"En":"ON Windsor Qualifier","Ev":"St. Clair College","Ea":"2000 Talbot Rd","Ec":"Windsor","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"NLNLM1","S":2022,"En":"NL League Meet The Hague","Ev":"Maerlant-lyceum","Ea":"Johannes Bildersstraat 11","Ec":"The Hague","Es":"ZH","Ect":"Netherlands","Dn":"Netherlands","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/ftcnetherlands","eventType":1000},{"Tc":"USALHUS1","S":2022,"En":"AL Scrimmage #1","Ev":"UAH Conference Training Center","Ea":"1410 Ben Graves Dr NW","Ec":"Huntsville","Es":"AL","Ect":"USA","Dn":"Alabama","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"n/a","eventType":0},{"Tc":"USAZGLQ","S":2022,"En":"AZ Cactus - Anthem Qualifier","Ev":"Ridgeline Academy 7-12 Campus","Ea":"39808 N Gavilan Peak Pkwy","Ec":"Anthem","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1004},{"Tc":"USCALAEM1","S":2022,"En":"CA-SoCal League E - Meet 1","Ev":"The Webb Schools","Ea":"1175 W Baseline Road","Ec":"Claremont","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAA1M1","S":2022,"En":"CA-SoCal League A1 - Meet 1","Ev":"Marlborough High School","Ea":"250 S Rossmore Ave","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALABM1","S":2022,"En":"CA-SoCal League B - Meet 1","Ev":"Dominguez High School,","Ea":"15301 San Jose Avenue","Ec":"Compton","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAC1M1","S":2022,"En":"CA-SoCal League C1 - Meet 1","Ev":"La Ca\u00F1ada High School","Ea":"4463 Oak Grove Drive","Ec":"La Canada","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSUQ","S":2022,"En":"CA-NorCal Google Qualifying Tournament","Ev":"Google Building MP3","Ea":"1170 Bordeaux Drive Building 3","Ec":"Sunnyvale","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCALAF1M2","S":2022,"En":"CA-SoCal League F1 - Meet 1","Ev":"Heritage High School","Ea":"26001 Briggs Road","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAF2M1","S":2022,"En":"CA-SoCal League F2 - Meet 1","Ev":"Heritage High School","Ea":"26001 Briggs Road","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAA2M1","S":2022,"En":"CA-SoCal League A2 - Meet 1","Ev":"YULA Boys School","Ea":"9760 Pico Blvd.","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSAQ","S":2022,"En":"CA-NorCal Saratoga Qualifying Tournament","Ev":"Saratoga High School","Ea":"20300 Herriman Avenue","Ec":"Saratoga","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCOENS","S":2022,"En":"CO Colorado Early Colleges","Ev":"Colorado Early Colleges","Ea":"321 Inverness Drive South","Ec":"Englewood","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLSPM2","S":2022,"En":"FL Space Coast Continuous Charge","Ev":"Deltona Middle School","Ea":"250 Enterprise Road","Ec":"Deltona","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLOCM3","S":2022,"En":"FL ONECLAY League Meet #3","Ev":"Lake Asbury Junior High: Cafeteria","Ea":"2851 Sandridge Road","Ec":"Green Cove Springs","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGANORTM4","S":2022,"En":"GA N Georgia Meet 4","Ev":"Lakeview Academy","Ea":"796 Lakeview Drive","Ec":"Gainesville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAETOWM5","S":2022,"En":"GA Etowah Meet 5","Ev":"Cartersville High School","Ea":"320 E Church St.","Ec":"Cartersville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAALBM4","S":2022,"En":"GA Albany Meet 4","Ev":"4C Academy","Ea":"1615 Newton Rd.","Ec":"Albany","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGANORTM3","S":2022,"En":"GA N Georgia Meet 3","Ev":"Lakeview Academy","Ea":"796 Lakeview Drive","Ec":"Gainesville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAETOWM4","S":2022,"En":"GA Etowah Meet 4","Ev":"Cartersville High School","Ea":"320 E Church St.","Ec":"Cartersville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAWIM3","S":2022,"En":"IA Wind_Meet_2022-12-03","Ev":"Southeast Valley High School","Ea":"1005 Riddle St.","Ec":"Gowrie","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIANUM4","S":2022,"En":"IA Nuclear_Meet_2022-12-03_Dike","Ev":"Dike-New Hartford High School","Ea":"330 Main Street","Ec":"Dike","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAMAM7","S":2022,"En":"IA Magnetic_Meet_2022-12-03","Ev":"Trinity Christian School","Ea":"1811 Hayes Ave","Ec":"Hull","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM2","S":2022,"En":"IA Hydro_Meet_2022-12-03","Ev":"Highland High School","Ea":"1715 Vine Ave","Ec":"Riverside","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIASOM3","S":2022,"En":"IA Solar_Meet_2022-12-03","Ev":"Lakewood Elementary","Ea":"9210 Happy Hollow Dr.","Ec":"Norwalk","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/6dkoCxDBUY8","eventType":1000},{"Tc":"USIACHM1","S":2022,"En":"IA Chemical_Meet_2022-12-03","Ev":"Southwest Valley Middle School","Ea":"406 E 3rd","Ec":"Villisca","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAGEM9","S":2022,"En":"IA Geothermal_Meet_2022-12-03","Ev":"Norway Intermediate School","Ea":"100 School Dr.","Ec":"Norway","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIANUM6","S":2022,"En":"IA Nuclear_Meet_2022-12-03_Arlington","Ev":"Starmont High School","Ea":"3202 40th St","Ec":"Arlington","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIDPFS3","S":2022,"En":"ID North Idaho Scrimmage #3","Ev":"4-H University of Idaho Research Park","Ea":"721 S. Lochsa Street","Ec":"Post Falls","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USILCMM2a","S":2022,"En":"IL Chicago Meet 2A","Ev":"Solorio HS","Ea":"5400 S St Louis Ave.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINISM1","S":2022,"En":"IN FIN Indy South League Meet 1","Ev":"Greenwood Middle School","Ea":"1584 Averitt Rd","Ec":"Greenwood","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINNCM2","S":2022,"En":"IN FIN North Central League Meet 2","Ev":"Career Academy","Ea":"3801 Crescent Cir","Ec":"South Bend","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINNWM1","S":2022,"En":"IN West Central League Meet #1","Ev":"North Montgomery High School","Ea":"5945 US-231","Ec":"Crawfordsville","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINNCM1","S":2022,"En":"IN FIN North Central League Meet 1","Ev":"Olive Elementary School","Ea":"300 W Ben St","Ec":"New Carlisle","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-11-29T00:00:00","Ed":"2022-11-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINBES","S":2022,"En":"IN FIN South League Scrimmage","Ev":"Bedford Boys \u0026 Girls Club","Ea":"2009 19th St","Ec":"Bedford","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-02T00:00:00","Ed":"2022-12-02T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USMIGWQ","S":2022,"En":"MI Grosse Pte. Woods FTC Qualifier","Ev":"University Liggett School","Ea":"1180 Cook Road","Ec":"Grosse Pointe Woods","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-03T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMIPEQ","S":2022,"En":"MI Pellston FTC Qualifier","Ev":"Pellston Middle High School","Ea":"172 N. Park Street","Ec":"Pellston","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-02T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMITRQ","S":2022,"En":"MI Troy FTC Qualifier","Ev":"Athens High School","Ea":"4333 John R Road","Ec":"Troy","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-02T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMISCLT","S":2022,"En":"MI South Central League Tournament","Ev":"Mason High School","Ea":"1001 S Barnes Street","Ec":"Mason","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-02T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMIDEQ","S":2022,"En":"MI Detroit FTC Qualifier","Ev":"University of Detroit Mercy","Ea":"4001 W McNichols Rd.","Ec":"Detroit","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-02T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMISELT","S":2022,"En":"MI South East League Tournament","Ev":"Riverside Middle School","Ea":"25900 W. Warren Road","Ec":"Dearborn Heights","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-02T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMNVM2","S":2022,"En":"MN FTC Vermillion League Meet 2","Ev":"Becker High School","Ea":"12000 Hancock Street","Ec":"Becker","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNMGQ1","S":2022,"En":"MN FTC Maple Grove Sat. Dec. 3","Ev":"Maple Grove High School","Ea":"9800 Fernbrook Ln N","Ec":"Maple Grove","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMNMGQ2","S":2022,"En":"MN FTC Maple Grove Sun. Dec. 4","Ev":"Maple Grove High School","Ea":"9800 Fernbrook Ln N","Ec":"Maple Grove","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSSTLMM2","S":2022,"En":"MOKS-MO Franklin Co Baptist PM","Ev":"Franklin County Baptist Association Building","Ea":"796 Butterfield Dr","Ec":"Union","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM3","S":2022,"En":"MOKS-MO Orchard Farm","Ev":"Orchard Farm High School","Ea":"2175 Hwy V","Ec":"St Charles","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-02T00:00:00","Ed":"2022-12-02T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCEM2","S":2022,"En":"MOKS-MO Pleasant Lea AM","Ev":"Pleasant Lea Middle School","Ea":"630 SW Persels Rd Lee\u0027s Summit","Ec":"Lee\u0027s Summit","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLSM2","S":2022,"En":"MOKS-MO Webster Groves 1","Ev":"Webster Groves High School","Ea":"100 Selma Ave","Ec":"Webster Groves","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSWMIM3","S":2022,"En":"MOKS-MO Kickapoo 1","Ev":"Kickapoo High School","Ea":"3710 S Jefferson Ave","Ec":"Kickapoo","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLMM3","S":2022,"En":"MOKS-MO Franklin Co Baptist AM","Ev":"Franklin County Baptist Association Building","Ea":"796 Butterfield Dr","Ec":"Union","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSEM2","S":2022,"En":"MOKS-MO Poplar Bluff","Ev":"Poplar Bluff high School","Ea":"3209 Oak Grove Rd","Ec":"Poplar Bluff","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCWM2","S":2022,"En":"MOKS-MO Pleasant Lea PM","Ev":"Pleasant Lea Middle School","Ea":"630 SW Persels Rd Lee\u0027s Summit","Ec":"Lee\u0027s Summit","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMSFLQ1","S":2022,"En":"MS Flowood Qualifier","Ev":"Hartfield Academy","Ea":"1240 Luckney Rd","Ec":"Flowood","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMTBUQ","S":2022,"En":"MT Butte Qualifier","Ev":"Montana Tech Hper","Ea":"HPER W Park St","Ec":"Butte","Es":"MT","Ect":"USA","Dn":"Montana","Sd":"2022-12-02T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNJSOM1","S":2022,"En":"NJ 1204-P2  Southern League meet (Sunday)","Ev":"Williamstown Middle School","Ea":"561 Clayton Rd","Ec":"Williamstown","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJNEM1","S":2022,"En":"NJ 1203-P2 Northeast Edge League meet (Saturday)","Ev":"Essex County West Caldwell Tech","Ea":"620 Passaic Ave","Ec":"West Caldwell","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNMANQ","S":2022,"En":"NM Alamogordo FTC Qualifier","Ev":"Alamogordo High School","Ea":"103 Cuba Ave","Ec":"Alamogordo, NM","Es":"NM","Ect":"USA","Dn":"New Mexico","Sd":"2022-12-02T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYNYBRQ","S":2022,"En":"NY-NYC Qualifier 4","Ev":"John Dewey High School","Ea":"50 Avenue X","Ec":"Brooklyn","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYNYBRQ3","S":2022,"En":"NY-NYC Qualifier 3","Ev":"John Dewey High School","Ea":"50 Avenue X","Ec":"Brooklyn","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHCOHLM3","S":2022,"En":"OH Central Ohio League Meet 3","Ev":"Marburn Academy","Ea":"9555 Jamestown Rd","Ec":"New Albany","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOKOKLAM9","S":2022,"En":"OK Muskogee December - morning","Ev":"Muskogee High School","Ea":"3200 E Shawnee Rd","Ec":"Muskogee","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOKOKLAM8","S":2022,"En":"OK Muskogee December - afternoon","Ev":"Muskogee High School","Ea":"3200 E Shawnee Rd","Ec":"Muskogee","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USPAGIS","S":2022,"En":"Green and Red Scrimmage","Ev":"Eden Hall Upper Elementary","Ea":"3900 Bakerstown Road","Ec":"Gibsonia","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USSCNES","S":2022,"En":"SC Midlands/Upstate Scrimmage 1","Ev":"Newberry High School","Ea":"3113 Main St","Ec":"Newberry","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USSCLAS","S":2022,"En":"SC PeeDee Scrimmage 1","Ev":"Latta High School","Ea":"618 N Richardson St","Ec":"Latta","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNONLM3","S":2022,"En":"TX-North N-League Meet 3","Ev":"McKinney Christian Academy","Ea":"3601 Bois D Arc Rd, McKinney, TX 75071","Ec":"McKinney, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCESTM2","S":2022,"En":"TX-Central SSTallions Meet 2","Ev":"SST (San Antonio)","Ea":"4410 David Edwards Dr","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNODLM2","S":2022,"En":"TX-North D-League Meet 2","Ev":"Dealey Montessori Academy, DISD","Ea":"6502 Royal Ln, Dallas, TX 75230","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGCM2","S":2022,"En":"TX-Central Sylvia Earle Meet 3","Ev":"Gregory-Portland High School","Ea":"4601 Wildcat Dr","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGCM3","S":2022,"En":"TX-Central Daphne Koller Meet 3","Ev":"Gregory-Portland High School","Ea":"4601 Wildcat Dr","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCENSAM4","S":2022,"En":"TX-Central Hill Country Field Meet 2","Ev":"Lutheran High School","Ea":"18104 Babcock Road","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPLAM2","S":2022,"En":"TX-W\u0026P Lubbock-A League Meet #2","Ev":"Lubbock High School","Ea":"2004 19th St","Ec":"Lubbock","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPLBM2","S":2022,"En":"TX-W\u0026P Lubbock-B League Meet #2","Ev":"Lubbock-Cooper Middle School","Ea":"16310 TX-493 Loop","Ec":"Lubbock","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPEPM2","S":2022,"En":"TX-W\u0026P El Paso League Meet #2","Ev":"Montwood High School","Ea":"12000 Montwood Dr","Ec":"El Paso","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGMM2","S":2022,"En":"TX-Central GEMS Meet 2","Ev":"Westwood HS","Ea":"12400 Mellow Meadow Dr","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEAUS2","S":2022,"En":"TX-Central Vandegrift HS Scrimmage","Ev":"Vandegrift HS","Ea":"9500 McNeil Drive","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-11-30T00:00:00","Ed":"2022-11-30T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNOCLM3","S":2022,"En":"TX-North C-League Meet 3","Ev":"Conrad High School, DISD","Ea":"7504 Fair Oaks Ave, Dallas, TX 75231","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOSLM2","S":2022,"En":"TX-Houston South League Meet 2","Ev":"Palacios High School","Ea":"100 Shark Dr","Ec":"Palacios","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2022-12-03T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCENSAM3","S":2022,"En":"TX-Central North San Field Meet 2","Ev":"Lutheran High School","Ea":"18104 Babcock Road","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCHSMEQ2","S":2022,"En":"CHS-VA Mechanicsville Qualifier 2","Ev":"Atlee High School","Ea":"9414 Atlee Station Rd","Ec":"Mechanicsville","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSCHQ","S":2022,"En":"CHS-VA Christiansburg Qualifier","Ev":"Christiansburg Middle School","Ea":"1205 Buffalo Dr","Ec":"Christiansburg","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSMEQ1","S":2022,"En":"CHS-VA Mechanicsville Qualifier 1","Ev":"Atlee High School","Ea":"9414 Atlee Station Rd","Ec":"Mechanicsville","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USVTHIS","S":2022,"En":"VT FTC Scrimmage at CVU","Ev":"Champlain Valley Union High School","Ea":"369 CVU Rd.","Ec":"Hinesburg","Es":"VT","Ect":"USA","Dn":"Vermont","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USWASAM2","S":2022,"En":"WA Salk League Meet 2","Ev":"Charles Wright Academy","Ea":"7723 Chambers Creek Rd W","Ec":"University Place","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWABRM2","S":2022,"En":"WA Brattain League Meet 2","Ev":"The Overlake School","Ea":"20301 NE 108th St","Ec":"Redmond","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWAHOM2","S":2022,"En":"WA Hopper League Meet 2","Ev":"Ridgeline High School","Ea":"20150 E Country Vista Dr","Ec":"Liberty Lake","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWABAM2","S":2022,"En":"WA Bardeen League Meet 2","Ev":"Cedarcrest High School","Ea":"29000 NE 150th St","Ec":"Duvall","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWALOM2","S":2022,"En":"WA Lovelace League Meet 2","Ev":"Olympia High School","Ea":"1302 North Street SE","Ec":"Olympia","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWASHM2","S":2022,"En":"WA Shockley League Meet 2","Ev":"Lower Columbia College","Ea":"1600 Maple St","Ec":"Longview","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWAAGM2","S":2022,"En":"WA Agnesi League Meet 2","Ev":"Chief Joseph Middle School","Ea":"504 Wilson Street","Ec":"Richland","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-03T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWASPM2","S":2022,"En":"WA Spencer League Meet 2","Ev":"Mt. Si High School","Ea":"8651 Meadowbrook Way SE","Ec":"Snoqualmie","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWATUM2","S":2022,"En":"WA Turing League Meet 2","Ev":"Bellevue International School","Ea":"445 128th Ave SE","Ec":"Bellevue","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-04T00:00:00","Ed":"2022-12-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWISHQ","S":2022,"En":"WI Red Raider FIRST Tech Challenge Qualifier","Ev":"Urban Middle School","Ea":"1226 North Avenue","Ec":"Sheboygan","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2022-12-02T00:00:00","Ed":"2022-12-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 12/05/2022","Ws":"2022-12-05T00:00:00","We":"2022-12-11T23:59:59","Wn":13,"Ec":103,"E":[{"Tc":"AUCMP","S":2022,"En":"Australian National Championship","Ev":"Pymble Ladies College","Ea":"20-64 Avon Rd","Ec":"Pymble","Es":"NSW","Ect":"Australia","Dn":"Australia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"CAABABNAM3","S":2022,"En":"AB Northern Alberta Round #3","Ev":"Lacombe Composite High School","Ea":"5628 56 Ave","Ec":"Lacombe","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"CABCKIS","S":2022,"En":"BC Northern Scrimmage 5","Ev":"Mt. Elizabeth Secondary","Ea":"1491 Kingfisher Ave,","Ec":"Kitimat","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"CABCVAS4","S":2022,"En":"BC Remote Scrimmage 4","Ev":"Remote Event","Ea":"366 E 3rd Street,","Ec":"Vancouver","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2022-12-01T00:00:00","Ed":"2022-12-07T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"CAONSCQ","S":2022,"En":"ON North Scarborough Qualifier","Ev":"Dr. Norman Bethune Collegiate Institute","Ea":"200 Fundy Bay Blvd","Ec":"Scarborough","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"CAONBOQ","S":2022,"En":"ON Bolton Qualifer","Ev":"Humberview Secondary School","Ea":"135 Kingsview Dr. Bolton","Ec":"Bolton","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"NLNLM2","S":2022,"En":"NL League Meet Hasselt","Ev":"VOKA Kamer van Koophandel Limburg","Ea":"Gouverneur Roppesingel 51","Ec":"Hasselt","Es":"LI","Ect":"Netherlands","Dn":"Netherlands","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/ftcnetherlands","eventType":1000},{"Tc":"NZCMP","S":2022,"En":"New Zealand National Championship","Ev":"Toitoi Events Centre","Ea":"109 Hastings Street South","Ec":"Hasting\u0027s","Es":"HKB","Ect":"New Zealand","Dn":"New Zealand","Sd":"2022-12-09T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"THCMP","S":2022,"En":"Thailand FTC Championship Event","Ev":"PRC","Ea":"Kaewnawarat Rd.","Ec":"Muang","Es":"50","Ect":"Thailand","Dn":"Thailand","Sd":"2022-12-07T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USAKANQ","S":2022,"En":"AK Southcentral Alaska Qualifier","Ev":"West High School","Ea":"1700 Hillcrest Drive","Ec":"Anchorage","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-12-09T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USAKJUQ","S":2022,"En":"AK Southeast Alaska Qualifier","Ev":"Thunder Mountain High School","Ea":"3101 Dimond Park Loop Rd","Ec":"Juneau","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-12-09T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USARMHS","S":2022,"En":"AR Mountain Home Scrimmage","Ev":"Mountain Home Junior High School","Ea":"2301 Rodeo Dr","Ec":"Mountain Home","Es":"AR","Ect":"USA","Dn":"Arkansas","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALAVM2","S":2022,"En":"CA-SoCal League V - Meet 2","Ev":"Ojai Valley School \u2013 Littlefield Student Commons","Ea":"10820 Revees Road","Ec":"Ojai","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOPNM2","S":2022,"En":"CA-NorCal Peninsula League Meet 2","Ev":"Jefferson High School","Ea":"6996 Mission Street","Ec":"Daly City","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAO1M1","S":2022,"En":"CA-SoCal League O1 - Meet 1","Ev":"Arena Soccer Park of Orange","Ea":"2190 N Canal St","Ec":"Orange","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOPIQ","S":2022,"En":"CA-NorCal Piedmont Qualifying Tournament","Ev":"Piedmont Middle School","Ea":"740 Magnolia Ave","Ec":"Piedmont","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCASDSDDEM2","S":2022,"En":"CA- San Diego Descartes Meet #2, Pacific Ridge","Ev":"Pacific Ridge School Athletic Center","Ea":"6269 El Fuerte St","Ec":"Carlsbad","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALADM2","S":2022,"En":"CA-SoCal League D - Meet 2","Ev":"Notre Dame High School","Ea":"13645 Riverside Drive","Ec":"Sherman Oaks","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANODUQ","S":2022,"En":"CA-NorCal Dublin Qualifying Tournament","Ev":"The Quarry Lane School","Ea":"6363 Tassajara Road","Ec":"Dublin","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-12-11T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCASDSDEUM2","S":2022,"En":"CA- San Diego Euclid Meet #2, Pacific Ridge","Ev":"Pacific Ridge School Athletic Center","Ea":"6269 El Fuerte St","Ec":"Carlsbad","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAWM1","S":2022,"En":"CA-SoCal League W - Meet 1","Ev":"Crossroads Elementary School","Ea":"1715 Olympic Blvd","Ec":"Santa Monica","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDTUM2","S":2022,"En":"CA- San Diego Turing Meet #2, Pacific Ridge","Ev":"Pacific Ridge School Athletic Center","Ea":"6269 El Fuerte St","Ec":"Carlsbad","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2022-12-11T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDGAM2","S":2022,"En":"CA- San Diego Gauss Meet #2, Pacific Ridge","Ev":"Pacific Ridge School Athletic Center","Ea":"6269 El Fuerte St","Ec":"Carlsbad","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2022-12-11T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCOGRS","S":2022,"En":"CO EGMS - Scrimmage","Ev":"East Grand Middle School","Ea":"251 West Diamond","Ec":"Granby","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLROM1","S":2022,"En":"FL ROBOT League Seven Rivers Shenanigans","Ev":"Seven Rivers Christian School Gym","Ea":"4221 West Gulf To Lake Highway","Ec":"Lecanto","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLNEM3","S":2022,"En":"FL North East League Meet #3","Ev":"Bolles Bartram Campus","Ea":"2264 Bartram Road","Ec":"Jacksonville","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLSFM2","S":2022,"En":"FL South Florida League Meet #2","Ev":"South Fork High School","Ea":"10000 SW Bulldog Way","Ec":"Stuart","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLACM3","S":2022,"En":"FL AeroCoast League Meet #3","Ev":"Shoal River Middle School","Ea":"3200 E Redstone Ave","Ec":"Crestview","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLGCM2","S":2022,"En":"FL Gulf Coast League Meet #2","Ev":"Meadowlawn Middle School","Ea":"6050 16th Street N","Ec":"St. Petersburg","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATLLT","S":2022,"En":"GA Atlanta League Tournament","Ev":"Marist School","Ea":"3790 ASHFORD DUNWOODY ROAD NE","Ec":"Atlanta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USGAMACM4","S":2022,"En":"GA Macon Meet 4","Ev":"First Presbyterian Day School","Ea":"5671 Calvin Dr","Ec":"Macon","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAMARIM3","S":2022,"En":"GA Marietta Meet 3","Ev":"Wheeler High School","Ea":"375 Holt Rd.","Ec":"Marietta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAMACM5","S":2022,"En":"GA Macon Meet 5","Ev":"First Presbyterian Day School","Ea":"5671 Calvin Dr","Ec":"Macon","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAJACKM4","S":2022,"En":"GA Jackson Meet 4","Ev":"East Jackson High School","Ea":"1435 Hoods Mill Road","Ec":"Commerce","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAJACKM3","S":2022,"En":"GA Jackson Meet 3","Ev":"East Jackson High School","Ea":"1435 Hoods Mill Road","Ec":"Commerce","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATHM3","S":2022,"En":"GA Caterpillar Meet 3","Ev":"Oconee County High School","Ea":"2721 Hog Mountain Road","Ec":"Watkinsville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-06T00:00:00","Ed":"2022-12-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USHI01LT","S":2022,"En":"HI Le Jardin Academy","Ev":"Le Jardin Academy","Ea":"917 Kalanianaole Hwy","Ec":"Kailua","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USIAMAM1","S":2022,"En":"IA Magnetic_Meet_2022-12-10","Ev":"Central Lyon High School","Ea":"1010 South Greene St.","Ec":"Rock Rapids","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAGEM8","S":2022,"En":"IA Geothermal_Meet_2022-12-10","Ev":"Trinity Lutheran School","Ea":"1361 7th Ave SW","Ec":"Cedar Rapids","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM1","S":2022,"En":"IA Hydro_Meet_2022-12-10","Ev":"Washington County 4H Hall","Ea":"2223 250th St.","Ec":"Washington","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAWIM1","S":2022,"En":"IA Wind_Meet_2022-12-10","Ev":"Grundy Center High School","Ea":"1006 M Ave.","Ec":"Grundy Center","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIASOM1","S":2022,"En":"IA Solar_Meet_2022-12-10","Ev":"Lakewood Elementary","Ea":"9210 Happy Hollow Dr.","Ec":"Norwalk","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/sZpEVdfm32w","eventType":1000},{"Tc":"USIANUM1","S":2022,"En":"IA Nuclear_Meet_2022-12-10","Ev":"Peet Junior High","Ea":"525 E. Seerley Blvd","Ec":"Cedar Falls","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCM2","S":2022,"En":"IL Central Meet 2","Ev":"Mt Zion Intermediate School","Ea":"310 S Henderson St","Ec":"Mt Zion","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILFNM2","S":2022,"En":"IL Fox Valley North Meet 2","Ev":"Crystal Lake South","Ea":"1200 South McHenry Ave","Ec":"Crystal Lake","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILFSM2","S":2022,"En":"IL Fox Valley South Meet 2","Ev":"Wheaton Academy","Ea":"900 Prince Crossing Road","Ec":"Wheaton","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCMM2B","S":2022,"En":"IL Chicago Meet 2B","Ev":"Lincoln Park HS","Ea":"2001 N Orchard St.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILSM2","S":2022,"En":"IL Southern Meet 2","Ev":"Centralia High School","Ea":"2100 East Calumet","Ec":"Centralia","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILNEM2","S":2022,"En":"IL Northeast Lake Meet 2","Ev":"Lakes Community High School","Ea":"1600 Eagle Way","Ec":"Lake Villa","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILNSM2","S":2022,"En":"IL North Shore Meet 2","Ev":"Highland Park High School","Ea":"433 Vine Ave","Ec":"Highland Park","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILPM2","S":2022,"En":"IL Peoria Meet 2","Ev":"Peoria Northwoods Mall","Ea":"2200 W War Memorial Dr","Ec":"Peoria","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINISM2","S":2022,"En":"IN FIN Indy South League Meet 2","Ev":"UIndy Schwitzer Student Center","Ea":"1400 Campus Dr","Ec":"Indianapolis","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCEM3","S":2022,"En":"MOKS-KS Heritage Christian KC East PM","Ev":"Heritage Christian Academy","Ea":"16000 S Black Bob Rd","Ec":"Olathe","Es":"KS","Ect":"USA","Dn":"Missouri","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCWM4","S":2022,"En":"MOKS-KS Heritage Christian KC West AM","Ev":"Heritage Christian Academy","Ea":"16000 S Black Bob Rd","Ec":"Olathe","Es":"KS","Ect":"USA","Dn":"Missouri","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMIBRQ","S":2022,"En":"MI Big Rapids FTC Qualifier","Ev":"Big Rapids High School","Ea":"21175 15 Mile Road","Ec":"Big Rapids","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-09T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMIFLQ","S":2022,"En":"MI Kettering FTC Qualifier","Ev":"Kettering University","Ea":"1700 University Avenue","Ec":"Flint","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-09T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMICOQ","S":2022,"En":"MI Coloma FTC Qualifier","Ev":"Coloma High School","Ea":"300 W St Joseph Street","Ec":"Coloma","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-09T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMICMP2","S":2022,"En":"Michigan FTC State Championship-SE","Ev":"Macomb Community College","Ea":"14500 E. 12 Mile Road","Ec":"Warren","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-08T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMNVM3","S":2022,"En":"MN FTC Vermillion League Meet 3","Ev":"Discovery Middle School","Ea":"510 McKay Avenue N","Ec":"Alexandria","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNCM3","S":2022,"En":"MN FTC Cass Lake League Meet 3","Ev":"St. Paul Academy","Ea":"1712 Randolph Ave","Ec":"St. Paul","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-08T00:00:00","Ed":"2022-12-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNNBQ2","S":2022,"En":"MN FTC New Brighton Sun. Dec. 11","Ev":"Irondale High School","Ea":"2425 Long Lake Rd","Ec":"New Brighton","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-11T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMNNBQ1","S":2022,"En":"MN FTC New Brighton Sat. Dec. 10","Ev":"Irondale High School","Ea":"2425 Long Lake Rd","Ec":"New Brighton","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSSTLNM2","S":2022,"En":"MOKS-MO Incarnate Word Academy PM","Ev":"Incarnate Word Academy","Ea":"2788 Normandy Ave","Ec":"St Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSWMIM1","S":2022,"En":"MOKS-MO Rolla Technical Institute 1","Ev":"Rolla Technical Institute","Ea":"1304 E 10th St","Ec":"Rolla","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM1","S":2022,"En":"MOKS-MO Incarnate Word Academy AM","Ev":"Incarnate Word Academy","Ea":"2788 Normandy Ave","Ec":"St Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNCBUS","S":2022,"En":"NC FTC Official Scrimmage","Ev":"TBD","Ea":"TBD","Ec":"Burlington","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2022-12-11T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":0},{"Tc":"USNDALS","S":2022,"En":"ND Dakota Alexander Comets Scrimmage","Ev":"Alexander Public Schools","Ea":"601 Delaney St.","Ec":"Alexander","Es":"ND","Ect":"USA","Dn":"North Dakota","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USNJNOM4","S":2022,"En":"NJ 1211-P2  Northern League Meet (Sunday)","Ev":"River Dell High School","Ea":"55 Pyle St.","Ec":"Oradell","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-12-11T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJUCM3","S":2022,"En":"NJ 1210-P2  Upper Central League Meet (Saturday)","Ev":"Brooklawn Middle School","Ea":"250 Beachwood Road","Ec":"Parsippany","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNVNOM2N","S":2022,"En":"NV Northern League Meet # 2N","Ev":"Excel Christian School","Ea":"850 Baring Blvd","Ec":"Sparks","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2022-12-08T00:00:00","Ed":"2022-12-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNVSOM2S","S":2022,"En":"NV Southern League Meet # 2S","Ev":"Word of Life Christian Academy","Ea":"3510 N Buffalo Dr","Ec":"Las Vegas","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2022-12-08T00:00:00","Ed":"2022-12-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USOKOKLAM1","S":2022,"En":"OK TSAS December","Ev":"Tulsa School of Arts and Sciences","Ea":"1202 W Easton St","Ec":"Tulsa","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORCBM2","S":2022,"En":"OR Columbia Basin League Meet 2","Ev":"Pendleton High School","Ea":"1800 NW Carden Ave","Ec":"Pendleton","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-12-07T00:00:00","Ed":"2022-12-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORSOM2","S":2022,"En":"OR SOAR League Meet 2","Ev":"Roseburg High School","Ea":"400 Harvard Ave","Ec":"Roseburg","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORSFM2","S":2022,"En":"OR Silicon Forest League Meet 2","Ev":"Hillsboro High School","Ea":"3285 SE Rood Bridge Rd","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORRCM2","S":2022,"En":"OR Rose City League Meet 2","Ev":"Franklin HS","Ea":"5405 SE Woodward St","Ec":"Portland","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORNCM2","S":2022,"En":"OR North Coast League Meet 3","Ev":"Neah-Kah-Nie High School","Ea":"24705 Hwy 101 N","Ec":"Rockaway Beach","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USSCMAS","S":2022,"En":"SC Upstate/Midlands Scrimmage 2","Ev":"Mauldin High School","Ea":"701 E Butler Rd","Ec":"Mauldin","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USSCNLCS2","S":2022,"En":"SC Lowcountry Scrimmage 2","Ev":"Ft. Dorchester High School","Ea":"8500 Patriot Blvd","Ec":"N. Charleston","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXHONLM1","S":2022,"En":"TX-Houston North League Meet 1","Ev":"Brabham Middle School","Ea":"10000 Fm 830 Rd.","Ec":"Willis","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHONEM1","S":2022,"En":"TX-Houston Northeast League Meet 1","Ev":"Livingston High School","Ea":"400 FM 350 South","Ec":"Livingston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOBLM3","S":2022,"En":"TX-North B-League Meet 3","Ev":"W.G. Thomas Coliseum, Birdville ISD","Ea":"6108 Broadway Avenue, Haltom City, TX 76117","Ec":"Haltom City, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOFLM2","S":2022,"En":"TX-North F-League Meet 2","Ev":"QD Academy","Ea":"4101 Legacy Dr, Plano, TX 75024","Ec":"Plano, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOXMLM2B","S":2022,"En":"TX-North X-League Metro Meet 2B","Ev":"Roboplex at Marcus HS, LISD","Ea":"5710 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPMDM2","S":2022,"En":"TX-W\u0026P Midland League Meet #2","Ev":"Andrews High School","Ea":"1400 NW Ave K,","Ec":"Andrews","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOTLM2","S":2022,"En":"TX-North T-League Meet 2","Ev":"New Tech High @ Coppell","Ea":"113 Samuel Blvd, Coppell, TX 75019","Ec":"Coppell, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOHOS1","S":2022,"En":"TX-Houston East League Scrimmage","Ev":"Mickey Leland College Prep.","Ea":"1700 Gregg St","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNOULM2","S":2022,"En":"TX-North U-League Meet 2","Ev":"UME Preparatory Academy","Ea":"3839 TX-408 Spur, Dallas, TX 75236","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEOH90M2","S":2022,"En":"TX- Central Old Highway 90 Meet 2","Ev":"Brentwood MS","Ea":"1626 W. Thompson Pl","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOCNLT1","S":2022,"En":"TX-North C\u0026N Tournament","Ev":"Townview SEM, DISD","Ea":"1201 E. Eighth St., Dallas, TX 75203","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXCEXSTM1","S":2022,"En":"TX-Central X-STREAM B Meet 2","Ev":"Kipp Collegiate HS","Ea":"8004 Cameron Road","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEKWM2","S":2022,"En":"TX-Central Kwolek Meet 2","Ev":"Harmony School of Innovation","Ea":"8124 Glen Mont Dr","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOCUM3","S":2022,"En":"TX-South Curie Meet 3","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPAMM2","S":2022,"En":"TX-W\u0026P Amarillo League Meet #2","Ev":"AmTech Career Academy","Ea":"3601 Plains Blvd","Ec":"Amarillo","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOHAM3","S":2022,"En":"TX-South Hawking Meet 3","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEWAM2","S":2022,"En":"TX-Central Waco League Meet 2","Ev":"TBD","Ea":"TBD","Ec":"Waco","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-07T00:00:00","Ed":"2022-12-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOXMLM2A","S":2022,"En":"TX-North X-League Metro Meet 2A","Ev":"Roboplex at Marcus HS, LISD","Ea":"5709 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEXSTM2","S":2022,"En":"TX-Central X-STREAM A Meet 2","Ev":"Kipp Collegiate HS","Ea":"8004 Cameron Road","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USUTPRQ","S":2022,"En":"UT Freedom Prep Academy Qualifier","Ev":"Freedom Prep Academy","Ea":"1761 W 820 N","Ec":"Provo","Es":"UT","Ect":"USA","Dn":"Utah","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSORQ","S":2022,"En":"CHS-VA Orange Qualifier","Ev":"Hornet Sports Center at Orange County High School","Ea":"200 Hornet Drive","Ec":"Orange","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSGAQ","S":2022,"En":"CHS-VA Glen Allen Qualifier","Ev":"Deep Run High School","Ea":"4801 Twin Hickory Rd","Ec":"Glen Allen","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2022-12-11T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USWAKNM2","S":2022,"En":"WA Knuth League Meet 2","Ev":"Post Middle School","Ea":"1220 E 5th St","Ec":"Arlington","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWIBRS","S":2022,"En":"WI Hazmat FTC Scrimmage","Ev":"Brookfield Central High School","Ea":"16900 Gebhardt Road","Ec":"Brookfield","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2022-12-10T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 12/12/2022","Ws":"2022-12-12T00:00:00","We":"2022-12-18T23:59:59","Wn":14,"Ec":67,"E":[{"Tc":"CAABABSAM2","S":2022,"En":"AB Southern Alberta Round 2","Ev":"William Aberhart High School","Ea":"3009 Morley Trail NW","Ec":"Calgary","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"KZALS","S":2022,"En":"Kazakhstan FIZMAT Championship","Ev":"Koktem 2 Bostandyk","Ea":"Bukhar zhyrau 36","Ec":"Almaty","Es":"ALA","Ect":"Kazakhstan","Dn":"Kazakhstan","Sd":"2022-12-16T00:00:00","Ed":"2022-12-16T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAKFAQ","S":2022,"En":"AK Fairbanks Qualifier","Ev":"University of Alaska Fairbanks","Ea":"1731 South Chandalar Dr.","Ec":"Fairbanks","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USAKJUS3","S":2022,"En":"AK Remote PowerPlay Scrimmage","Ev":"Juneau Economic Development Council","Ea":"612 W Willoughby Ave","Ec":"Juneau","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2022-12-12T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":False,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAZTUQ","S":2022,"En":"AZ Diamondback - Tucson Qualifier","Ev":"San Miguel High School","Ea":"6601 San Fernando Ave","Ec":"Tucson","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1004},{"Tc":"USCANOSBM2B","S":2022,"En":"CA-NorCal South Bay Metro League Meet 2b","Ev":"The Play Space","Ea":"2215 Old Oakland Road","Ec":"San Jose","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAA2M2","S":2022,"En":"CA-SoCal League A2 - Meet 2","Ev":"YULA Boys School","Ea":"9760 Pico Blvd.","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-18T00:00:00","Ed":"2022-12-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAC2M1","S":2022,"En":"CA-SoCal League C2 - Meet 1","Ev":"Santa Fe Middle School","Ea":"148 W Duarte Rd","Ec":"Monrovia","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSBM2A","S":2022,"En":"CA-NorCal South Bay Metro League Meet 2a","Ev":"The Play Space","Ea":"2215 Old Oakland Road","Ec":"San Jose","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANONEM2","S":2022,"En":"CA-NorCal North East League Meet 2","Ev":"Einstein Middle School","Ea":"9325 Mirandy Drive","Ec":"Sacramento","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAA1M2","S":2022,"En":"CA-SoCal League A1 - Meet 2","Ev":"Marlborough School","Ea":"250 South Rossmore Avenue","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLOLM2","S":2022,"En":"FL Orlando Robotics League Meet #2","Ev":"Lake Highland Preparatory School","Ea":"901 Highland Ave","Ec":"Orlando","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLSPM1","S":2022,"En":"FL Space Coast Wild Voltz","Ev":"T Dewitt Taylor Middle High School","Ea":"100 E Washington Avenue","Ec":"Pierson","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGADOUGM3","S":2022,"En":"GA Douglasville Meet 3","Ev":"Douglas County High School","Ea":"8705 Campbellton Street","Ec":"Douglasville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAWIM5","S":2022,"En":"IA Wind_Meet_2022-12-17","Ev":"Ames High School","Ea":"1801 Ridgewood Ave","Ec":"Ames","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM6","S":2022,"En":"IA Hydro_Meet_2022-12-17_Dubuque","Ev":"Roosevelt Middle School","Ea":"2001 Radford Rd","Ec":"Dubuque","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAGEM11","S":2022,"En":"IA Geothermal_Meet_2022-12-17","Ev":"Belle Plaine Jr/Sr High School","Ea":"610 13th Ave.","Ec":"Belle Plaine","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAWIM2","S":2022,"En":"IA Wind_Meet_2022-12-13","Ev":"Clear Lake High School","Ea":"125 N. 20th St.","Ec":"Clear Lake","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-13T00:00:00","Ed":"2022-12-13T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAMAM2","S":2022,"En":"IA Magnetic_Meet_2022-12-17","Ev":"Hinton High School","Ea":"315 W Grand Street","Ec":"Hinton","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIANUM8","S":2022,"En":"IA Nuclear_Meet_2022-12-16","Ev":"Valley Lutheran School","Ea":"4520 Rownd St.","Ec":"Cedar Falls","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-16T00:00:00","Ed":"2022-12-16T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAGEM5","S":2022,"En":"IA Geothermal_Meet_2022-12-16","Ev":"Linn-Mar High School","Ea":"South Commons","Ec":"Marion","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-16T00:00:00","Ed":"2022-12-16T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIANUM2","S":2022,"En":"IA Nuclear_Meet_2022-12-17","Ev":"Valley Lutheran School","Ea":"4520 Rownd St","Ec":"Cedar Falls","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYM7","S":2022,"En":"IA Hydro_Meet_2022-12-17_IowaCity","Ev":"City High School","Ea":"Lower Commons","Ec":"Iowa City","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIASOM2","S":2022,"En":"IA Solar_Meet_2022-12-17","Ev":"Lakewood Elementary","Ea":"9210 Happy Hollow Dr.","Ec":"Norwalk","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/ym7HUlwd76k","eventType":1000},{"Tc":"USILWM2","S":2022,"En":"IL Western Meet 2","Ev":"Fulton High School","Ea":"1207 12th St","Ec":"Fulton","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILRM2","S":2022,"En":"IL Rockford Meet 2","Ev":"Winnebago High School","Ea":"200 E McNair Rd","Ec":"Winnebago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILSSM2","S":2022,"En":"IL South Suburbs Meet 2","Ev":"Kingswood Academy","Ea":"133 Plainfield Rd","Ec":"Darien","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCMM2c","S":2022,"En":"IL Chicago Meet 2C","Ev":"Lake View HS","Ea":"4015 N Ashland Ave","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINNCM4","S":2022,"En":"IN FIN North Central League Meet 4","Ev":"Career Academy","Ea":"3801 Crescent Cir","Ec":"South Bend","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINNWM2","S":2022,"En":"IN West Central League Meet #2","Ev":"Battle Ground Middle School","Ea":"6100 N 50 W","Ec":"West Lafayette","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINNCM3","S":2022,"En":"IN FIN North Central League Meet 3","Ev":"Olive Elementary School","Ea":"300 W Ben St","Ec":"New Carlisle","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-12T00:00:00","Ed":"2022-12-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINSLM1","S":2022,"En":"IN FIN South League Meet 1","Ev":"Lincoln Elementary School","Ea":"2014 F St","Ec":"Bedford","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2022-12-16T00:00:00","Ed":"2022-12-16T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMASHQ","S":2022,"En":"MA Ryken Robobowl","Ev":"St. John\u0027s High School","Ea":"378 Main Street","Ec":"Shrewsbury","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2022-12-18T00:00:00","Ed":"2022-12-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMICMP","S":2022,"En":"Michigan FTC State Championship-NW","Ev":"Calvin University","Ea":"3195 Knight Way Southeast","Ec":"Grand Rapids","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-15T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMNMM3","S":2022,"En":"MN FTC Mille Lacs League Meet 3","Ev":"MURA Field","Ea":"2131 N. 12th Ave.","Ec":"Minneapolis","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNPM3","S":2022,"En":"MN FTC Pepin League Meet 3","Ev":"MURA Field","Ea":"2131 N. 12th Ave.","Ec":"Minneapolis","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM5","S":2022,"En":"MOKS-MO Warrenton PM","Ev":"Warrenton High School","Ea":"803 Pinckney","Ec":"Warrenton","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCEM1","S":2022,"En":"MOKS-MO Knob Noster AM","Ev":"Knob Noster High School","Ea":"504 S Washington Ave","Ec":"Knob Noster","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLSM1","S":2022,"En":"MOKS-MO Gateway STEM HS","Ev":"Gateway STEM HS","Ea":"5101 McRee Ave","Ec":"St. Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCWM1","S":2022,"En":"MOKS-MO Knob Noster PM","Ev":"Knob Noster High School","Ea":"504 S Washington Ave","Ec":"Knob Noster","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM10","S":2022,"En":"MOKS-MO Orchard Farm 2","Ev":"Orchard Farm High School","Ea":"2175 Hwy V","Ec":"St Charles","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-15T00:00:00","Ed":"2022-12-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSEM1","S":2022,"En":"MOKS-MO Notre Dame","Ev":"Notre Dame Regional High School","Ea":"265 Notre Dame Dr","Ec":"Cape Girardeau","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSWMIM2","S":2022,"En":"MOKS-MO Newburg","Ev":"Newburg School","Ea":"701 Wolf Pride Drive","Ec":"Newburg","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLMM1","S":2022,"En":"MOKS-MO St. Louis Community College Wildwood","Ev":"ST Louis Community College Wildwood","Ea":"2645 Generations Dr","Ec":"Grover","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM4","S":2022,"En":"MOKS-MO Warrenton AM","Ev":"Warrenton High School","Ea":"803 Pinckney","Ec":"Warrenton","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNHWIS","S":2022,"En":"NH Windham Scrimmage #3","Ev":"Windham Center School","Ea":"2 Lowell Road, Windham 03087","Ec":"Windham","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USNJNEM4","S":2022,"En":"NJ 1218-P2  Northeast Edge League Meet (Sunday)","Ev":"Scotch Plains-Fanwood High School","Ea":"667 Westfield Road","Ec":"Scotch Plains","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-12-18T00:00:00","Ed":"2022-12-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJSOM4","S":2022,"En":"NJ 1217-P2  Southern League Meet (Saturday)","Ev":"Clearview Regional High School","Ea":"625 Breakneck Road","Ec":"Mullica Hill","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNYEXPEQ","S":2022,"En":"NY-Excelsior Finger Lakes Qualifier","Ev":"Penfield High School","Ea":"25 High School Dr","Ec":"Penfield","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHKIS","S":2022,"En":"OH Kirtland Scrimmage","Ev":"Kirtland High School","Ea":"9150 Chillicothe Road","Ec":"Kirtland","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USOHCOHLLT","S":2022,"En":"OH Central Ohio League Tournament","Ev":"Watkins Intermediate School","Ea":"2020 Warrior Way SW","Ec":"Pataskala","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USOKOKLAM10","S":2022,"En":"OK Okarche - morning","Ev":"Okarche High School","Ea":"632 W Oklahoma Ave","Ec":"Okarche","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOKOKLAM2","S":2022,"En":"OK Okarche - afternoon","Ev":"Okarche High School","Ea":"632 W Oklahoma Ave","Ec":"Okarche","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USPACOQ1","S":2022,"En":"PA Eastern Qualifier","Ev":"Coatesville Area High School","Ea":"1445 E Lincoln Hwy","Ec":"Coatesville","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USPACOQ2","S":2022,"En":"PA Red and Black Qualifier","Ev":"Coatesville Area High School","Ea":"1445 E Lincoln Hwy","Ec":"Coatesville","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2022-12-18T00:00:00","Ed":"2022-12-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USTNKNS","S":2022,"En":"TN Webb School","Ev":"Webb School Of Knoxville","Ea":"9800 Webb School Ln, Knoxville, TN","Ec":"Knoxville","Es":"TN","Ect":"USA","Dn":"Tennessee","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXSOTEM2","S":2022,"En":"TX-South Tesla Meet 2 (Laredo)","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGCM1","S":2022,"En":"TX-Central Daphne Koller Meet 4","Ev":"Gregory-Portland High School","Ea":"4601 Wildcat Dr","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGCM4","S":2022,"En":"TX-Central Sylvia Earle Meet 4","Ev":"Gregory-Portland High School","Ea":"4601 Wildcat Dr","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOTEM3","S":2022,"En":"TX-South Tesla Meet 3 (Laredo)","Ev":"TBD","Ea":"801 E Fern Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOMLM2","S":2022,"En":"TX-North M-League Meet 2","Ev":"MAS DFW","Ea":"1515 Blake Dr, Richardson, TX 75081","Ec":"Richardson, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USWATELT","S":2022,"En":"WA Tesla Interleague Tournament","Ev":"Beaver Lake Middle School","Ea":"25025 SE 32nd St","Ec":"Issaquah","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-18T00:00:00","Ed":"2022-12-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USWACULT","S":2022,"En":"WA Curie Interleague Tournament","Ev":"Hanford High School","Ea":"450 Hanford St","Ec":"Richland","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USWAPALT1","S":2022,"En":"WA Pasteur Interleague Tournament","Ev":"Henry M. Jackson High School","Ea":"1508 136th St SE","Ec":"Mill Creek","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-18T00:00:00","Ed":"2022-12-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USWAWALT","S":2022,"En":"WA Watt Interleague Tournament","Ev":"Daybreak School","Ea":"1900 NW 20th Ave","Ec":"Battle Ground","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USWAFELT1","S":2022,"En":"WA Feynman Interleague Tournament","Ev":"Henry M. Jackson High School","Ea":"1508 136th St SE","Ec":"Mill Creek","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2022-12-17T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USWIVAQ","S":2022,"En":"WI Lakeshore FIRST Tech Challenge Qualifier","Ev":"Valders High School","Ea":"201 Wilson Street","Ec":"Valders","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2022-12-16T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 12/19/2022","Ws":"2022-12-19T00:00:00","We":"2022-12-25T23:59:59","Wn":15,"Ec":1,"E":[{"Tc":"USLATBQ","S":2022,"En":"LA Qualifier 1","Ev":"Dutchtown High School","Ea":"13165 LA HWY 73","Ec":"Geismar","Es":"LA","Ect":"USA","Dn":"Louisiana","Sd":"2022-12-15T00:00:00","Ed":"2022-12-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 01/02/2023","Ws":"2023-01-02T00:00:00","We":"2023-01-08T23:59:59","Wn":17,"Ec":47,"E":[{"Tc":"CABCSUS","S":2022,"En":"BC L.A. Matheson Scrimmage","Ev":"L.A. Matheson Secondary","Ea":"9484 122 St.","Ec":"Surrey","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"GBLOS","S":2022,"En":"GB South East Scrimmage","Ev":"American School in London","Ea":"1 Waverley Pl,","Ec":"London","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-01-06T00:00:00","Ed":"2023-01-06T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USARSPS2","S":2022,"En":"AR Turnbow Scrimmage","Ev":"Walter Turnbow Elementary School","Ea":"3390 Habberton Rd","Ec":"Springdale","Es":"AR","Ect":"USA","Dn":"Arkansas","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCALAA2M3","S":2022,"En":"CA-SoCal League A2 - Meet 3","Ev":"YULA Boys School","Ea":"9760 Pico Blvd.","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-08T00:00:00","Ed":"2023-01-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSJQ1","S":2022,"En":"CA-NorCal San Jose #1 Qualifying Tournament","Ev":"The Play Space","Ea":"2215 Old Oakland Road","Ec":"San Jose","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-08T00:00:00","Ed":"2023-01-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCALADM3","S":2022,"En":"CA-SoCal League D - Meet 3","Ev":"Notre Dame High School","Ea":"13645 Riverside Drive","Ec":"Sherman Oaks","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAF2M2","S":2022,"En":"CA-SoCal League F2 - Meet 2","Ev":"Heritage High School","Ea":"26001 Briggs Road","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAWM2","S":2022,"En":"CA-SoCal League W - Meet 2","Ev":"Crossroads Elementary School","Ea":"1715 Olympic Blvd","Ec":"Santa Monica","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-08T00:00:00","Ed":"2023-01-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAF1M1","S":2022,"En":"CA-SoCal League F1 - Meet 2","Ev":"Heritage High School","Ea":"26001 Briggs Road","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAC1M2","S":2022,"En":"CA-SoCal League C1 - Meet 2","Ev":"La Ca\u00F1ada High School","Ea":"4463 Oak Grove Drive","Ec":"La Canada","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCODEQ","S":2022,"En":"CO Central Metro Qualifier","Ev":"Regis University","Ea":"3333 Regis Blvd","Ec":"Denver","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USFLFLACM4","S":2022,"En":"FL AeroCoast League Meet #4","Ev":"College of Engineering","Ea":"2525 Pottsdamer Street","Ec":"Tallahassee","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAMARIM4","S":2022,"En":"GA Marietta Meet 4","Ev":"Wheeler High School","Ea":"375 Holt Rd.","Ec":"Marietta","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIACHM2","S":2022,"En":"IA Chemical_Meet_2023-01-07","Ev":"Diagonal School","Ea":"403 West Second Street","Ec":"Diagonal","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAWILT","S":2022,"En":"IA Wind League Tournament","Ev":"Fort Dodge High School","Ea":"819 N 25th Street","Ec":"Fort Dodge","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USIAMALT","S":2022,"En":"IA Magnetic League Tournament","Ev":"Central Lyon High School","Ea":"1010 S. Greene St","Ec":"Rock Rapids","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USIAGEM2","S":2022,"En":"IA Geothermal_Meet_2023-01-06","Ev":"Harding Middle School","Ea":"4801 Golf St. NE","Ec":"Cedar Rapids","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-06T00:00:00","Ed":"2023-01-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIASOM4","S":2022,"En":"IA Solar_Meet_2023-01-07","Ev":"Lakewood Elementary","Ea":"9210 Happy Hollow Dr.","Ec":"Norwalk","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/E2ttZ1oTEtg","eventType":1000},{"Tc":"USIDPFS4","S":2022,"En":"ID North Idaho Scrimmage #4","Ev":"4-H University of Idaho Research Park","Ea":"721 S. Lochsa Street","Ec":"Post Falls","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USILPM3","S":2022,"En":"IL Peoria Meet 3","Ev":"Peoria Woodruff Career Technical Center (WCTC)","Ea":"1800 NE Perry Avenue","Ec":"Peoria","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINSLM2","S":2022,"En":"IN FIN South League Meet 2","Ev":"Shoals Jr-Sr High School","Ea":"7900 US-50","Ec":"Shoals","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMALEQ","S":2022,"En":"MA Battle of Lexington 8.0","Ev":"Lexington High School","Ea":"251 Waltham Street","Ec":"Lexington","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSSWMIM5","S":2022,"En":"MOKS-MO Kickapoo 2","Ev":"Kickapoo High School","Ea":"3710 S Jefferson Ave","Ec":"Kickapoo","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM11","S":2022,"En":"MOKS-MO STLN Christian High Meet","Ev":"Christian High School","Ea":"1145 Tom Ginnever Ave","Ec":"O\u0027Fallon","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM7","S":2022,"En":"MOKS-MO Discovery Elementary AM","Ev":"Discovery Elementary","Ea":"500 Discovery Path Lane","Ec":"St Charles","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLNM6","S":2022,"En":"MOKS-MO Discovery Elementary PM","Ev":"Discovery Elementary","Ea":"500 Discovery Path Lane","Ec":"St Charles","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLMM6","S":2022,"En":"MOKS-MO MICDS","Ev":"MICDS (Mary Institute and St. Louis Country Day School)","Ea":"101 N Warson Rd","Ec":"St. Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-06T00:00:00","Ed":"2023-01-06T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMSGRQ3","S":2022,"En":"MS Grenada Qualifier","Ev":"Grenada Middle School","Ea":"28 Jones Rd","Ec":"Grenada","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNCELS","S":2022,"En":"NC Elon Power Play Scrimmage","Ev":"The Elon Community Church Community Life Center","Ea":"271 N Williamson Ave","Ec":"Elon","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.youtube.com/watch?v=u0C9vXgcTlU","eventType":0},{"Tc":"USNJNOM5","S":2022,"En":"NJ 0107-P3  Northern League Meet (Saturday)","Ev":"Liberty Science Center","Ea":"222 Jersey City Blvd","Ec":"Jersey City","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJUCM4","S":2022,"En":"NJ 0108-P3  Upper Central League Meet (Sunday)","Ev":"The Pingry School","Ea":"131 Martinsville Rd","Ec":"Basking Ridge","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-01-08T00:00:00","Ed":"2023-01-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNYEXCOQ","S":2022,"En":"NY-Excelsior Corning Qualifier","Ev":"Corning-Painted Post High School Field House","Ea":"Aisne Street","Ec":"Corning","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-01-08T00:00:00","Ed":"2023-01-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHCLQ","S":2022,"En":"OH Kirtland Qualifier","Ev":"Kirtland High School","Ea":"9150 Chillicothe Rd","Ec":"Cleveland","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-01-06T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOKOKLAM14","S":2022,"En":"OK OSSM","Ev":"Oklahoma School of Science and Mathematics","Ea":"1141 N Lincoln Blvd","Ec":"Oklahoma City","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-01-08T00:00:00","Ed":"2023-01-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOKOKLAM13","S":2022,"En":"OK Mustang - January","Ev":"Mustang High School","Ea":"801 S Snyder Dr","Ec":"Mustang","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORMWM2","S":2022,"En":"OR Midwestern League Meet 2","Ev":"Thurston High School","Ea":"333 58th St","Ec":"Springfield","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORSFM3","S":2022,"En":"OR Silicon Forest League Meet 3","Ev":"Hillsboro High School","Ea":"3285 SE Rood Bridge Rd","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORMWM3","S":2022,"En":"OR Midwestern League Meet 3","Ev":"Thurston High School","Ea":"333 58th St","Ec":"Springfield","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORSOM3","S":2022,"En":"OR SOAR League Meet 3","Ev":"Roseburg High School","Ea":"400 Harvard Ave","Ec":"Roseburg","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORRCM3","S":2022,"En":"OR Rose City League Meet 3","Ev":"Franklin HS","Ea":"5405 SE Woodward St","Ec":"Portland","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USPAPHS","S":2022,"En":"PA FTC Scrimmage","Ev":"The School District of Philadelphia Board of Education Building","Ea":"440 North Broad St","Ec":"Philadelphia","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-01-06T00:00:00","Ed":"2023-01-06T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USRIPRQ","S":2022,"En":"RI Wheeler School Qualifier","Ev":"The Wheeler School","Ea":"216 Hope Street","Ec":"Providence","Es":"RI","Ect":"USA","Dn":"Rhode Island","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USSCFLS2","S":2022,"En":"SC PeeDee Scrimmage 2","Ev":"Mayo High School","Ea":"405 Chestnut St","Ec":"Darlington","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTNCHS","S":2022,"En":"TN Baylor School Chattanooga","Ev":"Baylor School","Ea":"171 Baylor School Rd, Chattanooga, TN","Ec":"Chattanooga","Es":"TN","Ect":"USA","Dn":"Tennessee","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNOFLM3","S":2022,"En":"TX-North F-League Meet 3","Ev":"QD Academy","Ea":"4102 Legacy Dr, Plano, TX 75024","Ec":"Plano, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCESTM1","S":2022,"En":"TX-Central SSTallions Meet 3","Ev":"SST (San Antonio)","Ea":"4410 David Edwards Dr","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOMLM3","S":2022,"En":"TX-North M-League Meet 3","Ev":"MAS DFW","Ea":"1515 Blake Dr, Richardson, TX 75081","Ec":"Richardson, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-07T00:00:00","Ed":"2023-01-07T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000}]},{"Wt":"of 01/09/2023","Ws":"2023-01-09T00:00:00","We":"2023-01-15T23:59:59","Wn":18,"Ec":98,"E":[{"Tc":"CAABABSAM3","S":2022,"En":"AB Southern Alberta Round 3 (Junior High Only)","Ev":"University of Calgary Schulich School of Engineering Atrium (hosted by AC Robotics","Ea":"622 Collegiate Pl NW","Ec":"Calgary","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"CABCKIS6","S":2022,"En":"BC Northern Scrimmage 6","Ev":"Mt. Elizabeth Secondary","Ea":"1491 Kingfisher Ave,","Ec":"Kitimat","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"CAONKIQ","S":2022,"En":"ON Kingston Qualifier","Ev":"Loyalist Collegiate Vocational Institute","Ea":"153 Van Order Drive","Ec":"Kingston","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"JMK6S2","S":2022,"En":"JM Jamaica College Scrimmage","Ev":"Karl Hendrickson Auditorium - Jamaica College","Ea":"189 Old Hope Road","Ec":"Kingston 6","Es":"02","Ect":"Jamaica","Dn":"Jamaica","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"KZKAQ","S":2022,"En":"KZ DARYN Tournament","Ev":"Suleyman Demirel University","Ea":"Abylai khan 1/1","Ec":"Kaskelen","Es":"ALM","Ect":"Kazakhstan","Dn":"Kazakhstan","Sd":"2023-01-10T00:00:00","Ed":"2023-01-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"NLNLM3","S":2022,"En":"NL League Meet Bladel","Ev":"Pius X-college","Ea":"Tuinstraat 1-3","Ec":"Bladel","Es":"NB","Ect":"Netherlands","Dn":"Netherlands","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/ftcnetherlands","eventType":1000},{"Tc":"GBCHS","S":2022,"En":"GB North Scrimmage","Ev":"Outwood Academy  Newbold,","Ea":"Highfield Lane,","Ec":"Chesterfield","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-01-12T00:00:00","Ed":"2023-01-12T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"GBSTS","S":2022,"En":"GB West Midlands Scrimmage","Ev":"Newcastle and Stafford Colleges Group","Ea":"Newcastle campus, Knutton Lane, Staffordshire","Ec":"Staffordshire","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-01-10T00:00:00","Ed":"2023-01-10T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"GBBES","S":2022,"En":"GB Northern Ireland Scrimmage","Ev":"W5 Science Discovery Centre","Ea":"The Odyssey, 2 Queens Quay,","Ec":"Belfast","Es":"NIR","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-01-10T00:00:00","Ed":"2023-01-10T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAZGOQ","S":2022,"En":"AZ Palo Verde - Goodyear Qualifier","Ev":"Trivium Preparatory Academy","Ea":"2001 N. Bullard Ave.","Ec":"Goodyear","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1004},{"Tc":"USCANOPNM3","S":2022,"En":"CA-NorCal Peninsula League Meet 3","Ev":"Jefferson High School","Ea":"6996 Mission Street","Ec":"Daly City","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSJQ2","S":2022,"En":"CA-NorCal San Jose #2 Qualifying Tournament","Ev":"The Play Space","Ea":"2215 Oakland Rd","Ec":"San Jose","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCALAEM2","S":2022,"En":"CA-SoCal League E - Meet 2","Ev":"The Webb Schools","Ea":"1175 W Baseline Road","Ec":"Claremont","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAC1M3","S":2022,"En":"CA-SoCal League C1 - Meet 3","Ev":"La Ca\u00F1ada High School","Ea":"4463 Oak Grove Drive","Ec":"La Canada","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANONEM3","S":2022,"En":"CA-NorCal North East League Meet 3","Ev":"Berean Christian High School","Ea":"245 El Divisadero Avenue","Ec":"Walnut Creek","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAO1M2","S":2022,"En":"CA-SoCal League O1 - Meet 2","Ev":"Arena Soccer Park of Orange","Ea":"2190 N Canal St","Ec":"Orange","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAC2M2","S":2022,"En":"CA-SoCal League C2 - Meet 2","Ev":"Santa Fe Middle School","Ea":"148 W Duarte Rd","Ec":"Monrovia","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSCQ2","S":2022,"En":"CA-NorCal Santa Clara #2 Qualifying Tournament","Ev":"Wilcox High School","Ea":"3250 Monroe Street","Ec":"Santa Clara","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSWAQ","S":2022,"En":"CHS-DC Qualifier 1","Ev":"DC International School","Ea":"1400 Main Dr NW","Ec":"Washington","Es":"DC","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSWAQ1","S":2022,"En":"CHS-DC Qualifier 2","Ev":"DC International School","Ea":"1400 Main Dr NW","Ec":"Washington","Es":"DC","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USDEWIS2","S":2022,"En":"DE FTC Meet -- Tower Hill","Ev":"Tower Hill School","Ea":"2813 W. 17th St","Ec":"Wilmington","Es":"DE","Ect":"USA","Dn":"Delaware","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLOLM3","S":2022,"En":"FL Orlando Robotics League Meet #3","Ev":"Lake Highland Preparatory School","Ea":"741 N Mills Ave","Ec":"Orlando","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLSPM4","S":2022,"En":"FL Space Coast Pink Pac Rat Party","Ev":"Rockledge High School","Ea":"220 Rockledge Ave","Ec":"Rockledge","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLOCM4","S":2022,"En":"FL ONECLAY League Meet #4","Ev":"Orange Park Junior High : Cafeteria","Ea":"1500 Gano Avenue","Ec":"Orange Park","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLGCM3","S":2022,"En":"FL Gulf Coast League Meet #3","Ev":"Cypress Lakes High School","Ea":"6750 Panther Lane","Ec":"Fort Myers","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLNEM4","S":2022,"En":"FL North East League Meet #4","Ev":"Bolles Bartram Campus","Ea":"2264 Bartram Road","Ec":"Jacksonville","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USFLFLROM3","S":2022,"En":"FL ROBOT League Meet #3","Ev":"University Square Mall","Ea":"2154 University Square Mall","Ec":"Tampa","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGANORTM5","S":2022,"En":"GA N Georgia Meet 5","Ev":"Lakeview Academy","Ea":"796 Lakeview Drive","Ec":"Gainesville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAATHM4","S":2022,"En":"GA Caterpillar Meet 4","Ev":"Oconee County High School","Ea":"2721 Hog Mountain Road","Ec":"Watkinsville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-01-10T00:00:00","Ed":"2023-01-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGAJACKM5","S":2022,"En":"GA Jackson Meet 5","Ev":"East Jackson High School","Ea":"1435 Hoods Mill Road","Ec":"Commerce","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGADOUGM4","S":2022,"En":"GA Douglasville Meet 4","Ev":"Douglas County High School","Ea":"8705 Campbellton Street","Ec":"Douglasville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USHICMP","S":2022,"En":"Hawai\u2019i Regional Championship","Ev":"Le Jardin Academy","Ea":"917 Kalaniana\u02BBole Hwy,","Ec":"Honolulu","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBA","eventType":1010},{"Tc":"USIAGEM1","S":2022,"En":"IA Geothermal_Meet_2023-01-10","Ev":"Veterans Memorial Coliseum","Ea":"50 2nd Ave. Bridge","Ec":"Cedar Rapids","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-10T00:00:00","Ed":"2023-01-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USIAHYLT","S":2022,"En":"IA  Hydro League Tournament","Ev":"Pleasant Valley High School","Ea":"604 Belmont Rd.","Ec":"Riverdale","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USIANULT","S":2022,"En":"IA Nuclear League Tournament","Ev":"Peet Junior High School","Ea":"525 E. Seerley Blvd","Ec":"Cedar Falls","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USIDGOS","S":2022,"En":"ID Southern Idaho Scrimmage","Ev":"Gooding High School","Ea":"1050 7th Avenue W.","Ec":"Gooding","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USILSSM3","S":2022,"En":"IL South Suburbs Meet 3","Ev":"Parker Junior High School","Ea":"2810 School St","Ec":"Flossmoor","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILNEM3","S":2022,"En":"IL Northeast Lake Meet 3","Ev":"Carmel Catholic High School","Ea":"One Carmel Parkway","Ec":"Mundelein","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILFNM3","S":2022,"En":"IL Fox Valley North Meet 3","Ev":"Calvary Church","Ea":"5906 IL-31 S","Ec":"Crystal Lake","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILSM3","S":2022,"En":"ILSouthern Meet 3","Ev":"Granite City High School","Ea":"3101 Madison Ave","Ec":"Granite City","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCMM3A","S":2022,"En":"IL Chicago Meet 3A","Ev":"Wolcott School","Ea":"1950 W Hubbard St.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILWM3","S":2022,"En":"IL Western Meet 3","Ev":"Orion High School","Ea":"1100 13th Street","Ec":"Orion","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCM3","S":2022,"En":"IL Central Meet 3","Ev":"Decatur Christian School","Ea":"137 S Grant St","Ec":"Forsyth","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILFSM3","S":2022,"En":"IL Fox Valley South Meet 3","Ev":"North Central College Wentz Science Center","Ea":"131 S Loomis St","Ec":"Naperville","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILNSM3","S":2022,"En":"IL North Shore Meet 3","Ev":"Northridge Preparatory School","Ea":"8320 W Ballard Rd","Ec":"Niles","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINISM3","S":2022,"En":"IN FIN Indy South League Meet 3","Ev":"Avon High School","Ea":"7575 E County Rd 150 S","Ec":"Avon","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINNWM3","S":2022,"En":"IN West Central League Meet #3","Ev":"Battle Ground Middle School","Ea":"6100 N 50 W","Ec":"West Lafayette","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINSLM3","S":2022,"En":"IN FIN South League Meet 3","Ev":"Shoals Jr-Sr High School","Ea":"7900 US-50","Ec":"Shoals","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMNBUQ1","S":2022,"En":"MN FTC Burnsville Sat. Jan. 14","Ev":"Burnsville High School","Ea":"600 State Hwy 13","Ec":"Burnsville","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMNBUQ2","S":2022,"En":"MN FTC Burnsville Sun. Jan. 15","Ev":"Burnsville High School","Ea":"600 State Hwy 13","Ec":"Burnsville","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSKCWM6","S":2022,"En":"MOKS-MO East Trails KC West AM","Ev":"East Trails Middle School","Ea":"1001 SE Bailey Rd","Ec":"Lee\u0027s Summit","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCEM6","S":2022,"En":"MOKS-MO East Trails KC East PM","Ev":"East Trails Middle School","Ea":"1001 SE Bailey Rd","Ec":"Lee\u0027s Summit","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLSM3","S":2022,"En":"MOKS-MO St. Joseph\u0027s Academy","Ev":"St. Joseph\u0027s Academy","Ea":"2307 S Lindbergh Blvd","Ec":"St. Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-11T00:00:00","Ed":"2023-01-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSWMIM4","S":2022,"En":"MOKS-MO Rolla Technical Institute 2","Ev":"Rolla Technical Institute","Ea":"1304 E 10th St","Ec":"Rolla","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLMM7","S":2022,"En":"MOKS-MO Girl Scouts","Ev":"Girl Scouts of Eastern Missouri - Berges Family Center","Ea":"200 Ball Dr","Ec":"St. Louis","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMSBCQ4","S":2022,"En":"MS Bogue Chitto Qualifier","Ev":"Bogue Chitto Attendance Center","Ea":"385 Monticello St SE","Ec":"Bogue Chitto","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNCHUQ","S":2022,"En":"NC FTC JM Alexander MS","Ev":"JM Alexander Middle School","Ea":"12010 Hambright Rd","Ec":"Huntersville","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USNDFAQ","S":2022,"En":"ND Dakota State Qualifier at NDSU","Ev":"Bentson/Bunker Fieldhouse","Ea":"1301 Centennial Blvd","Ec":"Fargo","Es":"ND","Ect":"USA","Dn":"North Dakota","Sd":"2023-01-09T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1004},{"Tc":"USIACHM6","S":2022,"En":"IA-NE Chemical_Meet_2023-01-14","Ev":"Northeast Community College","Ea":"601 E Benjamin Ave","Ec":"Norfolk","Es":"NE","Ect":"USA","Dn":"Iowa","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNHMAQ","S":2022,"En":"NH Derryfield Qualifier #1","Ev":"The Derryfield School","Ea":"2108 River Rd, Manchester, NH 03104","Ec":"Manchester","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNJNEM5","S":2022,"En":"NJ 0114-P3  Northeast Edge League Meet (Saturday)","Ev":"Millburn High School","Ea":"462 Millburn Ave","Ec":"Millburn","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJSOM5","S":2022,"En":"NJ 0115-P3  Southern League Meet (Sunday)","Ev":"P.A.L. of Atlantic County \u0026 EHT","Ea":"2542 Ridge Ave","Ec":"Egg Harbor Township","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNMALQ","S":2022,"En":"NM Albuquerque FTC Qualifier","Ev":"La Academia de Esperanza Charter School","Ea":"7311 Glenrio NW","Ec":"Albuquerque","Es":"NM","Ect":"USA","Dn":"New Mexico","Sd":"2023-01-13T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYNYQUQ6","S":2022,"En":"NY-NYC Qualifier 6","Ev":"Francis Lewis High School","Ea":"58-20 Utopia Parkway","Ec":"Queens","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYEXPEQ2","S":2022,"En":"NY-Excelsior Peekskill Qualifier","Ev":"Peekskill High School","Ea":"1072 Elm St","Ec":"Peekskill","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYLIFPQ2","S":2022,"En":"NY-Long Island Qualifier #2","Ev":"Sewanhaka High School","Ea":"500 Tulip Avenue","Ec":"Floral Park","Es":"NY","Ect":"USA","Dn":"New York - Long Island","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYLIFPQ1","S":2022,"En":"NY-Long Island Qualifier #1","Ev":"Sewanhaka High School","Ea":"500 Tulip Avenue","Ec":"Floral Park","Es":"NY","Ect":"USA","Dn":"New York - Long Island","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYEXALQ","S":2022,"En":"NY-Excelsior Albany Academies Qualifier","Ev":"Albany Academies - Silipigno Athletic Center","Ea":"140 Academy Rd","Ec":"Albany","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYNYQUQ5","S":2022,"En":"NY-NYC Qualifier 5","Ev":"Francis Lewis High School","Ea":"58-20 Utopia Parkway","Ec":"QUEENS","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHOXQ","S":2022,"En":"OH Miami University Qualifier","Ev":"Millet Hall, Miami University","Ea":"500 E Sycamore St","Ec":"Oxford","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-01-12T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1004},{"Tc":"USOKOKLAM11","S":2022,"En":"OK TSAS January","Ev":"Tulsa School of Arts and Sciences","Ea":"1202 W Easton St","Ec":"Tulsa","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USPACTQ","S":2022,"En":"PA Southwestern Qualifier","Ev":"North Catholic High School","Ea":"1617 Pennsylvania 228","Ec":"Cranberry Township","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USRIEGQ","S":2022,"En":"RI New England Tech Qualifier","Ev":"New England Tech East Greenwich campus","Ea":"One New England Tech Blvd","Ec":"East Greenwich","Es":"RI","Ect":"USA","Dn":"Rhode Island","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USTXCENSAM6","S":2022,"En":"TX-Central Hill Country Field Meet 3","Ev":"Family Service Neighborhood Place","Ea":"3014 Rivas St","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEWAM3","S":2022,"En":"TX-Central Waco League Meet 3","Ev":"GWAMA","Ea":"2401 JJ Flewellen Rd","Ec":"Waco","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-12T00:00:00","Ed":"2023-01-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOWLM2","S":2022,"En":"TX-Houston West League Meet 1","Ev":"Hogg Middle School","Ea":"1100 Merrill St.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCENSAM5","S":2022,"En":"TX-Central North San Field Meet 3","Ev":"Family Service Neighborhood Place","Ea":"3014 Rivas St","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEAUS3","S":2022,"En":"TX-Central Vandegrift Scrimmage","Ev":"Vandegrift HS","Ea":"9500 McNeil Drive","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-10T00:00:00","Ed":"2023-01-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXHONEM2","S":2022,"En":"TX-Houston Northeast League Meet 2","Ev":"Livingston High School","Ea":"400 FM 350 South","Ec":"Livingston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNODLM3","S":2022,"En":"TX-North D-League Meet 3","Ev":"Dealey Montessori Academy, DISD","Ea":"6503 Royal Ln, Dallas, TX 75230","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEGMM4","S":2022,"En":"TX-Central GEMS Meet 3","Ev":"Westwood HS","Ea":"12400 Mellow Meadow Dr","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOCULT","S":2022,"En":"TX-South Curie League Tournament","Ev":"Vanguard Rembrandt Secondary Academy","Ea":"1200 E. Kelly Ave","Ec":"Pharr","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXNOTLM3","S":2022,"En":"TX-North T-League Meet 3","Ev":"New Tech High @ Coppell","Ea":"113 Samuel Blvd, Coppell, TX 75019","Ec":"Coppell, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEOH90M3","S":2022,"En":"TX-Central Old Highway 90 Meet 3","Ev":"Brentwood MS","Ea":"1626 W. Thompson Pl","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHONLM2","S":2022,"En":"TX-Houston North League Meet 2","Ev":"Brabham Middle School","Ea":"10000 Fm 830 Rd.","Ec":"Willis","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEXSTM4","S":2022,"En":"TX-Central X-STREAM A Meet 3","Ev":"Kipp Collegiate HS","Ea":"8004 Cameron Road","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEKWM3","S":2022,"En":"TX-Central Kwolek Meet 3","Ev":"Judson Middle School","Ea":"9695 Schaefer Rd","Ec":"Converse","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOSELM2","S":2022,"En":"TX-Houston SE Meet 2","Ev":"Lutheran South Academy","Ea":"12555 Ryewater Dr.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOCLM1","S":2022,"En":"TX-Houston Central League Meet 1","Ev":"Hogg Middle School","Ea":"1100 Merrill St.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPAMM3","S":2022,"En":"TX-W\u0026P Amarillo League Meet #3","Ev":"AmTech Career Academy","Ea":"3601 Plains Blvd","Ec":"Amarillo","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOXMLM3A","S":2022,"En":"TX-North X-League Metro Meet 3A","Ev":"Roboplex at Marcus HS, LISD","Ea":"5711 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPEPM3","S":2022,"En":"TX-W\u0026P El Paso League Meet #3","Ev":"Cathedral High School","Ea":"1309 N Stanton St","Ec":"El Paso","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPLAMA3","S":2022,"En":"TX-W\u0026P Lubbock-A League Meet #3","Ev":"Irons Middle School","Ea":"5214 79th St","Ec":"Lubbock","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOELM1","S":2022,"En":"TX-Houston East League Meet 1","Ev":"Mickey Leland College Prep.","Ea":"1700 Gregg St","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEXSTM3","S":2022,"En":"TX-Central X-STREAM B Meet 3","Ev":"Kipp Collegiate HS","Ea":"8004 Cameron Road","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOXMLM3B","S":2022,"En":"TX-North X-League Metro Meet 3B","Ev":"Roboplex at Marcus HS, LISD","Ea":"5712 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCHSCHQ2","S":2022,"En":"CHS-VA Charlottesville Qualifier","Ev":"Albemarle High School","Ea":"2775 Hydraulic Rd","Ec":"Charlottesville","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USWIBRS2","S":2022,"En":"WI Mentor Madness Scrimmage - Hosted by RhinoBots/Alien","Ev":"MSOE STEM Center","Ea":"1444 N. Water St. Milwaukee WI","Ec":"Milwaukee","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2023-01-15T00:00:00","Ed":"2023-01-15T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 01/16/2023","Ws":"2023-01-16T00:00:00","We":"2023-01-22T23:59:59","Wn":19,"Ec":92,"E":[{"Tc":"CAABABNAM4","S":2022,"En":"AB Northern Alberta Round #4","Ev":"Strathcona County Community Centre","Ea":"401 Festival Ln","Ec":"Sherwood Park","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"KZASQ","S":2022,"En":"KZ Nurorda Tournament","Ev":"Nurorda School","Ea":"Kasym Amanzholov 34","Ec":"Astana","Es":"AST","Ect":"Kazakhstan","Dn":"Kazakhstan","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"MXTOSQ","S":2022,"En":"MX FTC POWER PLAY Regional Norte (Torre\u00F3n)","Ev":"Colegio Cervantes campus Torre\u00F3n.","Ea":"Calz Jos\u00E9 Vasconcelos 545, Exhacienda los \u00C1ngeles, 27276 Torre\u00F3n, Coah.","Ec":"Torreon","Es":"COA","Ect":"Mexico","Dn":"Mexico","Sd":"2023-01-20T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"MXTOSQ2","S":2022,"En":"MX FTC POWER PLAY Regional Centro (Toluca)","Ev":"TECMILENIO CAMPUS TOLUCA","Ea":"Calle Guadalupe Victoria 221, Las Jaras, 52160 Metepec, M\u00E9x.","Ec":"Toluca","Es":"MEX","Ect":"Mexico","Dn":"Mexico","Sd":"2023-01-20T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"NLNLM4","S":2022,"En":"NL League Meet Zeist","Ev":"KSG De Breul","Ea":"Arnhemse Bovenweg 98","Ec":"Zeist","Es":"UT","Ect":"Netherlands","Dn":"Netherlands","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/ftcnetherlands","eventType":1000},{"Tc":"ZACTQ","S":2022,"En":"Western Cape Regional","Ev":"Protea Height academy","Ea":"33 Helling Street","Ec":"Cape Town","Es":"WC","Ect":"South Africa","Dn":"South Africa","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"GBCAS","S":2022,"En":"GB East Scrimmage","Ev":"Arm Ltd.","Ea":"Central Building 110","Ec":"Cambridge","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-01-19T00:00:00","Ed":"2023-01-19T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"GBBOS","S":2022,"En":"GB South West Scrimmage","Ev":"Bournemouth School for Girls","Ea":"Castle Gate Cl,","Ec":"Bournemouth","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-01-16T00:00:00","Ed":"2023-01-16T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAKCMP","S":2022,"En":"Alaska State Championship","Ev":"Colony High School","Ea":"9550 East Bogard Road","Ec":"Palmer","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2023-01-20T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USAZCHQ","S":2022,"En":"AZ Turquoise - Chandler Qualifier","Ev":"Valley Christian High School","Ea":"6900 W. Galveston St.","Ec":"Chandler","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1004},{"Tc":"USCASDSDTUM3","S":2022,"En":"CA- San Diego Turing Meet #3, Mater Dei","Ev":"Mater Dei Catholic High School","Ea":"1615 Mater Dei Dr","Ec":"Chula Vista","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAC2M3","S":2022,"En":"CA-SoCal League C2 - Meet 3","Ev":"Santa Fe Middle School","Ea":"148 W Duarte Rd","Ec":"Monrovia","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDGAM3","S":2022,"En":"CA- San Diego Gauss Meet #3, Mater Dei","Ev":"Mater Dei Catholic High School","Ea":"1617 Mater Dei Dr","Ec":"Chula Vista","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSJQ3","S":2022,"En":"CA-NorCal San Jose #3 Qualifying Tournament","Ev":"Statford Preparatory","Ea":"3800 Blackford Avenue","Ec":"San Jose","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCALAVM3","S":2022,"En":"CA-SoCal League V - Meet 3","Ev":"Ojai Valley School \u2013 Littlefield Student Commons","Ea":"10820 Revees Road","Ec":"Ojai","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDEUM3","S":2022,"En":"CA- San Diego Euclid Meet #3, Mater Dei","Ev":"Mater Dei Catholic High School","Ea":"1615 Mater Dei Dr","Ec":"Chula Vista","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALSLAQ","S":2022,"En":"CALS LAUSD Qualifier 1","Ev":"TBD","Ea":"TBD","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"Los Angeles Unified School District","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCANOROQ","S":2022,"En":"CA-NorCal Roseville Qualifying Tournament","Ev":"Roseville High School","Ea":"1 Tiger Way","Ec":"Roseville","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCALAF1M3","S":2022,"En":"CA-SoCal League F1 - Meet 3","Ev":"Heritage High School","Ea":"26001 Briggs Road","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAF2M3","S":2022,"En":"CA-SoCal League F2 - Meet 3","Ev":"Heritage High School","Ea":"26001 Briggs Road","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAWM3","S":2022,"En":"CA-SoCal League W - Meet 3","Ev":"Crossroads Elementary School","Ea":"1715 Olympic Blvd","Ec":"Santa Monica","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALABM2","S":2022,"En":"CA-SoCal League B - Meet 2","Ev":"Dominguez High School,","Ea":"15301 San Jose Avenue","Ec":"Compton","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAO1M3","S":2022,"En":"CA-SoCal League O1 - Meet 3","Ev":"Arena Soccer Park of Orange","Ea":"2190 N Canal St","Ec":"Orange","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSBM3A","S":2022,"En":"CA-NorCal South Bay Metro League Meet 3a","Ev":"The King\u0027s Academy","Ea":"562 N Britton Avenue","Ec":"Sunnyvale","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAA1M3","S":2022,"En":"CA-SoCal League A1 - Meet 3","Ev":"Marlborough School","Ea":"250 South Rossmore Avenue","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCASDSDDEM3","S":2022,"En":"CA- San Diego Descartes Meet #3, Mater Dei","Ev":"Mater Dei Catholic High School","Ea":"1615 Mater Dei Dr","Ec":"Chula Vista","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCALAEM3","S":2022,"En":"CA-SoCal League E - Meet 3","Ev":"The Webb Schools","Ea":"1175 W Baseline Road","Ec":"Claremont","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOSBM3B","S":2022,"En":"CA-NorCal South Bay Metro League Meet 3b","Ev":"The King\u0027s Academy","Ea":"562 N Britton Avenue","Ec":"Sunnyvale","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCOBRQ","S":2022,"En":"CO Broomfield Qualifier","Ev":"Prospect Ridge Academy","Ea":"2555 Preble Creek Pkwy","Ec":"Broomfield","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCTWOQ","S":2022,"En":"CT Wolcott Qualifier","Ev":"Wolcott High School","Ea":"457 Bound Line Rd","Ec":"Wolcott","Es":"CT","Ect":"USA","Dn":"Connecticut","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://twitch.tv/ctftc","eventType":1004},{"Tc":"USFLFLSFM3","S":2022,"En":"FL South Florida Meet #3","Ev":"North Broward Preparatory School","Ea":"7600 Lyons Road","Ec":"Coconut Creek","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USGANWLT","S":2022,"En":"GA Northwest Georgia League Tournament","Ev":"Mount Paran Christian School","Ea":"1275 Stanley Rd NW","Ec":"Kennesaw","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USGASOUTLT","S":2022,"En":"GA South Georgia League Tournament","Ev":"First Presbyterian Day School","Ea":"5671 Calvin Dr","Ec":"Macon","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USIASOLT","S":2022,"En":"IA Solar League Tournament","Ev":"Wallace Elementary","Ea":"6207 NW 62nd Ave","Ec":"Johnston","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/rQihDMOYE-I","eventType":1001},{"Tc":"USILCMM3B","S":2022,"En":"IL Chicago Meet 3B","Ev":"Bowen HS","Ea":"2710 E 89th St.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILRM3","S":2022,"En":"IL Rockford Meet 3","Ev":"Guilford High School","Ea":"5620 Spring Creek Rd","Ec":"Rockford","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINNCM5","S":2022,"En":"IN FIN North Central League Meet 5","Ev":"Career Academy","Ea":"3801 Crescent Cir","Ec":"South Bend","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USINISLT","S":2022,"En":"IN FIN Indy-South League Tournament","Ev":"Central Middle School","Ea":"725 7th St","Ec":"Columbus","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USINNCM6","S":2022,"En":"IN FIN North Central League Meet 6","Ev":"Career Academy","Ea":"3801 Crescent Cir","Ec":"South Bend","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USKYKYM2","S":2022,"En":"KY Dunker Meet #2","Ev":"Murray State University","Ea":"1375 Chestnut Street","Ec":"Murray","Es":"KY","Ect":"USA","Dn":"Kentucky","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USLANOQ","S":2022,"En":"LA Qualifier 2","Ev":"St Mary\u0027s Dominican High School","Ea":"7701 Walmsley Ave","Ec":"New Orleans","Es":"LA","Ect":"USA","Dn":"Louisiana","Sd":"2023-01-20T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMAANQ4","S":2022,"En":"MA Robostorm 7.2","Ev":"Andover High School","Ea":"80 Shawsheen Road","Ec":"Andover","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMAANQ3","S":2022,"En":"MA Robostorm 7.1","Ev":"Andover High School","Ea":"80 Shawsheen Road","Ec":"Andover","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSLAQ","S":2022,"En":"CHS-MD Laurel Qualifier","Ev":"Johns Hopkins Universtiy","Ea":"11100 Johns Hopkins Rd","Ec":"Laurel","Es":"MD","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSMCQ","S":2022,"En":"CHS-MD McHenry Qualifier","Ev":"Garrett College","Ea":"687 Mosser Rd","Ec":"McHenry","Es":"MD","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMNLLT1","S":2022,"En":"MN FTC Otsego Sat. Jan. 21","Ev":"Prairie View Middle School","Ea":"8300 Maciver Ave NE","Ec":"Otsego","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMNLLT2","S":2022,"En":"MN FTC Otsego Sun. Jan. 22","Ev":"Prairie View Middle School","Ea":"8300 Maciver Ave NE","Ec":"Otsego","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMOKSSEM3","S":2022,"En":"MOKS-MO Jackson","Ev":"Jackson High School","Ea":"315 S Missouri St","Ec":"Jackson","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSWMIM7","S":2022,"En":"MOKS-MO Lebanon Meet","Ev":"Lebanon Middle School","Ea":"2700 Buzz Pride Drive","Ec":"Lebanon","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCEM5","S":2022,"En":"MOKS-MO Belton KC East AM","Ev":"Yeokum Center of Innovation","Ea":"613 Mill St.","Ec":"Belton","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSKCWM5","S":2022,"En":"MOKS-MO Belton KC West PM","Ev":"Yeokum Center of Innovation","Ea":"613 Mill St.","Ec":"Belton","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLMM4","S":2022,"En":"MOKS-MO Eureka PM","Ev":"Eureka High School","Ea":"4525 MO-109","Ec":"Eureka","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLMM5","S":2022,"En":"MOKS-MO Eureka AM","Ev":"Eureka High School","Ea":"4525 MO-109","Ec":"Eureka","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMOKSSTLSM4","S":2022,"En":"MOKS-MO Webster Groves 2","Ev":"Webster Groves High School","Ea":"100 Selma Ave","Ec":"Webster Groves","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USMSMEQ2","S":2022,"En":"MS Meridian Qualifier","Ev":"The Lamar School","Ea":"544 Lindley Road","Ec":"Meridian","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNCSMQ","S":2022,"En":"NC FTC Smithfield-Selma HS","Ev":"Smithfield-Selma High School","Ea":"700 M Durwood Stephenson Pkwy","Ec":"Smithfield","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USNCROQ","S":2022,"En":"NC FTC Thales Academy Rolesville","Ev":"Thales Academy Rolesville","Ea":"1201 Granite Falls Blvd","Ec":"Rolesville","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USNDBIQ","S":2022,"En":"ND Dakota State Qualifier at The Dakota Adventist Academy","Ev":"Dakota Adventist Academy","Ea":"15905 Scheyenne Circle","Ec":"Bismarck","Es":"ND","Ect":"USA","Dn":"North Dakota","Sd":"2023-01-16T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1004},{"Tc":"USNHWIQ","S":2022,"En":"NH Windham Qualifier #2","Ev":"Windham High School","Ea":"64 London Bridge Rd","Ec":"Windham","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNJUCM6","S":2022,"En":"NJ 0121-P3  Upper Central League Meet (Saturday)","Ev":"Chatham High School","Ea":"255 Lafayette Street","Ec":"Chatham","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJNOM6","S":2022,"En":"NJ 0122-P3  Northern League Meet (Sunday)","Ev":"Blair Academy","Ea":"2 Park Street","Ec":"Blairstown","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNVNOM4N","S":2022,"En":"NV Northern League Meet # 4N","Ev":"Virginia City High School","Ea":"95 R St","Ec":"Virginia City","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNVNOM3N","S":2022,"En":"NV Northern League Meet # 3N","Ev":"Virginia City High School","Ea":"95 R St","Ec":"Virginia City","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNVSOM3S","S":2022,"En":"NV Southern League Meet # 3S","Ev":"Rosemary Clarke Middle School","Ea":"4201 N Blagg Rd","Ec":"Pahrump","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNVSOM4S","S":2022,"En":"NV Southern League Meet # 4S","Ev":"Rosemary Clarke Middle School","Ea":"4201 N Blagg Rd","Ec":"Pahrump","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNYEXUTQ","S":2022,"En":"NY-Excelsior MVCC Utica Qualifier","Ev":"Mohawk Valley Community College - Jorgensen Athletic Center","Ea":"1101 Sherman Drive","Ec":"Utica","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOKOKLAM12","S":2022,"En":"OK Oktaha","Ev":"Oktaha High School","Ea":"531 Prairie","Ec":"Oktaha","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USOKOKLAM15","S":2022,"En":"OK SWOSU","Ev":"Southwestern Oklahoma State University","Ea":"100 W Campus Dr","Ec":"Weatherford","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USORWVLT","S":2022,"En":"OR Willamette Valley League Tournament","Ev":"Thurston HS","Ea":"333 58th St","Ec":"Springfield","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USORNCLT","S":2022,"En":"OR North Coast League Tournament","Ev":"Neah-Kah-Nie High School","Ea":"24705 Hwy 101 N","Ec":"Rockaway Beach","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-20T00:00:00","Ed":"2023-01-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USORCBM3","S":2022,"En":"OR Columbia Basin League Meet 3","Ev":"Pendleton High School","Ea":"1800 NW Carden Ave","Ec":"Pendleton","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-18T00:00:00","Ed":"2023-01-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USPAYOQ2","S":2022,"En":"PA Blue and White Qualifier","Ev":"Penn State York","Ea":"1031 Edgecomb Avenue","Ec":"York","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USPAYOQ1","S":2022,"En":"PA South Central Qualifier","Ev":"Penn State York","Ea":"1031 Edgecomb Avenue","Ec":"York","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USRIWOQ","S":2022,"En":"RI Mt. St. Charles Academy Qualifier","Ev":"Mt. St. Charles Academy","Ea":"800 Logee Street","Ec":"Woonsocket","Es":"RI","Ect":"USA","Dn":"Rhode Island","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USSCRHS","S":2022,"En":"SC Upstate Scrimmage 3","Ev":"South Pointe High School","Ea":"801 Neely Rd","Ec":"Rock Hill","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USSCORS3","S":2022,"En":"SC Midlands Scrimmage 3","Ev":"Orangeburg County Libray and Conference Center","Ea":"1645 Russell St","Ec":"Orangeburg","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USSCNLCS3","S":2022,"En":"SC Lowcountry Scrimmage 3","Ev":"Military Magnet High School","Ea":"2950 Carner Ave","Ec":"N. Charleston","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTNNAS","S":2022,"En":"TN Central Magnet Hosting in Mid TN","Ev":"Central Magnet School","Ea":"701 E Main St","Ec":"Murfreesboro","Es":"TN","Ect":"USA","Dn":"Tennessee","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXNOBTLT","S":2022,"En":"TX-North B\u0026T Tournament","Ev":"Daniel Ninth Grade Campus, Aledo ISD","Ea":"990 Bailey Ranch Rd, Aledo, TX 76008","Ec":"Aledo, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOSWM2","S":2022,"En":"TX-Houston Southwest League Meet 1","Ev":"Harmony School of Innovation - Sugar Land","Ea":"13738 Old Richmond Rd","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOFMLT","S":2022,"En":"TX-North F\u0026M Tournament","Ev":"Irving, Texas","Ea":"2555 N Esters Rd, Irving, TX 75062","Ec":"Irving, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXCENSALT","S":2022,"En":"TX-Central North San / Hill Country League Tournament","Ev":"School of Science and Technology - Hill Country","Ea":"9202 W Loop 1604","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-20T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXNOULM3","S":2022,"En":"TX-North U-League Meet 3","Ev":"UME Preparatory Academy","Ea":"3840 TX-408 Spur, Dallas, TX 75236","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOSLM3","S":2022,"En":"TX-Houston South League Meet 3","Ev":"Palacios High School","Ea":"100 Shark Dr","Ec":"Palacios","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXCEWALT","S":2022,"En":"TX-Central Waco League Tournament","Ev":"TBD","Ea":"TBD","Ec":"Waco","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-20T00:00:00","Ed":"2023-01-20T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USTXWPMDM3","S":2022,"En":"TX-W\u0026P Midland League Meet #3","Ev":"Trinity School of Midland","Ea":"3500 W Wadley Ave","Ec":"Midland","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOHALT","S":2022,"En":"TX-South Hawking League Tournament","Ev":"BL Gray Junior/Middle High School","Ea":"4400 Glasscock Rd.","Ec":"Mission","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCHSHAQ1","S":2022,"En":"CHS-VA Harrisonburg Qualifier 1","Ev":"Harrisonburg High School","Ea":"1001 Garbers Church Rd","Ec":"Harrisonburg","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSHAQ2","S":2022,"En":"CHS-VA Harrisonburg Qualifier 2","Ev":"Harrisonburg High School","Ea":"1001 Garbers Church Rd","Ec":"Harrisonburg","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-22T00:00:00","Ed":"2023-01-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USVTBUS","S":2022,"En":"VT FTC scrimmage at South Burlington HS","Ev":"South Burlington High School","Ea":"550 Dorset St, South Burlington, VT","Ec":"Burlington","Es":"VT","Ect":"USA","Dn":"Vermont","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USWABES4","S":2022,"En":"WA Washington Tech Invitational","Ev":"Interlake High School","Ea":"16245 NE 24th St","Ec":"Bellevue","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USWINBQ","S":2022,"En":"WI Patriot Games","Ev":"Heritage Christian School","Ea":"3500 S Glen Park Rd","Ec":"New Berlin","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2023-01-21T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1004}]},{"Wt":"of 01/23/2023","Ws":"2023-01-23T00:00:00","We":"2023-01-29T23:59:59","Wn":20,"Ec":68,"E":[{"Tc":"CAABABSAM4","S":2022,"En":"AB Southern Alberta Round 4","Ev":"Webber Academy","Ea":"1515 93 St SW","Ec":"Calgary","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1000},{"Tc":"CABCVIQ","S":2022,"En":"BC Victoria Qualifier","Ev":"St. Margaret\u0027s School","Ea":"1080 Lucas Ave","Ec":"Victoria","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/@firstroboticsbc/streams","eventType":1004},{"Tc":"CABCSUQ","S":2022,"En":"BC Lower Mainland Qualifier","Ev":"L.A. Matheson Secondary","Ea":"9484 122 St.","Ec":"Surrey","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1004},{"Tc":"CABCVAQ","S":2022,"En":"BC Remote Qualifier","Ev":"Remote Event","Ea":"366 E 3rd Street,","Ec":"Vancouver","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2023-01-19T00:00:00","Ed":"2023-01-25T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"CAONPIQ","S":2022,"En":"ON Remote Qualifying Tournament","Ev":"Remote","Ea":"P.O. Box 518 Pickering Main","Ec":"Pickering","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2023-01-21T00:00:00","Ed":"2023-01-26T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"CAQCCMP","S":2022,"En":"Festival de Robotique - Championnat provincial du D\u00E9fi Techno FIRST","Ev":"Grand Quai du Port de Montr\u00E9al","Ea":"200 de la Commune St W","Ec":"Montr\u00E9al","Es":"QC","Ect":"Canada","Dn":"Qu\u00E9bec","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"ILSDS2","S":2022,"En":"Israel Scrimmage #2","Ev":"Yahalom School","Ea":"24 HaKeshet street","Ec":"Shoam","Es":"D","Ect":"Israel","Dn":"Israel","Sd":"2023-01-26T00:00:00","Ed":"2023-01-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://isrlive.firstisrael.org.il","eventType":0},{"Tc":"ILMES","S":2022,"En":"Israel Scrimmage #1","Ev":"Gitis Sport Center","Ea":"4 Ariel Sharon Street","Ec":"Sderot","Es":"D","Ect":"Israel","Dn":"Israel","Sd":"2023-01-23T00:00:00","Ed":"2023-01-23T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://isrlive.firstisrael.org.il","eventType":0},{"Tc":"KZALQ2","S":2022,"En":"KZ FIZMAT Tournament","Ev":"RPhMS Almaty","Ea":"Bukhar zhyrau 36","Ec":"Almaty","Es":"ALA","Ect":"Kazakhstan","Dn":"Kazakhstan","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"MXCMSQ","S":2022,"En":"MX FTC POWER PLAY Regional CDMX (CDMX)","Ev":"Prepa TEC CCM","Ea":"Prol. Canal de Miramontes 158, Coapa, Tlalpan, 14380 Ciudad de M\u00E9xico, CDMX","Ec":"Ciudad de M\u00E9xico","Es":"CMX","Ect":"Mexico","Dn":"Mexico","Sd":"2023-01-27T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"NLNLM5","S":2022,"En":"NL League Meet Delft","Ev":"Stanislas College Westplantsoen","Ea":"Westplantsoen 71","Ec":"Delft","Es":"ZH","Ect":"Netherlands","Dn":"Netherlands","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/ftcnetherlands","eventType":1000},{"Tc":"ZAJOQ1","S":2022,"En":"Gauteng Regional Event","Ev":"Sci-Bono","Ea":"Mirjam Makeba Street","Ec":"Johannesburg","Es":"GP","Ect":"South Africa","Dn":"South Africa","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USALFPS","S":2022,"En":"AL Scrimmage #2","Ev":"Fort Payne High School","Ea":"201 45th St  NE","Ec":"Fort Payne","Es":"AL","Ect":"USA","Dn":"Alabama","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"n/a","eventType":0},{"Tc":"USAZQCQ","S":2022,"En":"AZ Copper - Queen Creek Qualifier","Ev":"American Leadership Academy Ironwood Campus","Ea":"850 W. Combs Rd.","Ec":"Queen Creek","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1004},{"Tc":"USAZCHQ2","S":2022,"En":"AZ Red Rock - Microchip Qualifier","Ev":"Microchip Technology, Inc","Ea":"2355 W. Chandler Blvd","Ec":"Chandler","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/@firsttechchallengearizona6515","eventType":1004},{"Tc":"USCALSLAQ3","S":2022,"En":"CALS LAUSD Qualifier 3","Ev":"TBD","Ea":"TBD","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"Los Angeles Unified School District","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCANONELT","S":2022,"En":"CA-NorCal North East League Tournament","Ev":"Rosemont High School","Ea":"9594 Kiefer Blvd","Ec":"Sacramento","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCALSLAQ2","S":2022,"En":"CALS LAUSD Qualifier 2","Ev":"TBD","Ea":"TBD","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"Los Angeles Unified School District","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCALABM3","S":2022,"En":"CA-SoCal League B - Meet 3","Ev":"Dominguez High School,","Ea":"15301 San Jose Avenue","Ec":"Compton","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCANOFOQ","S":2022,"En":"CA-NorCal Folsom Qualifying Tournament","Ev":"Sutter Middle School","Ea":"715 Riley Street","Ec":"Folsom","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCOGSQ","S":2022,"En":"CO Mountain Qualifier","Ev":"Glenwood Springs High School","Ea":"1521 Grand Ave","Ec":"Glenwood Springs","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USDEWIS3","S":2022,"En":"DE FTC Meet at Padua","Ev":"Padua Academy","Ea":"905 N. Broom St.","Ec":"Wilmington","Es":"DE","Ect":"USA","Dn":"Delaware","Sd":"2023-01-24T00:00:00","Ed":"2023-01-24T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLSPLT","S":2022,"En":"FL Space Coast League Tournament","Ev":"Hagerty High School","Ea":"3225 Lockwood Blvd","Ec":"Oviedo","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USFLFLACLT","S":2022,"En":"FL AeroCoast League Tournament","Ev":"Northwood Elementary School","Ea":"501 4th Avenue E","Ec":"Crestview","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USGAWESTLT","S":2022,"En":"GA West Georgia League Tournament","Ev":"Milton High School","Ea":"13025 Birmingham Hwy","Ec":"Milton","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USIACHLT","S":2022,"En":"IA Chemical League Tournament","Ev":"Creighton Prep High School","Ea":"7400 Western Ave","Ec":"Omaha","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USIAGELT","S":2022,"En":"IA Geothermal League Tournament","Ev":"Clear Creek Middle School","Ea":"311 W. Marengo Rd","Ec":"Tiffin","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USILCMM3C","S":2022,"En":"IL Chicago Meet 3C","Ev":"Truman CCC","Ea":"1145 W Wilson Ave.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USILCSNELT","S":2022,"En":"IL Suburban Northeast League Tournament at Grainger","Ev":"Grainger","Ea":"100 Grainger Parkway","Ec":"Lake Forest","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USINNWLT","S":2022,"En":"IN FIN Northwest League Tournament","Ev":"Hammond Central High School","Ea":"5926 Calumet Ave","Ec":"Hammond","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USKYKYM1","S":2022,"En":"KY Beaker Meet #2","Ev":"Morehead State University","Ea":"150 University Blvd","Ec":"Morehead","Es":"KY","Ect":"USA","Dn":"Kentucky","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCHSUBQ","S":2022,"En":"CHS-MD Union Bridge Qualifier","Ev":"Francis Scott Key High School","Ea":"3825 Bark Hill Road","Ec":"Union Bridge","Es":"MD","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSSTLNLT","S":2022,"En":"MOKS-MO STL North League Tournament","Ev":"Hazelwood Central High School","Ea":"15875 New Halls Ferry Road","Ec":"Florissant","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMOKSSWMILT1","S":2022,"En":"MOKS-MO SW Mid MO League Tournament","Ev":"O\u0027Reilly Family Event Center","Ea":"935 N Summit Ave","Ec":"Springfield","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMSBIQ5","S":2022,"En":"MS Biloxi Qualifier","Ev":"St. Patrick\u0027s Catholic School","Ea":"18300 Hwy 67","Ec":"Biloxi","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNCELQ","S":2022,"En":"NC FTC Western MS","Ev":"Western Middle School","Ea":"2100 Eldon Dr","Ec":"Elon","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USNCSAQ","S":2022,"En":"NC FTC Ascend Leadership Academy","Ev":"Ascend Leadership Academy","Ea":"283 Harvey Faulk Rd","Ec":"Sanford","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USNCGRQ","S":2022,"En":"NC Hope Middle School","Ev":"Hope Middle School","Ea":"2995 Mills Rd","Ec":"Greenville","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USNHEXQ","S":2022,"En":"NH Phillips Exeter Academy Qualifier #3","Ev":"Phillips Exeter Academy","Ea":"20 Main St, Exeter, NH 03833","Ec":"Exeter","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNJNEM6","S":2022,"En":"NJ 0129-P3  Northeast Edge League Meet (Sunday)","Ev":"Livingston High School","Ea":"30 Robert Harp Dr","Ec":"Livingston High School","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNJSOM6","S":2022,"En":"NJ 0128-P3  Southern League Meet (Saturday)","Ev":"Stuart County Day School Of the Sacred Heart","Ea":"1200 Stuart RD","Ec":"Princeton","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USNMCMP","S":2022,"En":"New Mexico Regional Championship","Ev":"Raymond Sarracino Middle School","Ea":"1425 El Camino Real St.","Ec":"Socorro","Es":"NM","Ect":"USA","Dn":"New Mexico","Sd":"2023-01-27T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNVNOM5N","S":2022,"En":"NV Northern League Meet # 5N","Ev":"Truckee Meadows Community College - Dandini Campus","Ea":"7000 Dandini Blvd","Ec":"Reno","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNVSOM6S","S":2022,"En":"NV Southern League Meet # 6S","Ev":"Cannon Middle School","Ea":"5850 Euclid St","Ec":"Las Vegas","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNVSOM5S","S":2022,"En":"NV Southern League Meet # 5S","Ev":"Cannon Middle School","Ea":"5850 Euclid St","Ec":"Las Vegas","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1000},{"Tc":"USNYEXBRQ","S":2022,"En":"NY-Excelsior Broadalbin-Perth Qualifier","Ev":"Broadalbin-Perth Jr/Sr High School","Ea":"100 Bridge St","Ec":"Broadalbin","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYLILVQ","S":2022,"En":"NY-Long Island Qualifier #3","Ev":"Locust Valley High School","Ea":"99 Horse Hollow Road","Ec":"Locust Valley","Es":"NY","Ect":"USA","Dn":"New York - Long Island","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHVWQ","S":2022,"En":"OH Van Wert Qualifier","Ev":"Van Wert High School","Ea":"10708 State Rt 118 South","Ec":"Van Wert","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-01-27T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1004},{"Tc":"USOHCIQ","S":2022,"En":"OH Walnut Hills Qualifier","Ev":"Walnut Hills High School","Ea":"3250 Victory Pkwy","Ec":"Cincinnati","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-01-27T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USORSFLT","S":2022,"En":"OR Silicon Forest League Tournament","Ev":"Hillsboro High School","Ea":"3285 SE Rood Bridge Rd","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USORPAQ","S":2022,"En":"OR Hillsboro Qualifying Tournament","Ev":"Hillsboro HS","Ea":"3285 SE Rood Bridge Road","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USORUMQ","S":2022,"En":"OR Umatilla Qualifying Tournament","Ev":"TBD","Ea":"TBD","Ec":"Umatilla","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USSCHAS3","S":2022,"En":"SC PeeDee Scrimmage 3","Ev":"Governor\u0027s School for Science and Math","Ea":"401 Railroad Ave","Ec":"Hartsville","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXWPLBM3","S":2022,"En":"TX-W\u0026P Lubbock-B League Meet #3","Ev":"Frenship High School Student Center","Ea":"902 Dowden Rd","Ec":"Wolfforth","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPMDLT","S":2022,"En":"TX-W\u0026P Midland League Tournament","Ev":"Bush Convention Center","Ea":"105 N Main St","Ec":"Midland","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXCEXSTLT1","S":2022,"En":"TX-Central X-STREAM League Tournament","Ev":"Kipp Collegiate HS","Ea":"8004 Cameron Road","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXCEGCLT","S":2022,"En":"TX-Central Gulf Coast League Tournament","Ev":"Texas A\u0026M University - Corpus Christi","Ea":"6300 Ocean Drive","Ec":"Corpus Christi","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOELM2","S":2022,"En":"TX-Houston East League Meet 2","Ev":"Mickey Leland College Prep.","Ea":"1700 Gregg St","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXSOTELT","S":2022,"En":"TX-South Tesla League Tournament","Ev":"Harmony School of Excellence (Laredo)","Ea":"4401B San Francisco Ave.","Ec":"Laredo","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXCEKWLT1","S":2022,"En":"TX-Central Kwolek League Tournament","Ev":"Judson Middle School","Ea":"9695 Schaefer Rd","Ec":"Converse","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-27T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXCE90STLT","S":2022,"En":"TX-Central 90 SSTallions League Tournament","Ev":"School of Science \u0026 Technology - San Antonio","Ea":"4410 David Edwards Dr.","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-27T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXNODULT1","S":2022,"En":"TX-North D\u0026U Tournament","Ev":"Woodrow Wilson HS","Ea":"100 S Glasgow Dr, Dallas, TX 75214","Ec":"Dallas, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXCEGMLT","S":2022,"En":"TX-Central GEMS League Tournament","Ev":"Westwood High School","Ea":"12400 Mellow Meadow Dr","Ec":"Austin","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHONEM3","S":2022,"En":"TX-Houston Northeast League Meet 3","Ev":"Livingston High School","Ea":"400 FM 350 South","Ec":"Livingston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USCHSNOQ","S":2022,"En":"VA Norfolk Qualifier","Ev":"Norfolk State University / Gill Gymnasium","Ea":"700 Park Ave","Ec":"Norfolk","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSHEQ","S":2022,"En":"CHS-VA Herndon Qualifier","Ev":"Herndon High School","Ea":"700 Bennett St","Ec":"Herndon","Es":"VA","Ect":"USA","Dn":"Chesapeake","Sd":"2023-01-29T00:00:00","Ed":"2023-01-29T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USWACMP","S":2022,"En":"Washington State Championship","Ev":"Amazon Doppler Building","Ea":"2021 7th Ave","Ec":"Seattle","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USWIHAQ","S":2022,"En":"WI Knack Attack","Ev":"Lake Country Lutheran High School","Ea":"1800 Vettelson Rd","Ec":"Hartland","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 01/30/2023","Ws":"2023-01-30T00:00:00","We":"2023-02-05T23:59:59","Wn":21,"Ec":64,"E":[{"Tc":"CAABABNALT","S":2022,"En":"Alberta Northern Championship","Ev":"Bev Facey Community High School","Ea":"99 Colwill Blvd","Ec":"Sherwood Park","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2023-02-04T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1001},{"Tc":"ILSHS3","S":2022,"En":"Israel Scrimmage #3","Ev":"Omarim Regional School","Ea":"Ein HaShofet","Ec":"Megido","Es":"Z","Ect":"Israel","Dn":"Israel","Sd":"2023-01-30T00:00:00","Ed":"2023-01-30T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://isrlive.firstisrael.org.il","eventType":0},{"Tc":"LYALQ","S":2022,"En":"LY Tripoli Qualifying Competition","Ev":"Mukthat School Venue","Ea":"Alseraj area","Ec":"Alseraj","Es":"TB","Ect":"Libya","Dn":"Libya","Sd":"2023-02-03T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"KRCMP","S":2022,"En":"Korea Robot Championship","Ev":"Daejeon Convention Center","Ea":"107 Expo-ro, Yuseong-gu","Ec":"Daejeon","Es":"30","Ect":"South Korea","Dn":"South Korea","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USALHUS3","S":2022,"En":"AL Scrimmage #3","Ev":"UAH Conference Training Center","Ea":"1410 Ben Graves Dr NW","Ec":"Huntsville","Es":"AL","Ect":"USA","Dn":"Alabama","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"n/a","eventType":0},{"Tc":"USAZWAQ","S":2022,"En":"AZ Desert Vista - Waddell Qualifier","Ev":"Canyon View High School","Ea":"6024 N. Perryville Rd.","Ec":"Waddell","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1004},{"Tc":"USCALAROQ1","S":2022,"En":"CA-SoCal ILT 1 -Romoland Saturday","Ev":"Heritage High School","Ea":"26001 Briggs Rd","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USCANOSJQ","S":2022,"En":"CA-NorCal San Jose #4 Qualifying Tournament","Ev":"The Play Space","Ea":"2215 Old Oakland Road, Suite B","Ec":"San Jose","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-02-05T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCALAROQ2","S":2022,"En":"CA-SoCal ILT 2 - Romoland Sunday","Ev":"Heritage High School","Ea":"26001 Briggs Rd","Ec":"Romoland","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-02-05T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1004},{"Tc":"USCANOPNLT","S":2022,"En":"CA-NorCal Peninsula League Tournament","Ev":"Jefferson High School","Ea":"6996 Mission Street","Ec":"Daly City","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCOLIQ","S":2022,"En":"CO Southwest Metro Qualifier","Ev":"Chatfield Senior High School","Ea":"7227 S. Simms Street","Ec":"Littleton","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCTWIQ","S":2022,"En":"CT Windsor Qualifier","Ev":"Sage Park Middle School","Ea":"25 Sage Park Rd","Ec":"Windsor","Es":"CT","Ect":"USA","Dn":"Connecticut","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://twitch.tv/ctftc","eventType":1004},{"Tc":"USDEDOS","S":2022,"En":"DE FTC Meet at DSU","Ev":"Wentworth Gymnasium","Ea":"120 N. State St.","Ec":"Dover","Es":"DE","Ect":"USA","Dn":"Delaware","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USFLFLSFLT","S":2022,"En":"FL South Florida League Tournament","Ev":"St. Thomas Aquinas High School","Ea":"2801 SW 12th St.","Ec":"Fort Lauderdale","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USFLFLNELT","S":2022,"En":"FL North East League Tournament","Ev":"Bolles Bartram Campus","Ea":"2264 Bartram Road","Ec":"Jacksonville","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USFLFLOCLT","S":2022,"En":"FL ONECLAY League Tournament","Ev":"Orange Park High School","Ea":"2300 Kingsley Ave","Ec":"Orange Park","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USFLFLROLT","S":2022,"En":"FL ROBOT League Tournament","Ev":"Mckeel Academy of Science \u0026 Technology Gym","Ea":"1810 West Parker Street","Ec":"Lakeland","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USFLFLGCLT","S":2022,"En":"FL Gulf Coast League Tournament","Ev":"State College of Florida","Ea":"5840 26th St W","Ec":"Bradenton","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USFLFLOLLT","S":2022,"En":"FL Orlando Robotics League Tournament","Ev":"Lake Highland Preparatory School","Ea":"741 N Mills Ave","Ec":"Orlando","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USGANELT","S":2022,"En":"GA Northeast Georgia League Tournament","Ev":"Empower College and Career Center","Ea":"1952 Winder Hwy","Ec":"Jefferson","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USIDPFS5","S":2022,"En":"ID North Idaho Scrimmage #5","Ev":"4-H University of Idaho Research Park","Ea":"721 S. Lochsa Street","Ec":"Post Falls","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USILCSNWLT","S":2022,"En":"IL Suburban Northwest League Tournament","Ev":"Guilford High School","Ea":"5620 Spring Creek Rd","Ec":"Rockford","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USILCMLTA","S":2022,"En":"IL Chicago League Tournament A","Ev":"Leo HS","Ea":"7901 S Sangamon St.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USILPWLT","S":2022,"En":"IL Peoria Western League Tournament","Ev":"Manual High School","Ea":"811 S Griswold St","Ec":"Peoria","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USILCSSLT","S":2022,"En":"IL Suburban South League Tournament","Ev":"Rotolo Middle School","Ea":"1501 S Raddant Rd","Ec":"Batavia","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USINNCLT","S":2022,"En":"IN FIN North-Central League Tournament","Ev":"Success Academy","Ea":"3408 Ardmore Trail","Ec":"South Bend","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USLAALQ","S":2022,"En":"LA Qualifier 3","Ev":"Holy Savior Menard Central High School","Ea":"4603 Coliseum Blvd #3518","Ec":"Alexandira","Es":"LA","Ect":"USA","Dn":"Louisiana","Sd":"2023-02-03T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMANEQ","S":2022,"En":"MA Rocket Rumble 4.1","Ev":"Needham High School","Ea":"609 Webster Street","Ec":"Needham","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMANEQ2","S":2022,"En":"MA Rocket Rumble 4.2","Ev":"Needham High School","Ea":"609 Webster Street","Ec":"Needham","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-02-05T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSPOQ","S":2022,"En":"CHS-MD Potomac Qualifier","Ev":"The Bullis School","Ea":"10601 Falls Road","Ec":"Potomac","Es":"MD","Ect":"USA","Dn":"Chesapeake","Sd":"2023-02-05T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSKCELT","S":2022,"En":"MOKS-MO KC East League Tournament","Ev":"MCC - Penn Valley","Ea":"3201 SW  Trafficway","Ec":"Kansas City","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMOKSSTLSLT","S":2022,"En":"MOKS-MO STL South League Tournament","Ev":"Fox High School","Ea":"751 Jeffco Blvd","Ec":"Arnold","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMTCMP","S":2022,"En":"Montana Regional Championship","Ev":"Montana State Shroyer Gym","Ea":"1 Bobcat Cir","Ec":"Bozeman","Es":"MT","Ect":"USA","Dn":"Montana","Sd":"2023-02-02T00:00:00","Ed":"2023-02-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNCWSQ","S":2022,"En":"NC FTC Salem Academy and College","Ev":"Salem Academy and College","Ea":"601 S Church St","Ec":"Winston-Salem","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USNCASQ","S":2022,"En":"NC FTC Asheville School","Ev":"Asheville School","Ea":"360 Asheville School Rd","Ec":"Asheville","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USNDCMP","S":2022,"En":"North Dakota State Championships","Ev":"Bismarck Career Academy","Ea":"1221 College Drive","Ec":"Bismarck","Es":"ND","Ect":"USA","Dn":"North Dakota","Sd":"2023-01-30T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USIATBSQ","S":2022,"En":"IA Western Iowa Super Qualifier","Ev":"Metro Community College","Ea":"CAET Building, Building 24","Ec":"Omaha","Es":"NE","Ect":"USA","Dn":"Iowa","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USNHHUQ","S":2022,"En":"NH Alvirne Qualifier #4","Ev":"Alvirne High School","Ea":"200 Derry Rd, Hudson, NH 03051","Ec":"Hudson","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2023-02-05T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNJNELT","S":2022,"En":"NJ 0205 Northeast Conference; Northeast Edge League Tournament","Ev":"Bayonne High School","Ea":"669 Ave \u0022A\u0022","Ec":"Bayonne","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-02-05T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USNJUCLT","S":2022,"En":"NJ 0204 Morris County Conference; Upper Central League Tournament","Ev":"Delbarton School","Ea":"230 Mendham Road","Ec":"Morristown","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USNYNYBRQ7","S":2022,"En":"NY-NYC Qualifier 7","Ev":"Brooklyn Poly Prep","Ea":"1 Poly Prep Drive","Ec":"Brooklyn","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYNYBRQ8","S":2022,"En":"NY-NYC Qualifier 8","Ev":"Brooklyn Poly Prep","Ea":"1 Poly Prep Drive","Ec":"Brooklyn","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2023-02-05T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYEXPOQ","S":2022,"En":"NY-Excelsior Clarkson University Qualifier","Ev":"Clarkson University - Cheel Campus Center","Ea":"8 Clarkson Ave","Ec":"Potsdam","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHKEQ","S":2022,"En":"OH Kent State University Qualifier","Ev":"Kent State University Student Center","Ea":"1075 Risman Dr","Ec":"Kent","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-02-03T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHWAQ","S":2022,"En":"OH Wapakoneta Qualifier","Ev":"Wapakoneta High School","Ea":"1 Redskin Trail","Ec":"Wapakoneta","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-02-02T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1004},{"Tc":"USOKOKLALT2","S":2022,"En":"OK Oklahoma West","Ev":"Mustang High School","Ea":"801 S Snyder Dr","Ec":"Mustang","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-02-03T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USORSOLT","S":2022,"En":"OR SOAR League Tournament","Ev":"Roseburg High School","Ea":"400 Harvard Ave","Ec":"Roseburg","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USORWIQ","S":2022,"En":"OR Wilsonville Qualifying Tournament","Ev":"Meridian Creek MS","Ea":"6300 SW Hazel St","Ec":"Wilsonville","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USPAPHQ","S":2022,"En":"PA Philadelphia Qualifier","Ev":"Central High School","Ea":"1700 West Olney Ave","Ec":"Philadelphia","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USSCFIQ","S":2022,"En":"SC West Qualifying Tournament","Ev":"Fountain Inn High School","Ea":"644 Quillen Avenue","Ec":"Fountain Inn","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USTXCEBUSQ","S":2022,"En":"TX-Central Semi-Regional North","Ev":"Johnson High School","Ea":"4260 RANCH RD 967","Ec":"Buda","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USTXWPEPLT","S":2022,"En":"TX-W\u0026P El Paso League Tournament","Ev":"UTEP Campus - Memorial Gym","Ea":"101 W Robinson Ave","Ec":"El Paso","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOWLM3","S":2022,"En":"TX-Houston West League Meet 3","Ev":"Hogg Middle School","Ea":"1100 Merrill St.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPLALTA","S":2022,"En":"TX-W\u0026P Lubbock-A League Tournament","Ev":"Lubbock High School","Ea":"2004 19th St","Ec":"Lubbock","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOSWM3","S":2022,"En":"TX- Houston Soutwest League Meet 3","Ev":"Harmony School of Innovation - Sugar Land","Ea":"13738 Old Richmond Rd","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOCLM2","S":2022,"En":"TX-Houston Central League Meet 2","Ev":"Hogg Middle School","Ea":"1100 Merrill St.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOCLM3","S":2022,"En":"TX-Houston Central League Meet 3","Ev":"Hogg Middle School","Ea":"1100 Merrill St.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOSWM1","S":2022,"En":"TX-Houston Southwest League Meet 2","Ev":"Harmony School of Innovation - Sugar Land","Ea":"13738 Old Richmond Rd","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHONLM3","S":2022,"En":"TX-Houston North League Meet 3","Ev":"Brabham Middle School","Ea":"10000 Fm 830 Rd.","Ec":"Willis","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXNOXMLLT","S":2022,"En":"TX-North X^2 Tournament","Ev":"Roboplex at Marcus HS, LISD","Ea":"5707 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOWLM1","S":2022,"En":"TX-Houston West League Meet 2","Ev":"Hogg Middle School","Ea":"1100 Merrill St.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXHOSLLT1","S":2022,"En":"TX-Houston South League TOURNAMENT","Ev":"Palacios High School","Ea":"100 Shark Dr","Ec":"Palacios","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOSELM3","S":2022,"En":"TX-Houston SE Meet 3","Ev":"Lutheran South Academy","Ea":"12555 Ryewater Dr.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USUTHUQ","S":2022,"En":"UT Hurricane High School Qualifier","Ev":"Hurricane High School","Ea":"345 Tiger Blvd","Ec":"Hurricane","Es":"UT","Ect":"USA","Dn":"Utah","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 02/06/2023","Ws":"2023-02-06T00:00:00","We":"2023-02-12T23:59:59","Wn":22,"Ec":48,"E":[{"Tc":"BRBHS","S":2022,"En":"BR FTC - Amistoso Minas Gerais","Ev":"FIEMG","Ea":"FIEMG","Ec":"Belo Horizonte","Es":"MG","Ect":"Brazil","Dn":"Brazil","Sd":"2023-02-11T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"CAABABSALT","S":2022,"En":"Alberta Southern Championship","Ev":"Nelson Mandela High School","Ea":"45 Saddletowne Cir NE","Ec":"Calgary","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2023-02-11T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1001},{"Tc":"CNSHQ2","S":2022,"En":"CN China FTC Qualifier #1","Ev":"Remote Event","Ea":"Remote Event","Ec":"Shanghai","Es":"SH","Ect":"China","Dn":"China","Sd":"2023-02-06T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"TWCMP","S":2022,"En":"TW National Championship Event","Ev":"National Science and Technology Museum","Ea":"No. 720, Jiou Ru 1st Rd.,Sanminm Dist.","Ec":"Kaohsiung City","Es":"KHH","Ect":"Chinese Taipei","Dn":"Chinese Taipei","Sd":"2023-02-09T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"ILCMP","S":2022,"En":"Israel Championship","Ev":"HaKiriya Arena","Ea":"60 HaAtzma\u0027ut Street","Ec":"Ashdod","Es":"D","Ect":"Israel","Dn":"Israel","Sd":"2023-02-11T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://ftc-live.firstisrael.org.il","eventType":1010},{"Tc":"LYGHQ","S":2022,"En":"LY Gheryan Qualifying Competition","Ev":"Gheryan sports city venue","Ea":"Tripoli, Libya 218945798487","Ec":"Gheryan","Es":"JG","Ect":"Libya","Dn":"Libya","Sd":"2023-02-10T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"NLNLLT","S":2022,"En":"Netherlands FTC Benelux Championship","Ev":"SintLucas","Ea":"Torenallee 75","Ec":"Eindhoven","Es":"NB","Ect":"Netherlands","Dn":"Netherlands","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/ftcnetherlands","eventType":1010},{"Tc":"USARSPS1","S":2022,"En":"AR Shiloh Scrimmage","Ev":"Shiloh Christian School","Ea":"1707 Johnson Rd","Ec":"Springdale","Es":"AR","Ect":"USA","Dn":"Arkansas","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USAZSVS","S":2022,"En":"AZ Champs Warmup Scrimmage","Ev":"San Tan Foothills High School","Ea":"1255 W. Silverdale Rd.","Ec":"San Tan Valley","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USCASDSDGALT","S":2022,"En":"CA- San Diego Gauss League Champ, Classical Academy","Ev":"Classical Academy","Ea":"130 Woodward Ave","Ec":"Escondido","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-02-12T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCASDSDEULT","S":2022,"En":"CA- San Diego Euclid League Champ, Patrick Henry","Ev":"Patrick Henry High School","Ea":"6702 Wandermere Dr","Ec":"San Diego","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCASDSDDELT","S":2022,"En":"CA- San Diego Descartes League Champ, TCCS","Ev":"Tri-City Christian School","Ea":"302 Emerald Dr","Ec":"Vista","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCANOSBLT","S":2022,"En":"CA-NorCal South Bay Metro League Tournament","Ev":"The King\u0027s Academy","Ea":"562 N Britton Ave","Ec":"Sunnyvale","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCASDSDTULT","S":2022,"En":"CA- San Diego Turing League Champ, Sage Creek","Ev":"Sage Creek High School","Ea":"3900 Cannon Rd","Ec":"Carlsbad","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCTSOQ","S":2022,"En":"CT Southington Qualifier","Ev":"Joseph A DePaolo Middle School","Ea":"385 Pleasant St","Ec":"Southington","Es":"CT","Ect":"USA","Dn":"Connecticut","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://twitch.tv/ctftc","eventType":1004},{"Tc":"USDEWIS","S":2022,"En":"DE FTC Meet at Wilmington Friends","Ev":"Wilmington Friends School","Ea":"101 School Road","Ec":"Wilmington","Es":"DE","Ect":"USA","Dn":"Delaware","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USIANOSQ","S":2022,"En":"IA Central Iowa Super Qualifier","Ev":"Lakewood Elementary","Ea":"9210 Happy Hollow Dr","Ec":"Norwalk","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://youtu.be/_02vKPUsJUA","eventType":1007},{"Tc":"USILSCLT","S":2022,"En":"IL Central Southern League Tournament","Ev":"Maryville Christian High School","Ea":"7110 State Route 162","Ec":"Maryville","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USILCMLTB","S":2022,"En":"IL Chicago League Tournament B","Ev":"Francis W. Parker School","Ea":"330 W Webster Ave.","Ec":"Chicago","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USINSLLT","S":2022,"En":"IN FIN South League Tournament","Ev":"Westgate @ Crane","Ea":"13598 East WestGate Dr","Ec":"Odon","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMOKSKCWLT","S":2022,"En":"MOKS-KS KC West League Tournament","Ev":"Mill Valley High School","Ea":"5900 Monticello Rd","Ec":"Shawnee","Es":"KS","Ect":"USA","Dn":"Missouri","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USKYCMP","S":2022,"En":"Kentucky State Championship","Ev":"University of Kentucky - Gatton Student Center","Ea":"160 Avenue of Champions","Ec":"Lexington","Es":"KY","Ect":"USA","Dn":"Kentucky","Sd":"2023-02-09T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMAANQ2","S":2022,"En":"MA Robostorm 8.2","Ev":"Andover High School","Ea":"80 Shawsheen Road","Ec":"Andover","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-02-12T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMAANQ","S":2022,"En":"MA Robostorm 8.1","Ev":"Andover High School","Ea":"80 Shawsheen Road","Ec":"Andover","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USCHSCMP","S":2022,"En":"Chesapeake FTC Championship","Ev":"Archbishop Spalding High School","Ea":"8080 New Cut Rd","Ec":"Severn","Es":"MD","Ect":"USA","Dn":"Chesapeake","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMNCMP","S":2022,"En":"Minnesota FTC State Championship","Ev":"Saint Paul RiverCentre","Ea":"175 Kellogg Blvd. W.","Ec":"St. Paul","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2023-02-10T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMOKSSTLMLT","S":2022,"En":"MOKS-MO STL Mid League Tournament","Ev":"Rockwood Valley Middle School","Ea":"1220 Babler Park Dr","Ec":"Wildwood","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USMSLAQ6","S":2022,"En":"MS Laurel Qualifier","Ev":"Laurel Christian School","Ea":"1200 Highway 15","Ec":"Laurel","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNJSOLT","S":2022,"En":"NJ 0212 Upper South Conference; Southern League Tournament","Ev":"Highstown High School","Ea":"25 Leshin Lane","Ec":"Highstown","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-02-12T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USNJNOLT","S":2022,"En":"NJ 0211 Far North Conference; Northern League Tournament","Ev":"Glen Rock High School","Ea":"400 Hamilton Ave.","Ec":"Glen Rock","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USNVSOLT","S":2022,"En":"NV Southern League Tournament","Ev":"Sunrise Mountain High School","Ea":"2575 Los Feliz St","Ec":"Las Vegas","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-02-10T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1001},{"Tc":"USNVNOLT","S":2022,"En":"NV Northern League Tournament","Ev":"McQueen High School","Ea":"6055 Lancer St","Ec":"Reno","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-02-10T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1001},{"Tc":"USNYNYNYSQ2","S":2022,"En":"NY-NYC Super Qualifier 2","Ev":"John Dewey High School","Ea":"50 Avenue X","Ec":"Brooklyn","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2023-02-12T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USNYLISBQ4","S":2022,"En":"*** SUSPENDED *** NY-Long Island Qualifier #4","Ev":"The Stony Brook School","Ea":"1 Chapman Parkway","Ec":"Stony Brook","Es":"NY","Ect":"USA","Dn":"New York - Long Island","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYNYNYSQ","S":2022,"En":"NY-NYC Super Qualifier 1","Ev":"John Dewey High School","Ea":"50 Avenue X","Ec":"Brooklyn","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USOKOKLALT","S":2022,"En":"OK Oklahoma East","Ev":"Bishop Kelley","Ea":"3905 S Hudson Ave","Ec":"Tulsa","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-02-10T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USORCBLT","S":2022,"En":"OR Columbia Basin League Tournament","Ev":"Pendleton High School","Ea":"1800 NW Carden Ave","Ec":"Pendleton","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USORPOSQ","S":2022,"En":"OR Second Chance Qualifying Tournament","Ev":"University of Portland","Ea":"5000 N Willamette Blvd","Ec":"Portland","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-11T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USPALAQ","S":2022,"En":"PA Red Tornado Qualifier","Ev":"McCaskey East High School","Ea":"1051 Lehigh Avenue","Ec":"Lancaster","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USSCCHQ","S":2022,"En":"SC East Qualifying Tournament","Ev":"Phillip Simmons High School","Ea":"3080 River Village Crossing Dr.","Ec":"Charleston","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USTXNOLTSQ","S":2022,"En":"TX-North Semi-Regional NORTH","Ev":"Hedrick Middle School, LISD","Ea":"1526 Bellaire Blvd, Lewisville, TX 75067","Ec":"Lewisville, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USTXWPAMLT","S":2022,"En":"TX-W\u0026P Amarillo League Tournament","Ev":"AmTech Career Academy","Ea":"3601 Plains Blvd","Ec":"Amarillo","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHONELT1","S":2022,"En":"TX-Houston Northeast League Tournament","Ev":"Livingston High School","Ea":"400 FM 350 South","Ec":"Livingston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-05T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOELM3","S":2022,"En":"TX-Houston East League Meet 3","Ev":"Mickey Leland College Prep.","Ea":"1700 Gregg St","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1000},{"Tc":"USTXWPLBLT","S":2022,"En":"TX-W\u0026P Lubbock-B League Tournament","Ev":"Lubbock-Cooper Middle School","Ea":"16310 TX-493 Loop","Ec":"Lubbock","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USUTSJQ","S":2022,"En":"UT American Academy of Innovation Qualifier","Ev":"Amercain Academy of Innovation","Ea":"5410 S Jordan Pkwy","Ec":"South Jordan","Es":"UT","Ect":"USA","Dn":"Utah","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USVTCMP","S":2022,"En":"Vermont FTC Championship","Ev":"Champlain Valley Union High School","Ea":"369 CVU Road","Ec":"Hinesburg","Es":"VT","Ect":"USA","Dn":"Vermont","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USWIBRQ","S":2022,"En":"WI Battle In Brookfield","Ev":"Brookfield Central High School","Ea":"16900 Gebhardt Rd","Ec":"Brookfield","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 02/13/2023","Ws":"2023-02-13T00:00:00","We":"2023-02-19T23:59:59","Wn":23,"Ec":38,"E":[{"Tc":"BRNHS","S":2022,"En":"BR FTC - Sinos Valley Challenge","Ev":"Universidade Vale dos Sinos","Ea":"Universidade Vale dos Sinos","Ec":"Novo Hamburgo","Es":"RS","Ect":"Brazil","Dn":"Brazil","Sd":"2023-02-15T00:00:00","Ed":"2023-02-16T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"CNSHQ","S":2022,"En":"CN China FTC Qualifier #2","Ev":"Remote Event","Ea":"Remote Event","Ec":"Shanghai","Es":"SH","Ect":"China","Dn":"China","Sd":"2023-02-13T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"CNSHQ3","S":2022,"En":"CN China FTC Qualifier #3","Ev":"Remote Event","Ea":"Remote Event","Ec":"Shanghai","Es":"SH","Ect":"China","Dn":"China","Sd":"2023-02-13T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"LYTRQ","S":2022,"En":"LY Sabha Qualifying Competition","Ev":"Tamanhent Venue","Ea":"Sabha","Ec":"Tripoli","Es":"SB","Ect":"Libya","Dn":"Libya","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"MXCMP","S":2022,"En":"MX POWER PLAY Campeonato Nacional FTC M\u00E9xico (CDMX)","Ev":"ITAM Campus R\u00EDo Hondo","Ea":"R\u00EDo Hondo 1, Altavista, \u00C1lvaro Obreg\u00F3n, 01080 Ciudad de M\u00E9xico, CDMX","Ec":"Ciudad de M\u00E9xico","Es":"CMX","Ect":"Mexico","Dn":"Mexico","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"NGABQ","S":2022,"En":"NG Regional FIRST Tech Challenge","Ev":"National Stadium","Ea":"Constitution Ave, Kukwaba 900211, Abuja, Federal Capital Territory","Ec":"Abuja","Es":"FC","Ect":"Nigeria","Dn":"Nigeria","Sd":"2023-02-12T00:00:00","Ed":"2023-02-13T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"ROBUQ2","S":2022,"En":"RO BUCHAREST #2 - FTC ROMANIA QUALIFYING TOURNAMENT","Ev":"Universitatea POLITEHNICA din BUCURESTI","Ea":"Splaiul Independen\u021Bei 313, Bucure\u0219ti","Ec":"Bucuresti","Es":"B","Ect":"Romania","Dn":"Romania","Sd":"2023-02-17T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.youtube.com/@NatieprinEducatie","eventType":1004},{"Tc":"ROBUQ1","S":2022,"En":"RO BUCHAREST #1 - FTC Romania Qualifying Tournament","Ev":"Universitatea POLITEHNICA din BUCURESTI","Ea":"Splaiul Independen\u021Bei 313, Bucure\u0219ti","Ec":"Bucuresti","Es":"B","Ect":"Romania","Dn":"Romania","Sd":"2023-02-13T00:00:00","Ed":"2023-02-15T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.youtube.com/@NatieprinEducatie","eventType":1004},{"Tc":"USCALAMOQ2","S":2022,"En":"CA-SoCal ILT 4 - Monrovia Sunday","Ev":"Monrovia High School","Ea":"845 W Colorado Blvd","Ec":"Monrovia","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-02-19T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USCALAMOQ1","S":2022,"En":"CA-SoCal ILT 3- Monrovia Saturday","Ev":"Monrovia High School","Ea":"845 W Colorado Blvd","Ec":"Monrovia","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USCOCMP","S":2022,"En":"Colorado State Championship 2022-2023","Ev":"Colorado State University","Ea":"200 W. Lake Street","Ec":"Ft. Collins","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USCTCMP","S":2022,"En":"Connecticut State Championship","Ev":"Wolcott High School","Ea":"457 Bound Line Rd","Ec":"Wolcott","Es":"CT","Ect":"USA","Dn":"Connecticut","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://twitch.tv/ctftc","eventType":1010},{"Tc":"USIABESQ","S":2022,"En":"IA Eastern Iowa Super Qualifier","Ev":"Bettendorf High School","Ea":"3333 18th St","Ec":"Bettendorf","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USLAHAQ4","S":2022,"En":"LA Qualifier 4","Ev":"Hammond High Magnet School","Ea":"45168 River Road","Ec":"Hammond","Es":"LA","Ect":"USA","Dn":"Louisiana","Sd":"2023-02-17T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMACAQ","S":2022,"En":"MA Gears on the Loose","Ev":"Canton High School","Ea":"960 Washington Street","Ec":"Canton","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMACAQ2","S":2022,"En":"MA Who Let the Bots Out","Ev":"Canton High School","Ea":"960 Washington Street","Ec":"Canton","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-02-19T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USMOKSSELT","S":2022,"En":"MOKS-MO SE League Tournament","Ev":"Jackson High School","Ea":"315 S Missouri St","Ec":"Jackson","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USNCCMP","S":2022,"En":"North Carolina FTC State Championship","Ev":"Southern Guilford High School","Ea":"5700 Drake Rd","Ec":"Greensboro","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1010},{"Tc":"USNHCMP","S":2022,"En":"New Hampshire State Championship","Ev":"NHTI (New Hampshire Technical Institute)","Ea":"31 College Dr, Concord, NH 03301","Ec":"Concord","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNJNELT2","S":2022,"En":"NJ 0218 South Essex Conference; Northeast Edge League Tournament","Ev":"Payne Tech","Ea":"498 Market St.","Ec":"Newark","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USNJUCLT2","S":2022,"En":"NJ 0219 Central Conference; Upper Central League Tournament","Ev":"Kean University","Ea":"1000 Morris Ave","Ec":"Union","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-02-19T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USNYLIREQ","S":2022,"En":"New York - Long Island Qualifier #4 - REMOTE","Ev":"Remote Event","Ea":"Remote Event","Ec":"Oyster Bay ","Es":"NY","Ect":"USA","Dn":"New York - Long Island","Sd":"2023-02-13T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USNYEXHJQ","S":2022,"En":"NY-Excelsior John Jay Qualifier","Ev":"John Jay High School","Ea":"2012 NY Rt 52","Ec":"Hopewell Junction","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USOHSYQ","S":2022,"En":"OH Sylvania STEM Center Qualifier","Ev":"Timberstone Junior High School","Ea":"9000 W Sylvania Ave","Ec":"Sylvania","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USPAEMQ2","S":2022,"En":"PA Green and Gold Qualifier","Ev":"Emmaus High School","Ea":"800 Pine Street","Ec":"Emmaus","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-02-19T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USPAEMQ1","S":2022,"En":"PA Lehigh Valley Qualifier","Ev":"Emmaus High School","Ea":"800 Pine Street","Ec":"Emmaus","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1004},{"Tc":"USTNCMP","S":2022,"En":"Tennessee State Championship","Ev":"MTSU Alumni Memorial Gym","Ea":"2610 Middle Tennessee Blvd","Ec":"Murfreesboro","Es":"TN","Ect":"USA","Dn":"Tennessee","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USTXHOELLT1","S":2022,"En":"TX-Houston East League Tournament","Ev":"Mickey Leland College Prep.","Ea":"1700 Gregg St","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOSELLT1","S":2022,"En":"TX-Houston SE Tournament","Ev":"Lutheran South Academy","Ea":"12555 Ryewater Dr.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXHOWLLT","S":2022,"En":"TX-Houston West League Tournament","Ev":"Hogg Middle School","Ea":"1100 Merrill St.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-13T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USTXHOCLLT","S":2022,"En":"TX-Houston Central League Tournament","Ev":"Hogg Middle School","Ea":"1100 Merrill St.","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-13T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USTXCEPOSQ","S":2022,"En":"TX-Central Semi-Regional South","Ev":"Gregory-Portland HS","Ea":"4601 Wildcat Dr.","Ec":"Portland","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USTXHOSWLT1","S":2022,"En":"TX-Houston Southwest League Tournament","Ev":"Harmony School of Innovation - Sugar Land","Ea":"13738 Old Richmond Rd","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-19T00:00:00","Ed":"2023-02-19T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXNOFMQ","S":2022,"En":"TX-North Last Call Qualifier","Ev":"Flower Mound High School","Ea":"3411 Peters Colony Rd, Flower Mound, TX 75022","Ec":"Flower Mound","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USTXHONLLT1","S":2022,"En":"TX-Houston North League TOURNAMENT","Ev":"Brabham Middle School","Ea":"10000 Fm 830 Rd.","Ec":"Willis","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USTXNOATSQ","S":2022,"En":"TX-North Semi-Regional SOUTH","Ev":"Lamar High School, Arlington ISD","Ea":"1400 W Lamar Blvd, Arlington, TX 76012","Ec":"Arlington, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USWISFQ","S":2022,"En":"WI Frozen Frenzy","Ev":"St. Francis High School","Ea":"4225 South Lake Drive","Ec":"St. Francis","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USWYCMP","S":2022,"En":"Wyoming 2023 FTC State Championship","Ev":"CY Middle School","Ea":"2900 Cyclone Drive","Ec":"Casper","Es":"WY","Ect":"USA","Dn":"Wyoming","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010}]},{"Wt":"of 02/20/2023","Ws":"2023-02-20T00:00:00","We":"2023-02-26T23:59:59","Wn":24,"Ec":31,"E":[{"Tc":"CABCCMP","S":2022,"En":"British Columbia Championship","Ev":"L.A. Matheson Secondary","Ea":"9484 122 St.","Ec":"Surrey","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2023-02-25T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"CAONCMP","S":2022,"En":"Ontario Provincial Championship","Ev":"Centennial College (Progress Campus)","Ea":"941 Progress Ave","Ec":"Scarborough","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2023-02-26T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstcanada","eventType":1010},{"Tc":"ONADODCMP","S":2022,"En":"ONADoDEA-Europe 2023 Invitational Tournament","Ev":"Kaiserslautern High School","Ea":"Washington Square","Ec":"Kaiserslautern","Es":"BW","Ect":"Germany","Dn":"Military and Diplomatic","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.facebook.com/DoDEAEuropeActivitiesAthletics/","eventType":1010},{"Tc":"ONADODCMP1","S":2022,"En":"ONADoDEA-Europe 2023 Invitational Tournament","Ev":"Kaiserslautern High School","Ea":"Kaiserslautern HS","Ec":"Kaiserslautern","Es":"BW","Ect":"Germany","Dn":"Germany","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":None,"eventType":1010},{"Tc":"JMCMP","S":2022,"En":"JAMAICA National Championship","Ev":"Karl Hendrickson Auditorium - Jamaica College","Ea":"189 Old Hope Road","Ec":"Kingston 6","Es":"02","Ect":"Jamaica","Dn":"Jamaica","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"JMK6S","S":2022,"En":"Jamaica Pre-Championship Scrimmage","Ev":"Karl Hendrickson Auditorium - Jamaica College","Ea":"189 Old Hope Road","Ec":"Kingston 6","Es":"02","Ect":"Jamaica","Dn":"Jamaica","Sd":"2023-02-23T00:00:00","Ed":"2023-02-23T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"KZCMP","S":2022,"En":"Kazakhstan Central Asia FTC Regional Championship","Ev":"Children\u0027s Palace","Ea":"Bauyrzhan Momyshuly Avenue, 5, Astana, Kazakhstan","Ec":"Astana","Es":"AST","Ect":"Kazakhstan","Dn":"Kazakhstan","Sd":"2023-02-23T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"LYBEQ","S":2022,"En":"LY Benghazi Qualifying Competition","Ev":"New Benghazi Club venue","Ea":"Benghazi","Ec":"Benghazi","Es":"BA","Ect":"Libya","Dn":"Libya","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"ZACMP1","S":2022,"En":"South Africa National Championship","Ev":"Sci-Bono","Ea":"Mirjam Makeba Street","Ec":"Johannesburg","Es":"GP","Ect":"South Africa","Dn":"South Africa","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USARCMP","S":2022,"En":"Arkansas Championship","Ev":"Don Tyson School of Innovation","Ea":"2667 Hylton Rd","Ec":"Springdale","Es":"AR","Ect":"USA","Dn":"Arkansas","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1010},{"Tc":"USAZCMP","S":2022,"En":"Arizona FIRST Tech Challenge Championship","Ev":"Northern Arizona University Fieldhouse","Ea":"1050 Knoles Dr.","Ec":"Flagstaff","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1010},{"Tc":"USCALADBQ1","S":2022,"En":"CA-SoCal ILT 5 - Diamond Bar Saturday","Ev":"Diamond Bar High School","Ea":"21400 Pathfinder Rd","Ec":"Diamond Bar","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USCALSCMP","S":2022,"En":"CALS Los Angeles Unified School District Regional Championship","Ev":"TBD","Ea":"TBD","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"Los Angeles Unified School District","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USCALADBQ2","S":2022,"En":"CA-SoCal ILT 6 - Diamond Bar Sunday","Ev":"Diamond Bar High School","Ea":"21400 Pathfinder Rd","Ec":"Diamond Bar","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-02-26T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1001},{"Tc":"USDECMP","S":2022,"En":"Delaware 2022-2023 FTC Championship","Ev":"Wentworth Gymnasium, Delware State University","Ea":"120 N State St","Ec":"Dover","Es":"DE","Ect":"USA","Dn":"Delaware","Sd":"2023-02-20T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USGACMP","S":2022,"En":"Georgia State Championship","Ev":"Riverside Preparatory Academy","Ea":"2001 Riverside Dr.","Ec":"Gainesville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://twitch.tv/gafirst1","eventType":1010},{"Tc":"USIDMES","S":2022,"En":"ID Treasure Valley Scrimmage","Ev":"Cole Valley Christian","Ea":"200 E. Carlton Avenue","Ec":"Meridian","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USILCMP","S":2022,"En":"Illinois State Championship","Ev":"Elgin Community College Bldg J","Ea":"1700 Spartan Dr.","Ec":"Elgin","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USINCMP","S":2022,"En":"Indiana FIN FTC State Championship","Ev":"Tippecanoe County Fairgrounds","Ea":"1406 Teal Rd","Ec":"Lafayette","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNJSOLT2","S":2022,"En":"NJ 0225 Deep South Conference; Southern League Tournament","Ev":"North Burlington County Middle School","Ea":"180 Mansfield Road East","Ec":"Columbus","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USNJNOLT2","S":2022,"En":"NJ 0226 East Bergen Conference; Northern League Tournament","Ev":"Emerson Jr Sr High School","Ea":"131 Main St.","Ec":"Emerson","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-02-26T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USOKCMP","S":2022,"En":"Oklahoma Regional Championship","Ev":"Wes Watkins Center","Ea":"N Washington St \u0026 W Hall of Fame Ave","Ec":"Stillwater","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USORCMPSOL","S":2022,"En":"Oregon FIRST Tech Challenge Championship - Solar Division","Ev":"Liberty HS","Ea":"7445 NE Wagon Dr","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-25T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":None,"eventType":1010},{"Tc":"USORCMPHYD","S":2022,"En":"Oregon FIRST Tech Challenge Championship - Hydro Division","Ev":"Liberty HS","Ea":"7445 NE Wagon Dr","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-25T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":None,"eventType":1010},{"Tc":"USSCCMP","S":2022,"En":"South Carolina FTC Championship","Ev":"Dreher High School","Ea":"3319 Millwood Ave","Ec":"Columbia","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://firstsc.link/stream","eventType":1010},{"Tc":"USTXWPCMP","S":2022,"En":"Texas-West \u0026 Panhandle Regional Championship","Ev":"Lubbock High School","Ea":"2004 19th St","Ec":"Lubbock","Es":"TX","Ect":"USA","Dn":"Texas - West and Panhandle","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USTXNOCMP","S":2022,"En":"TX-North Regional Championship","Ev":"Marauder Activity Center at Marcus HS, LISD","Ea":"5707 Morriss Rd, Flower Mound, TX 75028","Ec":"Flower Mound, Texas","Es":"TX","Ect":"USA","Dn":"Texas - North","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.youtube.com/@ntxftc","eventType":1007},{"Tc":"USTXSOCMP3","S":2022,"En":"TX SOUTH REGIONAL CHAMPIONSHIP","Ev":"McAllen High School","Ea":"2021 La Vista Ave","Ec":"McAllen","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2023-02-22T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USTXHOCMP","S":2022,"En":"Texas-Houston East FTC Regional Championship","Ev":"San Jacinto College Central - CPET Building","Ea":"7901 Fairmont Pkwy","Ec":"Pasadena","Es":"TX","Ect":"USA","Dn":"Texas - Houston","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USTXCECMP2","S":2022,"En":"TX-Central Regional Championship","Ev":"School of Sience and Technology - Hill Country","Ea":"9202 West Loop 1604","Ec":"San Antonio","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1007},{"Tc":"USUTSJQ2","S":2022,"En":"UT AAI 2nd Qualifier","Ev":"American Academy of Innovation","Ea":"5410 S South Jordan Parkway","Ec":"South Jordan","Es":"UT","Ect":"USA","Dn":"Utah","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 02/27/2023","Ws":"2023-02-27T00:00:00","We":"2023-03-05T23:59:59","Wn":25,"Ec":19,"E":[{"Tc":"CAABCMP","S":2022,"En":"Alberta Championship","Ev":"St. Joseph\u0027s High School","Ea":"110, 2700 67 Street","Ec":"Red Deer","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2023-03-04T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1010},{"Tc":"CNCMP","S":2022,"En":"China FTC Championship","Ev":"Remote Event","Ea":"Remote Event","Ec":"Shanghai","Es":"SH","Ect":"China","Dn":"China","Sd":"2023-02-22T00:00:00","Ed":"2023-02-28T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"LYCMP","S":2022,"En":"Libya Regional Championship","Ev":"Mukthar International School Venue","Ea":"Tripoli","Ec":"Tripoli","Es":"TB","Ect":"Libya","Dn":"Libya","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"ROCMP1","S":2022,"En":"RO NATIONAL CHAMPIONSHIP - FTC ROMANIA","Ev":"Sala Polivalenta BUCURESTI  - parcul TINERETULUI","Ea":"Calea Piscului 10, Bucuresti","Ec":"Bucuresti","Es":"B","Ect":"Romania","Dn":"Romania","Sd":"2023-03-03T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.youtube.com/@NatieprinEducatie","eventType":1010},{"Tc":"USALCMP","S":2022,"En":"Alabama State Championship","Ev":"New Century Technology High School","Ea":"2500 Meridian St N","Ec":"Huntsville","Es":"AL","Ect":"USA","Dn":"Alabama","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"n/a","eventType":1010},{"Tc":"USCANOCMP","S":2022,"En":"California-NorCal FTC Regional Championship","Ev":"Kathleen MacDonald High School","Ea":"3588 Zanker Road","Ec":"San Jose","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-03-04T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USFLCMP","S":2022,"En":"Florida Championship","Ev":"Advent Fieldhouse","Ea":"210 Cypress Gardens Blvd","Ec":"Winter Haven","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USIACMP","S":2022,"En":"Iowa Championship","Ev":"Xtream Arena \u0026 GreenState Family Fieldhouse","Ea":"811 E. 2nd Ave","Ec":"Coralville","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USLACMP","S":2022,"En":"Louisiana Regional Championship","Ev":"Denham Springs High School - Hornsby Gym","Ea":"1000 N. Range Ave.","Ec":"Denham Springs","Es":"LA","Ect":"USA","Dn":"Louisiana","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMACMP","S":2022,"En":"Massachusetts State Championship","Ev":"Andover High School","Ea":"80 Shawsheen Road","Ec":"Andover","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-03-05T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMOKSCMP","S":2022,"En":"Missouri Kansas Regional Championship","Ev":"Gale Bullman Multi-Purpose Building","Ea":"705 W 10th St","Ec":"Rolla","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-03-04T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMSCMP","S":2022,"En":"Mississippi Championship","Ev":"University of Mississippi","Ea":"1111 Jackson Ave West","Ec":"Oxford","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNVCMP","S":2022,"En":"Nevada Championship","Ev":"Foothill High School","Ea":"800 College Dr","Ec":"Henderson","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1010},{"Tc":"USNYEXCMP","S":2022,"En":"New York-Excelsior MVCC Utica Championship","Ev":"Mohawk Valley Community College - Jorgensen Athletic Center","Ea":"1101 Sherman Drive","Ec":"Utica","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-03-05T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNYNYCMP","S":2022,"En":"New York-NYC CHAMPIONSHIP","Ev":"Dalton School Gym","Ea":"200 E 87th street","Ec":"New York","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2023-03-05T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USORCMP2","S":2022,"En":"OR Regional Championship","Ev":"Remote","Ea":"Remote","Ec":"Beaverton","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-25T00:00:00","Ed":"2023-03-03T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USPACMP","S":2022,"En":"Pennsylvania FTC Championship","Ev":"Saucon Valley Middle School","Ea":"2095 Polk Valley Rd","Ec":"Hellertown","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-03-01T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USRICMP","S":2022,"En":"Rhode Island FTC Championship","Ev":"New England Institute of Technology","Ea":"65-110 Access Road","Ec":"Warwick","Es":"RI","Ect":"USA","Dn":"Rhode Island","Sd":"2023-03-04T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USUTPCQ","S":2022,"En":"UT Park City High School Qualifier","Ev":"Park City High School","Ea":"750 Kearns Blvd","Ec":"Park City","Es":"UT","Ect":"USA","Dn":"Utah","Sd":"2023-03-04T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 03/06/2023","Ws":"2023-03-06T00:00:00","We":"2023-03-12T23:59:59","Wn":26,"Ec":13,"E":[{"Tc":"CYCMP","S":2022,"En":"Cyprus FTC Championship 2023","Ev":"Agios Dometios Basketball Stadium","Ea":"Gregori Afxentiou 6","Ec":"Agios Dometios","Es":"01","Ect":"Cyprus","Dn":"Cyprus","Sd":"2023-03-11T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"INCMP","S":2022,"En":"FIRST Tech Challenge India Championship","Ev":"Shree Shiv Chhatrapati Sports Complex","Ea":"Baner - Mahalunge Rd, National Games Park, Mahalunge","Ec":"Pune","Es":"MH","Ect":"India","Dn":"India","Sd":"2023-03-10T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"QACMP","S":2022,"En":"Qatar FIRST Tech Challenge 2023 Championship","Ev":"Qatar National Library","Ea":"Education City","Ec":"Doha","Es":"DA","Ect":"Qatar","Dn":"Qatar","Sd":"2023-03-08T00:00:00","Ed":"2023-03-09T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"GBBEQ","S":2022,"En":"GB Northern Ireland Regional","Ev":"W5 Science Discovery Centre","Ea":"The Odyssey, 2 Queens Quay,","Ec":"Belfast","Es":"NIR","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-03-10T00:00:00","Ed":"2023-03-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"ONADODFE23LT","S":2022,"En":"DoDEA Pacific FTC","Ev":"Kadena Rocker Club","Ea":"Kadena Air Base","Ec":"Kadena","Es":"AP","Ect":"USA","Dn":"Military and Diplomatic","Sd":"2023-03-07T00:00:00","Ed":"2023-03-08T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1001},{"Tc":"USCASDCMP","S":2022,"En":"CA- San Diego Regional Championship","Ev":"Pacific Ridge School","Ea":"6269 El Fuerte St","Ec":"Carlsbad","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-03-12T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USCALACMP","S":2022,"En":"California SoCal Championship","Ev":"Monrovia High School","Ea":"845 W Colorado Blvd, Monrovia CA","Ec":"Monrovia","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-03-11T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USIDCMP","S":2022,"En":"Idaho FIRST Tech Challenge State Championship","Ev":"Cole Valley Christian","Ea":"200 E. Carlton Avenue","Ec":"Meridian","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2023-03-10T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstidahorobotics","eventType":1010},{"Tc":"USNJCMP","S":2022,"En":"New Jersey State Championship-NJ0312","Ev":"Morris Knolls High School","Ea":"50 Knoll Drive","Ec":"Rockaway","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-03-12T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNYLICMP","S":2022,"En":"New York - Long Island Championship","Ev":"Bethpage High School","Ea":"10 Cherry Ave","Ec":"Bethpage","Es":"NY","Ect":"USA","Dn":"New York - Long Island","Sd":"2023-03-12T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USOHCMP","S":2022,"En":"Ohio FIRST Tech Challenge State Championship","Ev":"Hobart Arena","Ea":"255 Adams St","Ec":"Troy","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-03-09T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USUTCMP","S":2022,"En":"Utah Championship","Ev":"Southern Utah University","Ea":"351 W University Blvd","Ec":"Cedar City","Es":"UT","Ect":"USA","Dn":"Utah","Sd":"2023-03-11T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USWICMP","S":2022,"En":"Wisconsin Championship","Ev":"Kress Event Center","Ea":"2358 Leon Bond Dr","Ec":"Green Bay","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2023-03-11T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010}]},{"Wt":"of 03/13/2023","Ws":"2023-03-13T00:00:00","We":"2023-03-19T23:59:59","Wn":27,"Ec":2,"E":[{"Tc":"BRCMP","S":2022,"En":"Brazil FTC National Tournament","Ev":"Brasilia National Stadium","Ea":"SRPN Arena BRB Man\u00E9 Garrincha - Asa Norte, Bras\u00EDlia - DF","Ec":"Brasilia","Es":"DF","Ect":"Brazil","Dn":"Brazil","Sd":"2023-03-16T00:00:00","Ed":"2023-03-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"EGALS","S":2022,"En":"Egypt Scrimmage","Ev":"Library of Alexandria","Ea":"Chatby","Ec":"Alexandria","Es":"ALX","Ect":"Egypt","Dn":"Egypt","Sd":"2023-03-13T00:00:00","Ed":"2023-03-14T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 03/20/2023","Ws":"2023-03-20T00:00:00","We":"2023-03-26T23:59:59","Wn":28,"Ec":8,"E":[{"Tc":"SACMP","S":2022,"En":"Saudi Arabia FIRST Tech Challenge Championship - KSA","Ev":"King Abdullah Cultural Center","Ea":"3GPJ\u002BM35, Al Jubail 35821, Saudi Arabia","Ec":"Jubail Industrial City","Es":"04","Ect":"Saudi Arabia","Dn":"Saudi Arabia","Sd":"2023-03-18T00:00:00","Ed":"2023-03-22T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"GBLOQ","S":2022,"En":"GB South East Regional","Ev":"American School in London","Ea":"1 Waverley Pl,","Ec":"London","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-03-25T00:00:00","Ed":"2023-03-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"GBCOQ","S":2022,"En":"West Midlands Regional","Ev":"Royal Air Force Cosford","Ea":"Lysander Avenue, Cosford, Shropshire,","Ec":"Cosford","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-03-26T00:00:00","Ed":"2023-03-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1004},{"Tc":"USTXSOCMP2","S":2022,"En":"FIRST in Texas State Championship","Ev":"Bell County Expo Center","Ea":"801 E Fern Ave","Ec":"Rio Grande Valley","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2023-03-25T00:00:00","Ed":"2023-03-26T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXSOCMP","S":2022,"En":"FIRST in Texas UIL State 1A-4A","Ev":"Bell County Expo Center","Ea":"301 W Loop 121","Ec":"Belton","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2023-03-24T00:00:00","Ed":"2023-03-24T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXSOBES","S":2022,"En":"FIRST in Texas UIL State 6A","Ev":"Bell County Expo Center","Ea":"301 W Loop 121","Ec":"Belton","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2023-03-24T00:00:00","Ed":"2023-03-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"USTXCECMP","S":2022,"En":"FIRST in Texas FTC State Championship","Ev":"Bell County Expo Center (Garth Arena)","Ea":"301 W Loop 121","Ec":"Belton","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-03-20T00:00:00","Ed":"2023-03-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USTXSOBEOS","S":2022,"En":"FIRST in Texas UIL State 5A","Ev":"Bell County Expo Center","Ea":"301 W Loop 121","Ec":"Belton","Es":"TX","Ect":"USA","Dn":"Texas - South","Sd":"2023-03-24T00:00:00","Ed":"2023-03-24T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]},{"Wt":"of 03/27/2023","Ws":"2023-03-27T00:00:00","We":"2023-04-02T23:59:59","Wn":29,"Ec":2,"E":[{"Tc":"CNDIS","S":2022,"En":"Dianjian Peony Cup","Ev":"Dianjian","Ea":"Dianjian","Ec":"Dianjian","Es":"CQ","Ect":"China","Dn":"China","Sd":"2023-04-01T00:00:00","Ed":"2023-04-02T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0},{"Tc":"GBREQ","S":2022,"En":"GB Remote Regional","Ev":"Remote Event","Ea":"Remote Event","Ec":"Remote Event","Es":"ENG","Ect":"United Kingdom","Dn":"United Kingdom","Sd":"2023-03-23T00:00:00","Ed":"2023-03-29T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1004}]},{"Wt":"of 05/08/2023","Ws":"2023-05-08T00:00:00","We":"2023-05-14T23:59:59","Wn":35,"Ec":1,"E":[{"Tc":"USTXCECCS","S":2022,"En":"TX-Central Buc Days 2023 Robot Rodeo","Ev":"American Bank Building","Ea":"1900 Shoreline Blvd","Ec":"Corpus Christi","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-05-13T00:00:00","Ed":"2023-05-13T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":0}]}]
worlds=  [{"Wt":"FIRST Championship","Ws":"2023-04-18T00:00:00","We":"2023-04-22T00:00:00","Wn":0,"Ec":1,"E":[{"Tc":"FTCCMP1","S":2022,"En":"FIRST Championship - Houston - World Championship - FIRST Tech Challenge","Ev":"George R. Brown Convention Center","Ea":"1001 Avenida De Las Americas","Ec":"Houston","Es":"TX","Ect":"USA","Dn":"FIRST Championship - Zone 2 (Red)","Sd":"2023-04-18T00:00:00","Ed":"2023-04-22T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1013}]}]
regionals=  [{"Wt":"Regional Championships","Ws":"2022-12-07T00:00:00","We":"2023-03-26T00:00:00","Wn":0,"Ec":78,"E":[{"Tc":"USALCMP","S":2022,"En":"Alabama State Championship","Ev":"New Century Technology High School","Ea":"2500 Meridian St N","Ec":"Huntsville","Es":"AL","Ect":"USA","Dn":"Alabama","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"n/a","eventType":1010},{"Tc":"USAKCMP","S":2022,"En":"Alaska State Championship","Ev":"Colony High School","Ea":"9550 East Bogard Road","Ec":"Palmer","Es":"AK","Ect":"USA","Dn":"Alaska","Sd":"2023-01-20T00:00:00","Ed":"2023-01-21T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"CAABCMP","S":2022,"En":"Alberta Championship","Ev":"St. Joseph\u0027s High School","Ea":"110, 2700 67 Street","Ec":"Red Deer","Es":"AB","Ect":"Canada","Dn":"Alberta","Sd":"2023-03-04T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstalberta","eventType":1010},{"Tc":"USAZCMP","S":2022,"En":"Arizona FIRST Tech Challenge Championship","Ev":"Northern Arizona University Fieldhouse","Ea":"1050 Knoles Dr.","Ec":"Flagstaff","Es":"AZ","Ect":"USA","Dn":"Arizona","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://www.youtube.com/channel/UCsGNMOCahHmM_woTxeHbwnw","eventType":1010},{"Tc":"USARCMP","S":2022,"En":"Arkansas Championship","Ev":"Don Tyson School of Innovation","Ea":"2667 Hylton Rd","Ec":"Springdale","Es":"AR","Ect":"USA","Dn":"Arkansas","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1010},{"Tc":"AUCMP","S":2022,"En":"Australian National Championship","Ev":"Pymble Ladies College","Ea":"20-64 Avon Rd","Ec":"Pymble","Es":"NSW","Ect":"Australia","Dn":"Australia","Sd":"2022-12-10T00:00:00","Ed":"2022-12-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"BRCMP","S":2022,"En":"Brazil FTC National Tournament","Ev":"Brasilia National Stadium","Ea":"SRPN Arena BRB Man\u00E9 Garrincha - Asa Norte, Bras\u00EDlia - DF","Ec":"Brasilia","Es":"DF","Ect":"Brazil","Dn":"Brazil","Sd":"2023-03-16T00:00:00","Ed":"2023-03-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"CABCCMP","S":2022,"En":"British Columbia Championship","Ev":"L.A. Matheson Secondary","Ea":"9484 122 St.","Ec":"Surrey","Es":"BC","Ect":"Canada","Dn":"British Columbia","Sd":"2023-02-25T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USCASDCMP","S":2022,"En":"CA- San Diego Regional Championship","Ev":"Pacific Ridge School","Ea":"6269 El Fuerte St","Ec":"Carlsbad","Es":"CA","Ect":"USA","Dn":"California - San Diego","Sd":"2023-03-12T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USCALACMP","S":2022,"En":"California SoCal Championship","Ev":"Monrovia High School","Ea":"845 W Colorado Blvd, Monrovia CA","Ec":"Monrovia","Es":"CA","Ect":"USA","Dn":"California - Los Angeles","Sd":"2023-03-11T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USCANOCMP","S":2022,"En":"California-NorCal FTC Regional Championship","Ev":"Kathleen MacDonald High School","Ea":"3588 Zanker Road","Ec":"San Jose","Es":"CA","Ect":"USA","Dn":"California - Northern","Sd":"2023-03-04T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USCALSCMP","S":2022,"En":"CALS Los Angeles Unified School District Regional Championship","Ev":"TBD","Ea":"TBD","Ec":"Los Angeles","Es":"CA","Ect":"USA","Dn":"Los Angeles Unified School District","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USCHSCMP","S":2022,"En":"Chesapeake FTC Championship","Ev":"Archbishop Spalding High School","Ea":"8080 New Cut Rd","Ec":"Severn","Es":"MD","Ect":"USA","Dn":"Chesapeake","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"CNCMP","S":2022,"En":"China FTC Championship","Ev":"Remote Event","Ea":"Remote Event","Ec":"Shanghai","Es":"SH","Ect":"China","Dn":"China","Sd":"2023-02-22T00:00:00","Ed":"2023-02-28T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USCOCMP","S":2022,"En":"Colorado State Championship 2022-2023","Ev":"Colorado State University","Ea":"200 W. Lake Street","Ec":"Ft. Collins","Es":"CO","Ect":"USA","Dn":"Colorado","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USCTCMP","S":2022,"En":"Connecticut State Championship","Ev":"Wolcott High School","Ea":"457 Bound Line Rd","Ec":"Wolcott","Es":"CT","Ect":"USA","Dn":"Connecticut","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://twitch.tv/ctftc","eventType":1010},{"Tc":"CYCMP","S":2022,"En":"Cyprus FTC Championship 2023","Ev":"Agios Dometios Basketball Stadium","Ea":"Gregori Afxentiou 6","Ec":"Agios Dometios","Es":"01","Ect":"Cyprus","Dn":"Cyprus","Sd":"2023-03-11T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USDECMP","S":2022,"En":"Delaware 2022-2023 FTC Championship","Ev":"Wentworth Gymnasium, Delware State University","Ea":"120 N State St","Ec":"Dover","Es":"DE","Ect":"USA","Dn":"Delaware","Sd":"2023-02-20T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"CAQCCMP","S":2022,"En":"Festival de Robotique - Championnat provincial du D\u00E9fi Techno FIRST","Ev":"Grand Quai du Port de Montr\u00E9al","Ea":"200 de la Commune St W","Ec":"Montr\u00E9al","Es":"QC","Ect":"Canada","Dn":"Qu\u00E9bec","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USTXCECMP","S":2022,"En":"FIRST in Texas FTC State Championship","Ev":"Bell County Expo Center (Garth Arena)","Ea":"301 W Loop 121","Ec":"Belton","Es":"TX","Ect":"USA","Dn":"Texas - Central","Sd":"2023-03-20T00:00:00","Ed":"2023-03-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"INCMP","S":2022,"En":"FIRST Tech Challenge India Championship","Ev":"Shree Shiv Chhatrapati Sports Complex","Ea":"Baner - Mahalunge Rd, National Games Park, Mahalunge","Ec":"Pune","Es":"MH","Ect":"India","Dn":"India","Sd":"2023-03-10T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USFLCMP","S":2022,"En":"Florida Championship","Ev":"Advent Fieldhouse","Ea":"210 Cypress Gardens Blvd","Ec":"Winter Haven","Es":"FL","Ect":"USA","Dn":"Florida","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USGACMP","S":2022,"En":"Georgia State Championship","Ev":"Riverside Preparatory Academy","Ea":"2001 Riverside Dr.","Ec":"Gainesville","Es":"GA","Ect":"USA","Dn":"Georgia","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"https://twitch.tv/gafirst1","eventType":1010},{"Tc":"USHICMP","S":2022,"En":"Hawai\u2019i Regional Championship","Ev":"Le Jardin Academy","Ea":"917 Kalaniana\u02BBole Hwy,","Ec":"Honolulu","Es":"HI","Ect":"USA","Dn":"Hawaii","Sd":"2023-01-14T00:00:00","Ed":"2023-01-14T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBA","eventType":1010},{"Tc":"USIDCMP","S":2022,"En":"Idaho FIRST Tech Challenge State Championship","Ev":"Cole Valley Christian","Ea":"200 E. Carlton Avenue","Ec":"Meridian","Es":"ID","Ect":"USA","Dn":"Idaho","Sd":"2023-03-10T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstidahorobotics","eventType":1010},{"Tc":"USILCMP","S":2022,"En":"Illinois State Championship","Ev":"Elgin Community College Bldg J","Ea":"1700 Spartan Dr.","Ec":"Elgin","Es":"IL","Ect":"USA","Dn":"Illinois","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USINCMP","S":2022,"En":"Indiana FIN FTC State Championship","Ev":"Tippecanoe County Fairgrounds","Ea":"1406 Teal Rd","Ec":"Lafayette","Es":"IN","Ect":"USA","Dn":"Indiana","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USIACMP","S":2022,"En":"Iowa Championship","Ev":"Xtream Arena \u0026 GreenState Family Fieldhouse","Ea":"811 E. 2nd Ave","Ec":"Coralville","Es":"IA","Ect":"USA","Dn":"Iowa","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"ILCMP","S":2022,"En":"Israel Championship","Ev":"HaKiriya Arena","Ea":"60 HaAtzma\u0027ut Street","Ec":"Ashdod","Es":"D","Ect":"Israel","Dn":"Israel","Sd":"2023-02-11T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://ftc-live.firstisrael.org.il","eventType":1010},{"Tc":"JMCMP","S":2022,"En":"JAMAICA National Championship","Ev":"Karl Hendrickson Auditorium - Jamaica College","Ea":"189 Old Hope Road","Ec":"Kingston 6","Es":"02","Ect":"Jamaica","Dn":"Jamaica","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"KZCMP","S":2022,"En":"Kazakhstan Central Asia FTC Regional Championship","Ev":"Children\u0027s Palace","Ea":"Bauyrzhan Momyshuly Avenue, 5, Astana, Kazakhstan","Ec":"Astana","Es":"AST","Ect":"Kazakhstan","Dn":"Kazakhstan","Sd":"2023-02-23T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USKYCMP","S":2022,"En":"Kentucky State Championship","Ev":"University of Kentucky - Gatton Student Center","Ea":"160 Avenue of Champions","Ec":"Lexington","Es":"KY","Ect":"USA","Dn":"Kentucky","Sd":"2023-02-09T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"KRCMP","S":2022,"En":"Korea Robot Championship","Ev":"Daejeon Convention Center","Ea":"107 Expo-ro, Yuseong-gu","Ec":"Daejeon","Es":"30","Ect":"South Korea","Dn":"South Korea","Sd":"2023-02-04T00:00:00","Ed":"2023-02-04T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"LYCMP","S":2022,"En":"Libya Regional Championship","Ev":"Mukthar International School Venue","Ea":"Tripoli","Ec":"Tripoli","Es":"TB","Ect":"Libya","Dn":"Libya","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USLACMP","S":2022,"En":"Louisiana Regional Championship","Ev":"Denham Springs High School - Hornsby Gym","Ea":"1000 N. Range Ave.","Ec":"Denham Springs","Es":"LA","Ect":"USA","Dn":"Louisiana","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMACMP","S":2022,"En":"Massachusetts State Championship","Ev":"Andover High School","Ea":"80 Shawsheen Road","Ec":"Andover","Es":"MA","Ect":"USA","Dn":"Massachusetts","Sd":"2023-03-05T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMICMP","S":2022,"En":"Michigan FTC State Championship-NW","Ev":"Calvin University","Ea":"3195 Knight Way Southeast","Ec":"Grand Rapids","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-15T00:00:00","Ed":"2022-12-17T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMICMP2","S":2022,"En":"Michigan FTC State Championship-SE","Ev":"Macomb Community College","Ea":"14500 E. 12 Mile Road","Ec":"Warren","Es":"MI","Ect":"USA","Dn":"Michigan - FiM","Sd":"2022-12-08T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMNCMP","S":2022,"En":"Minnesota FTC State Championship","Ev":"Saint Paul RiverCentre","Ea":"175 Kellogg Blvd. W.","Ec":"St. Paul","Es":"MN","Ect":"USA","Dn":"Minnesota","Sd":"2023-02-10T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMSCMP","S":2022,"En":"Mississippi Championship","Ev":"University of Mississippi","Ea":"1111 Jackson Ave West","Ec":"Oxford","Es":"MS","Ect":"USA","Dn":"Mississippi","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMOKSCMP","S":2022,"En":"Missouri Kansas Regional Championship","Ev":"Gale Bullman Multi-Purpose Building","Ea":"705 W 10th St","Ec":"Rolla","Es":"MO","Ect":"USA","Dn":"Missouri","Sd":"2023-03-04T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USMTCMP","S":2022,"En":"Montana Regional Championship","Ev":"Montana State Shroyer Gym","Ea":"1 Bobcat Cir","Ec":"Bozeman","Es":"MT","Ect":"USA","Dn":"Montana","Sd":"2023-02-02T00:00:00","Ed":"2023-02-03T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"MXCMP","S":2022,"En":"MX POWER PLAY Campeonato Nacional FTC M\u00E9xico (CDMX)","Ev":"ITAM Campus R\u00EDo Hondo","Ea":"R\u00EDo Hondo 1, Altavista, \u00C1lvaro Obreg\u00F3n, 01080 Ciudad de M\u00E9xico, CDMX","Ec":"Ciudad de M\u00E9xico","Es":"CMX","Ect":"Mexico","Dn":"Mexico","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"NLNLLT","S":2022,"En":"Netherlands FTC Benelux Championship","Ev":"SintLucas","Ea":"Torenallee 75","Ec":"Eindhoven","Es":"NB","Ect":"Netherlands","Dn":"Netherlands","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/ftcnetherlands","eventType":1010},{"Tc":"USNVCMP","S":2022,"En":"Nevada Championship","Ev":"Foothill High School","Ea":"800 College Dr","Ec":"Henderson","Es":"NV","Ect":"USA","Dn":"Nevada","Sd":"2023-03-03T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstnevada","eventType":1010},{"Tc":"USNHCMP","S":2022,"En":"New Hampshire State Championship","Ev":"NHTI (New Hampshire Technical Institute)","Ea":"31 College Dr, Concord, NH 03301","Ec":"Concord","Es":"NH","Ect":"USA","Dn":"New Hampshire","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNJCMP","S":2022,"En":"New Jersey State Championship-NJ0312","Ev":"Morris Knolls High School","Ea":"50 Knoll Drive","Ec":"Rockaway","Es":"NJ","Ect":"USA","Dn":"New Jersey","Sd":"2023-03-12T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNMCMP","S":2022,"En":"New Mexico Regional Championship","Ev":"Raymond Sarracino Middle School","Ea":"1425 El Camino Real St.","Ec":"Socorro","Es":"NM","Ect":"USA","Dn":"New Mexico","Sd":"2023-01-27T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNYLICMP","S":2022,"En":"New York - Long Island Championship","Ev":"Bethpage High School","Ea":"10 Cherry Ave","Ec":"Bethpage","Es":"NY","Ect":"USA","Dn":"New York - Long Island","Sd":"2023-03-12T00:00:00","Ed":"2023-03-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNYEXCMP","S":2022,"En":"New York-Excelsior MVCC Utica Championship","Ev":"Mohawk Valley Community College - Jorgensen Athletic Center","Ea":"1101 Sherman Drive","Ec":"Utica","Es":"NY","Ect":"USA","Dn":"New York - Excelsior","Sd":"2023-03-05T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNYNYCMP","S":2022,"En":"New York-NYC CHAMPIONSHIP","Ev":"Dalton School Gym","Ea":"200 E 87th street","Ec":"New York","Es":"NY","Ect":"USA","Dn":"New York - NYC","Sd":"2023-03-05T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"NZCMP","S":2022,"En":"New Zealand National Championship","Ev":"Toitoi Events Centre","Ea":"109 Hastings Street South","Ec":"Hasting\u0027s","Es":"HKB","Ect":"New Zealand","Dn":"New Zealand","Sd":"2022-12-09T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"NGABQ","S":2022,"En":"NG Regional FIRST Tech Challenge","Ev":"National Stadium","Ea":"Constitution Ave, Kukwaba 900211, Abuja, Federal Capital Territory","Ec":"Abuja","Es":"FC","Ect":"Nigeria","Dn":"Nigeria","Sd":"2023-02-12T00:00:00","Ed":"2023-02-13T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USNCCMP","S":2022,"En":"North Carolina FTC State Championship","Ev":"Southern Guilford High School","Ea":"5700 Drake Rd","Ec":"Greensboro","Es":"NC","Ect":"USA","Dn":"North Carolina","Sd":"2023-02-18T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"TBD","eventType":1010},{"Tc":"USNDCMP","S":2022,"En":"North Dakota State Championships","Ev":"Bismarck Career Academy","Ea":"1221 College Drive","Ec":"Bismarck","Es":"ND","Ect":"USA","Dn":"North Dakota","Sd":"2023-01-30T00:00:00","Ed":"2023-02-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USOHCMP","S":2022,"En":"Ohio FIRST Tech Challenge State Championship","Ev":"Hobart Arena","Ea":"255 Adams St","Ec":"Troy","Es":"OH","Ect":"USA","Dn":"Ohio","Sd":"2023-03-09T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":True,"Lsu":"","eventType":1010},{"Tc":"USOKCMP","S":2022,"En":"Oklahoma Regional Championship","Ev":"Wes Watkins Center","Ea":"N Washington St \u0026 W Hall of Fame Ave","Ec":"Stillwater","Es":"OK","Ect":"USA","Dn":"Oklahoma","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"ONADODCMP","S":2022,"En":"ONADoDEA-Europe 2023 Invitational Tournament","Ev":"Kaiserslautern High School","Ea":"Washington Square","Ec":"Kaiserslautern","Es":"BW","Ect":"Germany","Dn":"Military and Diplomatic","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.facebook.com/DoDEAEuropeActivitiesAthletics/","eventType":1010},{"Tc":"ONADODCMP1","S":2022,"En":"ONADoDEA-Europe 2023 Invitational Tournament","Ev":"Kaiserslautern High School","Ea":"Kaiserslautern HS","Ec":"Kaiserslautern","Es":"BW","Ect":"Germany","Dn":"Germany","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":None,"eventType":1010},{"Tc":"CAONCMP","S":2022,"En":"Ontario Provincial Championship","Ev":"Centennial College (Progress Campus)","Ea":"941 Progress Ave","Ec":"Scarborough","Es":"ON","Ect":"Canada","Dn":"Ontario","Sd":"2023-02-26T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.twitch.tv/firstcanada","eventType":1010},{"Tc":"USORCMP2","S":2022,"En":"OR Regional Championship","Ev":"Remote","Ea":"Remote","Ec":"Beaverton","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-25T00:00:00","Ed":"2023-03-03T00:00:00","Ew":"","Hmd":True,"Isr":True,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USORCMPHYD","S":2022,"En":"Oregon FIRST Tech Challenge Championship - Hydro Division","Ev":"Liberty HS","Ea":"7445 NE Wagon Dr","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-25T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":None,"eventType":1010},{"Tc":"USORCMPSOL","S":2022,"En":"Oregon FIRST Tech Challenge Championship - Solar Division","Ev":"Liberty HS","Ea":"7445 NE Wagon Dr","Ec":"Hillsboro","Es":"OR","Ect":"USA","Dn":"Oregon","Sd":"2023-02-25T00:00:00","Ed":"2023-02-26T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":None,"eventType":1010},{"Tc":"USPACMP","S":2022,"En":"Pennsylvania FTC Championship","Ev":"Saucon Valley Middle School","Ea":"2095 Polk Valley Rd","Ec":"Hellertown","Es":"PA","Ect":"USA","Dn":"Pennsylvania","Sd":"2023-03-01T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"QACMP","S":2022,"En":"Qatar FIRST Tech Challenge 2023 Championship","Ev":"Qatar National Library","Ea":"Education City","Ec":"Doha","Es":"DA","Ect":"Qatar","Dn":"Qatar","Sd":"2023-03-08T00:00:00","Ed":"2023-03-09T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USRICMP","S":2022,"En":"Rhode Island FTC Championship","Ev":"New England Institute of Technology","Ea":"65-110 Access Road","Ec":"Warwick","Es":"RI","Ect":"USA","Dn":"Rhode Island","Sd":"2023-03-04T00:00:00","Ed":"2023-03-04T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"ROCMP1","S":2022,"En":"RO NATIONAL CHAMPIONSHIP - FTC ROMANIA","Ev":"Sala Polivalenta BUCURESTI  - parcul TINERETULUI","Ea":"Calea Piscului 10, Bucuresti","Ec":"Bucuresti","Es":"B","Ect":"Romania","Dn":"Romania","Sd":"2023-03-03T00:00:00","Ed":"2023-03-05T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://www.youtube.com/@NatieprinEducatie","eventType":1010},{"Tc":"SACMP","S":2022,"En":"Saudi Arabia FIRST Tech Challenge Championship - KSA","Ev":"King Abdullah Cultural Center","Ea":"3GPJ\u002BM35, Al Jubail 35821, Saudi Arabia","Ec":"Jubail Industrial City","Es":"04","Ect":"Saudi Arabia","Dn":"Saudi Arabia","Sd":"2023-03-18T00:00:00","Ed":"2023-03-22T00:00:00","Ew":"","Hmd":False,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"ZACMP1","S":2022,"En":"South Africa National Championship","Ev":"Sci-Bono","Ea":"Mirjam Makeba Street","Ec":"Johannesburg","Es":"GP","Ect":"South Africa","Dn":"South Africa","Sd":"2023-02-25T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USSCCMP","S":2022,"En":"South Carolina FTC Championship","Ev":"Dreher High School","Ea":"3319 Millwood Ave","Ec":"Columbia","Es":"SC","Ect":"USA","Dn":"South Carolina","Sd":"2023-02-24T00:00:00","Ed":"2023-02-25T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"https://firstsc.link/stream","eventType":1010},{"Tc":"USTNCMP","S":2022,"En":"Tennessee State Championship","Ev":"MTSU Alumni Memorial Gym","Ea":"2610 Middle Tennessee Blvd","Ec":"Murfreesboro","Es":"TN","Ect":"USA","Dn":"Tennessee","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"THCMP","S":2022,"En":"Thailand FTC Championship Event","Ev":"PRC","Ea":"Kaewnawarat Rd.","Ec":"Muang","Es":"50","Ect":"Thailand","Dn":"Thailand","Sd":"2022-12-07T00:00:00","Ed":"2022-12-10T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"TWCMP","S":2022,"En":"TW National Championship Event","Ev":"National Science and Technology Museum","Ea":"No. 720, Jiou Ru 1st Rd.,Sanminm Dist.","Ec":"Kaohsiung City","Es":"KHH","Ect":"Chinese Taipei","Dn":"Chinese Taipei","Sd":"2023-02-09T00:00:00","Ed":"2023-02-12T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USUTCMP","S":2022,"En":"Utah Championship","Ev":"Southern Utah University","Ea":"351 W University Blvd","Ec":"Cedar City","Es":"UT","Ect":"USA","Dn":"Utah","Sd":"2023-03-11T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USVTCMP","S":2022,"En":"Vermont FTC Championship","Ev":"Champlain Valley Union High School","Ea":"369 CVU Road","Ec":"Hinesburg","Es":"VT","Ect":"USA","Dn":"Vermont","Sd":"2023-02-11T00:00:00","Ed":"2023-02-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USWACMP","S":2022,"En":"Washington State Championship","Ev":"Amazon Doppler Building","Ea":"2021 7th Ave","Ec":"Seattle","Es":"WA","Ect":"USA","Dn":"Washington","Sd":"2023-01-28T00:00:00","Ed":"2023-01-28T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USWICMP","S":2022,"En":"Wisconsin Championship","Ev":"Kress Event Center","Ea":"2358 Leon Bond Dr","Ec":"Green Bay","Es":"WI","Ect":"USA","Dn":"Wisconsin","Sd":"2023-03-11T00:00:00","Ed":"2023-03-11T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010},{"Tc":"USWYCMP","S":2022,"En":"Wyoming 2023 FTC State Championship","Ev":"CY Middle School","Ea":"2900 Cyclone Drive","Ec":"Casper","Es":"WY","Ect":"USA","Dn":"Wyoming","Sd":"2023-02-17T00:00:00","Ed":"2023-02-18T00:00:00","Ew":"","Hmd":True,"Isr":False,"IsHybrid":False,"Lsu":"","eventType":1010}]}]

In [20]:
len(stuff)

12

In [22]:
stuff[1]

{'Wt': 'of 05/08/2023',
 'Ws': '2023-05-08T00:00:00',
 'We': '2023-05-14T23:59:59',
 'Wn': 35,
 'Ec': 7,
 'E': [{'Tc': 'FRLEOS',
   'S': 2022,
   'En': 'FR Le Défi Robotique – Lyon 2023',
   'Ev': 'Hotel de Région - Région Auvergne-Rhône-Alpes',
   'Ea': '101 Cours Charlemagne',
   'Ec': 'Lyon',
   'Es': '69',
   'Ect': 'France',
   'Dn': 'France',
   'Sd': '2023-05-13T00:00:00',
   'Ed': '2023-05-13T00:00:00',
   'Ew': '',
   'Hmd': False,
   'Isr': False,
   'IsHybrid': False,
   'Lsu': '',
   'eventType': 7},
  {'Tc': 'USMITCOS2',
   'S': 2022,
   'En': 'MI TC West Remote Event',
   'Ev': 'Traverse City West Middle School',
   'Ea': '3950 Silver Lake Rd.',
   'Ec': 'Traverse City',
   'Es': 'MI',
   'Ect': 'USA',
   'Dn': 'Michigan - FiM',
   'Sd': '2023-05-07T00:00:00',
   'Ed': '2023-05-13T00:00:00',
   'Ew': '',
   'Hmd': False,
   'Isr': True,
   'IsHybrid': False,
   'Lsu': '',
   'eventType': 7},
  {'Tc': 'USMIKIOS',
   'S': 2022,
   'En': 'Kingsford Spring Event',
   'Ev': 'Kingsford Middle School',
   'Ea': '431 Hamilton Avenue',
   'Ec': 'Kingsford',
   'Es': 'MI',
   'Ect': 'USA',
   'Dn': 'Michigan - FiM',
   'Sd': '2023-05-12T00:00:00',
   'Ed': '2023-05-13T00:00:00',
   'Ew': '',
   'Hmd': True,
   'Isr': False,
   'IsHybrid': False,
   'Lsu': '',
   'eventType': 7},
  {'Tc': 'USMIRCOS',
   'S': 2022,
   'En': 'Reed City Spring Event',
   'Ev': 'Reed City Middle School',
   'Ea': '233 W Church Avenue',
   'Ec': 'Reed City',
   'Es': 'MI',
   'Ect': 'USA',
   'Dn': 'Michigan - FiM',
   'Sd': '2023-05-12T00:00:00',
   'Ed': '2023-05-13T00:00:00',
   'Ew': '',
   'Hmd': True,
   'Isr': False,
   'IsHybrid': False,
   'Lsu': '',
   'eventType': 7},
  {'Tc': 'USMIJAOS',
   'S': 2022,
   'En': 'Jackson FTC Spring Event',
   'Ev': 'Jackson College Victor Cuiss Fieldhouse',
   'Ea': '2111 Emmons Road',
   'Ec': 'Jackson',
   'Es': 'MI',
   'Ect': 'USA',
   'Dn': 'Michigan - FiM',
   'Sd': '2023-05-12T00:00:00',
   'Ed': '2023-05-13T00:00:00',
   'Ew': '',
   'Hmd': True,
   'Isr': False,
   'IsHybrid': False,
   'Lsu': '',
   'eventType': 7},
  {'Tc': 'USORROOS',
   'S': 2022,
   'En': 'OR Spring Showcase',
   'Ev': 'Roseburg High School',
   'Ea': '400 W Harvard Ave',
   'Ec': 'Roseburg',
   'Es': 'OR',
   'Ect': 'USA',
   'Dn': 'Oregon',
   'Sd': '2023-05-13T00:00:00',
   'Ed': '2023-05-13T00:00:00',
   'Ew': '',
   'Hmd': False,
   'Isr': False,
   'IsHybrid': False,
   'Lsu': '',
   'eventType': 7},
  {'Tc': 'USTXWPROS',
   'S': 2022,
   'En': 'TX- WP CEN Exhibition',
   'Ev': 'Roscoe Collegiate ISD',
   'Ea': 'P. O. Box 579',
   'Ec': 'Roscoe',
   'Es': 'TX',
   'Ect': 'USA',
   'Dn': 'Texas - West and Panhandle',
   'Sd': '2023-05-13T00:00:00',
   'Ed': '2023-05-13T00:00:00',
   'Ew': '',
   'Hmd': True,
   'Isr': False,
   'IsHybrid': False,
   'Lsu': '',
   'eventType': 7}]}

In [27]:
bads = ['Wt', 'Ws', 'We', 'Wn', 'Ec']
for e in [stuff, others, worlds, regionals]:
    for s in e:
        for x in bads:
            del s[x]

In [28]:
stuff

[{'E': [{'Tc': 'USARLCMP',
    'S': 2022,
    'En': 'Adventist Robotics League Championship',
    'Ev': 'Forest Lake Academy',
    'Ea': '500 Education Loop',
    'Ec': 'Apopka',
    'Es': 'FL',
    'Ect': 'USA',
    'Dn': 'Adventist Robotics League',
    'Sd': '2023-05-07T00:00:00',
    'Ed': '2023-05-07T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USMIAAOS',
    'S': 2022,
    'En': 'Girls R GRAYT All Girls Event',
    'Ev': 'Rudolf Steiner School',
    'Ea': '2230 Pontiac Trail',
    'Ec': 'Ann Arbor',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-05T00:00:00',
    'Ed': '2023-05-06T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USMIGIOS',
    'S': 2022,
    'En': 'Gibraltar FTC Spring Showdown',
    'Ev': 'Carlson High School',
    'Ea': '30550 W Jefferson Avenue',
    'Ec': 'Gibraltar',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-05T00:00:00',
    'Ed': '2023-05-06T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USPAPHOS',
    'S': 2022,
    'En': 'PA FTC RoboJawn',
    'Ev': 'Central High School',
    'Ea': '1700 West Olney Ave',
    'Ec': 'Philadelphia',
    'Es': 'PA',
    'Ect': 'USA',
    'Dn': 'Pennsylvania',
    'Sd': '2023-05-06T00:00:00',
    'Ed': '2023-05-06T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'FRLEOS',
    'S': 2022,
    'En': 'FR Le Défi Robotique – Lyon 2023',
    'Ev': 'Hotel de Région - Région Auvergne-Rhône-Alpes',
    'Ea': '101 Cours Charlemagne',
    'Ec': 'Lyon',
    'Es': '69',
    'Ect': 'France',
    'Dn': 'France',
    'Sd': '2023-05-13T00:00:00',
    'Ed': '2023-05-13T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USMITCOS2',
    'S': 2022,
    'En': 'MI TC West Remote Event',
    'Ev': 'Traverse City West Middle School',
    'Ea': '3950 Silver Lake Rd.',
    'Ec': 'Traverse City',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-07T00:00:00',
    'Ed': '2023-05-13T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': True,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USMIKIOS',
    'S': 2022,
    'En': 'Kingsford Spring Event',
    'Ev': 'Kingsford Middle School',
    'Ea': '431 Hamilton Avenue',
    'Ec': 'Kingsford',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-12T00:00:00',
    'Ed': '2023-05-13T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USMIRCOS',
    'S': 2022,
    'En': 'Reed City Spring Event',
    'Ev': 'Reed City Middle School',
    'Ea': '233 W Church Avenue',
    'Ec': 'Reed City',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-12T00:00:00',
    'Ed': '2023-05-13T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USMIJAOS',
    'S': 2022,
    'En': 'Jackson FTC Spring Event',
    'Ev': 'Jackson College Victor Cuiss Fieldhouse',
    'Ea': '2111 Emmons Road',
    'Ec': 'Jackson',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-12T00:00:00',
    'Ed': '2023-05-13T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USORROOS',
    'S': 2022,
    'En': 'OR Spring Showcase',
    'Ev': 'Roseburg High School',
    'Ea': '400 W Harvard Ave',
    'Ec': 'Roseburg',
    'Es': 'OR',
    'Ect': 'USA',
    'Dn': 'Oregon',
    'Sd': '2023-05-13T00:00:00',
    'Ed': '2023-05-13T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USTXWPROS',
    'S': 2022,
    'En': 'TX- WP CEN Exhibition',
    'Ev': 'Roscoe Collegiate ISD',
    'Ea': 'P. O. Box 579',
    'Ec': 'Roscoe',
    'Es': 'TX',
    'Ect': 'USA',
    'Dn': 'Texas - West and Panhandle',
    'Sd': '2023-05-13T00:00:00',
    'Ed': '2023-05-13T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'USAZFLOS',
    'S': 2022,
    'En': 'AZ Lunar Legacy Invitational',
    'Ev': 'Northern Arizona University Fieldhouse',
    'Ea': '1050 Knoles Dr',
    'Ec': 'Flagstaff',
    'Es': 'AZ',
    'Ect': 'USA',
    'Dn': 'Arizona',
    'Sd': '2023-05-20T00:00:00',
    'Ed': '2023-05-21T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': 'https://www.youtube.com/@firsttechchallengearizona6515',
    'eventType': 7},
   {'Tc': 'USMIFROS',
    'S': 2022,
    'En': 'Freeland FTC Gear-Up!',
    'Ev': 'Freeland High School',
    'Ea': '8250 Webster Road',
    'Ec': 'Freeland',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-19T00:00:00',
    'Ed': '2023-05-20T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USORGLOS',
    'S': 2022,
    'En': 'OR Spring Showcase 2',
    'Ev': 'Gladstone High School',
    'Ea': '18800 Portland Ave',
    'Ec': 'Gladstone',
    'Es': 'OR',
    'Ect': 'USA',
    'Dn': 'Oregon',
    'Sd': '2023-05-20T00:00:00',
    'Ed': '2023-05-20T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USORMLS',
    'S': 2022,
    'En': 'OR Spring Scrimmage and Showcase',
    'Ev': 'Multiple Locations',
    'Ea': 'Multiple Locations',
    'Ec': 'Multiple Locations',
    'Es': 'OR',
    'Ect': 'USA',
    'Dn': 'Oregon',
    'Sd': '2023-05-20T00:00:00',
    'Ed': '2023-05-20T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'USIADMOS',
    'S': 2022,
    'En': 'IA CelebrAsian Off-Season Event',
    'Ev': 'Western Gateway Park',
    'Ea': '1205 Locust St',
    'Ec': 'Des Moines',
    'Es': 'IA',
    'Ect': 'USA',
    'Dn': 'Iowa',
    'Sd': '2023-05-27T00:00:00',
    'Ed': '2023-05-27T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USTXCESAOS',
    'S': 2022,
    'En': '2023 Blackout Battle Royale',
    'Ev': 'NA',
    'Ea': 'NA',
    'Ec': 'San Antonio',
    'Es': 'TX',
    'Ect': 'USA',
    'Dn': 'Texas - Central',
    'Sd': '2023-05-27T00:00:00',
    'Ed': '2023-05-27T00:00:00',
    'Ew': '',
    'Hmd': True,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'USMITCOS1',
    'S': 2022,
    'En': 'MI TC East Remote Event',
    'Ev': 'Traverse City East Middle School',
    'Ea': '1776 N Three Mile Rd.',
    'Ec': 'Traverse City',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-28T00:00:00',
    'Ed': '2023-06-03T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': True,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USWASAOS',
    'S': 2022,
    'En': 'WA Spartan Showdown',
    'Ev': 'Skyline High School',
    'Ea': '1122 228th Ave SE',
    'Ec': 'Sammamish',
    'Es': 'WA',
    'Ect': 'USA',
    'Dn': 'Washington',
    'Sd': '2023-06-03T00:00:00',
    'Ed': '2023-06-03T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'USMIBHOS1',
    'S': 2022,
    'En': 'MI FiM Remote Event',
    'Ev': 'Remote',
    'Ea': 'Remote',
    'Ec': 'Bloomfield Hills',
    'Es': 'MI',
    'Ect': 'USA',
    'Dn': 'Michigan - FiM',
    'Sd': '2023-05-30T00:00:00',
    'Ed': '2023-06-05T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': True,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'USCTSTOS',
    'S': 2022,
    'En': 'CT Husky Robotics Invitational',
    'Ev': 'University of Connecticut (UCONN) - Lawrence D. McHugh Hall',
    'Ea': 'Fairfield Way',
    'Ec': 'Storrs',
    'Es': 'CT',
    'Ect': 'USA',
    'Dn': 'Connecticut',
    'Sd': '2023-06-17T00:00:00',
    'Ed': '2023-06-17T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'GBCAOS',
    'S': 2022,
    'En': 'GB New Teams Regional',
    'Ev': 'University of Cambridge- Sports Centre',
    'Ea': 'Philippa Fawcett Dr,',
    'Ec': 'Cambridge',
    'Es': 'ENG',
    'Ect': 'United Kingdom',
    'Dn': 'United Kingdom',
    'Sd': '2023-06-23T00:00:00',
    'Ed': '2023-06-23T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'GBCMP',
    'S': 2022,
    'En': 'Championship- United Kingdom',
    'Ev': 'University of Cambridge- Sports Centre',
    'Ea': 'Philippa Fawcett Dr,',
    'Ec': 'Cambridge',
    'Es': 'ENG',
    'Ect': 'United Kingdom',
    'Dn': 'United Kingdom',
    'Sd': '2023-06-23T00:00:00',
    'Ed': '2023-06-23T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USALHUOS',
    'S': 2022,
    'En': 'AL betaSEIT',
    'Ev': 'New Century High School',
    'Ea': '2500 Meridian St N',
    'Ec': 'Huntsville',
    'Es': 'AL',
    'Ect': 'USA',
    'Dn': 'Alabama',
    'Sd': '2023-06-22T00:00:00',
    'Ed': '2023-06-24T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USOKMUOS',
    'S': 2022,
    'En': 'OK-Northeast (NEO) Invitational',
    'Ev': 'Muskogee High School',
    'Ea': '3200 E Shawnee Rd',
    'Ec': 'Muskogee',
    'Es': 'OK',
    'Ect': 'USA',
    'Dn': 'Oklahoma',
    'Sd': '2023-06-24T00:00:00',
    'Ed': '2023-06-24T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'USCHSLAOS',
    'S': 2022,
    'En': 'Maryland Tech Invitational',
    'Ev': 'Kossiakoff Center',
    'Ea': '11100 John Hopkins Rd',
    'Ec': 'laurel',
    'Es': 'MD',
    'Ect': 'USA',
    'Dn': 'Chesapeake',
    'Sd': '2023-06-23T00:00:00',
    'Ed': '2023-06-26T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'USCANOSMOS',
    'S': 2022,
    'En': 'Lobster Cup International',
    'Ev': 'San Mateo County Event Center',
    'Ea': '1346 Saratoga Drive',
    'Ec': 'San Mateo',
    'Es': 'CA',
    'Ect': 'USA',
    'Dn': 'California - Northern',
    'Sd': '2023-07-09T00:00:00',
    'Ed': '2023-07-09T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'AUMPOS1',
    'S': 2022,
    'En': 'AU APOC 2023',
    'Ev': 'Macquarie University',
    'Ea': 'Balaclava Road, Macquarie Park, NSW',
    'Ec': 'Macquarie Park',
    'Es': 'NSW',
    'Ect': 'Australia',
    'Dn': 'Australia',
    'Sd': '2023-07-14T00:00:00',
    'Ed': '2023-07-16T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7},
   {'Tc': 'USILCHOS',
    'S': 2022,
    'En': 'IL Chicago Robotics Invitational',
    'Ev': 'Francis W. Parker School',
    'Ea': '330 W Webster Ave',
    'Ec': 'chicago',
    'Es': 'IL',
    'Ect': 'USA',
    'Dn': 'Illinois',
    'Sd': '2023-07-14T00:00:00',
    'Ed': '2023-07-16T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]},
 {'E': [{'Tc': 'USOHAKOS',
    'S': 2022,
    'En': 'OH KSS Robotics Turtle Friendly',
    'Ev': 'Central-Hower High School',
    'Ea': '123 S. Forge Street',
    'Ec': 'Akron',
    'Es': 'OH',
    'Ect': 'USA',
    'Dn': 'Ohio',
    'Sd': '2023-07-29T00:00:00',
    'Ed': '2023-07-29T00:00:00',
    'Ew': '',
    'Hmd': False,
    'Isr': False,
    'IsHybrid': False,
    'Lsu': '',
    'eventType': 7}]}]

In [29]:
all_matches = []

In [38]:
for e in [stuff, others, worlds, regionals]:
    for s in e:
        for x in s['E']:
            useless = ['S', 'Lsu', 'eventType', 'IsHybrid', 'Isr', 'Hmd', 'Ew', 'Ev', 'Ea', 'Ec']
            for u in useless:
                del x[u]
            all_matches.append(x)

In [40]:
len(all_matches)

1218

In [41]:
df = pd.DataFrame.from_dict(all_matches)

In [42]:
df

,Tc,En,Es,Ect,Dn,Sd,Ed
0,USARLCMP,Adventist Robotics League Championship,FL,USA,Adventist Robotics League,2023-05-07T00:00:00,2023-05-07T00:00:00
1,USMIAAOS,Girls R GRAYT All Girls Event,MI,USA,Michigan - FiM,2023-05-05T00:00:00,2023-05-06T00:00:00
2,USMIGIOS,Gibraltar FTC Spring Showdown,MI,USA,Michigan - FiM,2023-05-05T00:00:00,2023-05-06T00:00:00
3,USPAPHOS,PA FTC RoboJawn,PA,USA,Pennsylvania,2023-05-06T00:00:00,2023-05-06T00:00:00
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,69,France,France,2023-05-13T00:00:00,2023-05-13T00:00:00
...,...,...,...,...,...,...,...
1213,USUTCMP,Utah Championship,UT,USA,Utah,2023-03-11T00:00:00,2023-03-11T00:00:00
1214,USVTCMP,Vermont FTC Championship,VT,USA,Vermont,2023-02-11T00:00:00,2023-02-11T00:00:00
1215,USWACMP,Washington State Championship,WA,USA,Washington,2023-01-28T00:00:00,2023-01-28T00:00:00
1216,USWICMP,Wisconsin Championship,WI,USA,Wisconsin,2023-03-11T00:00:00,2023-03-11T00:00:00
1217,USWYCMP,Wyoming 2023 FTC State Championship,WY,USA,Wyoming,2023-02-17T00:00:00,2023-02-18T00:00:00

In [44]:
renamed_df = df.rename(columns={"Tc": "Link", "En": "Name", "Ect": "Location", "Sd": "Start", "Ed": "End"})

In [48]:
renamed_df = renamed_df[['Link', 'Name','Location','Start', 'End']]

In [49]:
renamed_df

,Link,Name,Location,Start,End
0,USARLCMP,Adventist Robotics League Championship,USA,2023-05-07T00:00:00,2023-05-07T00:00:00
1,USMIAAOS,Girls R GRAYT All Girls Event,USA,2023-05-05T00:00:00,2023-05-06T00:00:00
2,USMIGIOS,Gibraltar FTC Spring Showdown,USA,2023-05-05T00:00:00,2023-05-06T00:00:00
3,USPAPHOS,PA FTC RoboJawn,USA,2023-05-06T00:00:00,2023-05-06T00:00:00
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,France,2023-05-13T00:00:00,2023-05-13T00:00:00
...,...,...,...,...,...
1213,USUTCMP,Utah Championship,USA,2023-03-11T00:00:00,2023-03-11T00:00:00
1214,USVTCMP,Vermont FTC Championship,USA,2023-02-11T00:00:00,2023-02-11T00:00:00
1215,USWACMP,Washington State Championship,USA,2023-01-28T00:00:00,2023-01-28T00:00:00
1216,USWICMP,Wisconsin Championship,USA,2023-03-11T00:00:00,2023-03-11T00:00:00
1217,USWYCMP,Wyoming 2023 FTC State Championship,USA,2023-02-17T00:00:00,2023-02-18T00:00:00

In [50]:
renamed_df.at[0,"Start"][0:10]

'2023-05-07'

In [51]:
for i in range(renamed_df.shape[0]):
    renamed_df.at[i,"Start"] = renamed_df.at[i,"Start"][0:10]
    renamed_df.at[i,"End"] = renamed_df.at[i,"End"][0:10]

In [52]:
renamed_df

,Link,Name,Location,Start,End
0,USARLCMP,Adventist Robotics League Championship,USA,2023-05-07,2023-05-07
1,USMIAAOS,Girls R GRAYT All Girls Event,USA,2023-05-05,2023-05-06
2,USMIGIOS,Gibraltar FTC Spring Showdown,USA,2023-05-05,2023-05-06
3,USPAPHOS,PA FTC RoboJawn,USA,2023-05-06,2023-05-06
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,France,2023-05-13,2023-05-13
...,...,...,...,...,...
1213,USUTCMP,Utah Championship,USA,2023-03-11,2023-03-11
1214,USVTCMP,Vermont FTC Championship,USA,2023-02-11,2023-02-11
1215,USWACMP,Washington State Championship,USA,2023-01-28,2023-01-28
1216,USWICMP,Wisconsin Championship,USA,2023-03-11,2023-03-11
1217,USWYCMP,Wyoming 2023 FTC State Championship,USA,2023-02-17,2023-02-18

In [53]:
import datetime
all_df = renamed_df
for i in range(renamed_df.shape[0]):
    s = renamed_df.at[i,"Start"].split("-")
    e = renamed_df.at[i,"End"].split("-")
    all_df.at[i,"Start"] = datetime.datetime(int(s[0]),int(s[1]),int(s[2]))
    all_df.at[i,"End"] = datetime.datetime(int(e[0]),int(e[1]),int(e[2]))

In [54]:
all_df

,Link,Name,Location,Start,End
0,USARLCMP,Adventist Robotics League Championship,USA,2023-05-07 00:00:00,2023-05-07 00:00:00
1,USMIAAOS,Girls R GRAYT All Girls Event,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
2,USMIGIOS,Gibraltar FTC Spring Showdown,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
3,USPAPHOS,PA FTC RoboJawn,USA,2023-05-06 00:00:00,2023-05-06 00:00:00
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,France,2023-05-13 00:00:00,2023-05-13 00:00:00
...,...,...,...,...,...
1213,USUTCMP,Utah Championship,USA,2023-03-11 00:00:00,2023-03-11 00:00:00
1214,USVTCMP,Vermont FTC Championship,USA,2023-02-11 00:00:00,2023-02-11 00:00:00
1215,USWACMP,Washington State Championship,USA,2023-01-28 00:00:00,2023-01-28 00:00:00
1216,USWICMP,Wisconsin Championship,USA,2023-03-11 00:00:00,2023-03-11 00:00:00
1217,USWYCMP,Wyoming 2023 FTC State Championship,USA,2023-02-17 00:00:00,2023-02-18 00:00:00

In [56]:
all_df.at[0,"Start"] >= all_df.at[0,"End"]

True

In [57]:
os.getcwd()

'/Volumes/mac/ftccomp/scripts'

In [59]:
all_df.to_csv(os.getcwd().replace('scripts', 'data')+ '/all_matches.csv', index = False)