In [1]:
import pandas as pd
import os

In [2]:
data = pd.read_csv(os.getcwd().replace("scripts", "data/all_data.csv"))

In [3]:
data.head(50)

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg RP,Avg Opp,Event W-L-T
0,12599,Overcharged,187.2,187.1,182.0,45.5,76.8,59.7,205.6,233.0,Oregon,2.0,34.8,9‑0‑0
1,8644,The Brainstormers,179.7,185.1,178.7,45.8,105.9,27.0,212.0,229.0,Massachusetts,2.0,63.2,10‑0‑0
2,15637,Fata Morgana,171.1,182.9,171.3,41.6,87.5,42.3,214.7,250.0,Israel,2.0,106.3,8‑0‑0
3,11329,I.C.E. Robotics,171.0,174.9,170.1,49.7,77.5,42.8,209.4,241.0,Indiana,2.0,84.0,9‑0‑0
4,18438,Wolfpack Machina,169.8,174.1,169.8,40.4,71.4,58.0,202.2,243.0,Massachusetts,2.0,84.7,10‑0‑0
5,11329,I.C.E. Robotics,165.2,166.9,161.0,44.8,85.7,30.5,207.0,228.0,Indiana,2.0,59.4,5‑0‑0
6,12599,Overcharged,162.7,165.4,165.0,39.2,77.8,48.0,222.2,284.0,Oregon,2.0,69.8,5‑0‑0
7,14179,Sushi Squad,161.2,152.8,161.6,47.4,70.7,43.5,251.0,271.0,New Mexico,2.0,71.2,6‑2‑0
8,8644,The Brainstormers,160.5,165.3,159.1,38.1,86.4,34.6,202.8,235.0,Massachusetts,2.0,53.7,10‑0‑0
9,14525,TerraBats,160.5,162.3,160.7,43.0,87.7,30.0,208.2,244.0,California Northern,2.0,111.6,9‑0‑0
10,16458,TechnoWizards,158.9,163.5,157.5,45.6,98.8,13.1,177.2,180.0,Texas Central,2.0,36.0,6‑0‑0
11,7172,Technical Difficulties,158.7,171.6,158.3,45.0,81.9,31.5,227.0,229.0,Texas North,2.0,117.3,10‑0‑0
12,19121,Tea Borgs,155.2,164.0,152.8,41.3,73.9,37.6,202.7,248.0,Romania,2.0,104.8,9‑3‑0
13,19458,Equilibrium.exe,154.9,156.2,152.3,38.5,73.2,40.6,195.8,217.0,Chesapeake,2.0,54.6,9‑0‑0
14,16158,VC Silver Circuits,154.1,159.8,154.1,50.4,73.2,30.6,207.5,240.0,Nevada,2.0,64.0,10‑0‑0
15,19746,The Disruptingly Robocephalic BrainSTEM Roboti...,154.0,158.5,153.0,47.9,81.2,23.9,223.4,242.0,Texas Central,2.0,126.4,9‑0‑0
16,8644,The Brainstormers,153.1,152.6,154.8,29.1,97.7,28.0,183.2,227.0,Chesapeake,2.0,28.2,9‑0‑0
17,19044,Peppers,151.2,154.5,150.9,41.9,76.7,32.3,230.1,255.0,Romania,2.0,126.0,8‑4‑0
18,16158,VC Silver Circuits,149.9,145.6,150.1,31.7,77.5,40.9,181.3,233.0,Nevada,2.0,47.3,10‑1‑0
19,21229,Quality Control,149.8,160.8,150.0,42.8,77.5,29.7,214.8,264.0,Washington,2.0,129.2,7‑2‑0
20,17713,Delta Force,149.4,154.2,148.8,44.5,52.5,51.8,248.7,274.0,Romania,2.0,105.7,8‑3‑0
21,9956,The Knack,149.1,155.2,145.9,48.4,75.9,21.6,196.8,219.0,Chesapeake,2.0,109.0,7‑2‑0
22,11329,I.C.E. Robotics,147.9,151.1,147.5,40.0,70.5,36.9,215.2,237.0,Indiana,1.6,104.4,4‑3‑0
23,15171,Scorpio,147.3,146.5,146.5,43.6,64.3,38.6,211.0,242.0,California San Diego,2.0,108.7,9‑2‑0
24,8393,The Giant Diencephalic BrainSTEM Robotics Team,145.7,161.4,145.6,49.9,57.8,37.9,230.8,238.0,Chesapeake,2.0,109.2,9‑1‑1
25,18529,Rust In Piece Robotics,145.6,145.2,144.6,40.8,88.7,15.1,208.3,223.0,Illinois,1.6,133.6,5‑3‑0
26,12560,Soft Hoarders,145.1,144.9,144.6,41.0,66.6,37.0,215.5,218.0,Romania,2.0,124.5,10‑1‑0
27,16417,ROC,145.0,152.6,146.2,50.7,90.0,5.5,211.0,253.0,Ontario,2.0,74.8,9‑0‑0
28,18438,Wolfpack Machina,144.9,148.4,145.1,49.4,63.6,32.1,229.6,246.0,Chesapeake,1.6,127.0,5‑3‑0
29,14614,Electro,144.0,146.1,143.9,40.9,76.5,26.5,198.6,217.0,Illinois,2.0,108.0,9‑0‑0
30,19234,BYTE FORCE RO037,143.8,148.6,144.7,42.3,62.6,39.8,216.8,245.0,Romania,2.0,71.7,6‑2‑0
31,21229,Quality Control,143.6,147.5,141.5,48.0,66.7,26.9,181.5,270.0,Colorado,2.0,63.8,10‑0‑0
32,12599,Overcharged,143.6,149.6,142.9,34.4,59.1,49.4,178.8,206.0,Oregon,2.0,41.4,5‑0‑0
33,20153,Silver Wolves,142.8,161.8,142.8,39.7,74.6,28.5,193.4,246.0,Pennsylvania,1.6,116.6,8‑3‑0
34,10138,Newton Busters,142.0,152.7,140.6,28.7,74.9,36.9,199.0,233.0,Illinois,1.6,133.8,8‑1‑0
35,22377,SigmaCorns,142.0,138.7,142.2,43.0,75.8,23.4,168.6,184.0,North Carolina,2.0,69.2,9‑0‑0
36,12611,TechNova,141.6,141.6,141.7,44.9,82.2,14.7,199.3,259.0,Alabama,1.7,125.0,5‑3‑0
37,3658,The BOSONS,141.3,141.9,141.6,41.7,62.8,37.1,182.2,219.0,Missouri,1.7,76.8,5‑1‑0
38,19561,Tiger Tech Black 19561,141.1,141.1,141.5,39.8,93.8,7.8,200.7,222.0,Michigan,1.3,172.0,5‑4‑0
39,19862,Mecha Mantises,141.0,137.4,139.1,45.5,77.0,16.7,185.4,219.0,California Northern,1.2,126.4,3‑4‑0
40,9889,Cruise Control,140.8,153.0,140.9,23.2,70.2,47.5,212.4,271.0,New Jersey,2.0,39.2,5‑0‑0
41,19746,The Disruptingly Robocephalic BrainSTEM Roboti...,140.4,142.7,135.7,39.9,75.9,19.9,210.6,226.0,Texas Central,1.6,137.2,7‑3‑0
42,19746,The Disruptingly Robocephalic BrainSTEM Roboti...,139.6,138.8,138.3,40.0,65.4,32.9,230.8,280.0,Texas Central,1.7,126.0,9‑2‑0
43,16158,VC Silver Circuits,139.4,138.0,133.7,31.9,70.6,31.1,154.6,187.0,Nevada,2.0,29.6,5‑0‑0
44,17595,Beta Bionix,139.1,145.6,138.9,25.7,76.8,36.3,192.2,224.0,Washington,1.2,129.2,7‑2‑0
45,14212,Metrobotics,139.0,142.3,138.4,41.6,63.0,33.7,204.7,251.0,New York City,2.0,82.2,10‑0‑0
46,21229,Quality Control,139.0,154.2,135.4,47.1,68.0,20.3,224.2,235.0,Colorado,2.0,107.7,10‑0‑0
47,18527,PCM Alchemists,138.9,146.0,137.3,42.8,66.1,28.4,204.2,257.0,Iowa,1.7,121.2,8‑3‑0
48,12635,Kuriosity Robotics,137.6,138.0,137.6,49.6,65.6,22.4,223.3,255.0,California Northern,2.0,115.7,12‑1‑0
49,11039,Innov8rz,137.5,138.3,138.8,41.9,86.7,10.3,171.2,186.0,California Northern,2.0,91.8,9‑0‑0

In [4]:
data.sort_values("Team Number")

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg RP,Avg Opp,Event W-L-T
9916,1,Team Unlimited,24.6,31.5,24.8,0.0,12.2,12.6,69.3,109.0,Massachusetts,1.3,38.3,4‑4‑0
3917,1,Team Unlimited,57.2,72.1,60.5,21.4,28.7,10.4,126.0,165.0,Massachusetts,1.3,63.0,5‑4‑0
1234,1,Team Unlimited,83.8,113.5,86.1,13.9,51.3,20.9,175.0,219.0,Massachusetts,2.0,70.2,7‑3‑0
8375,7,Tactical Sheep,31.6,49.3,32.3,9.1,16.5,6.7,102.4,123.0,Chesapeake,1.2,83.4,3‑4‑0
712,7,Tactical Sheep,94.8,102.9,94.3,30.4,42.8,21.1,181.2,216.0,Chesapeake,1.2,137.8,3‑4‑1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3537,23069,NaN,60.0,64.8,58.2,18.1,25.8,14.4,113.7,177.0,Brazil,1.3,70.8,6‑5‑0
8119,23072,NaN,32.8,40.2,31.2,7.2,14.4,9.6,73.0,107.0,Brazil,0.3,92.0,1‑5‑0
16618,23073,NaN,-6.5,0.8,1.4,0.0,0.0,1.4,41.2,86.0,Brazil,0.3,90.0,1‑5‑0
15577,23085,NaN,3.0,14.7,6.3,0.0,4.5,1.8,69.5,112.0,Kazakhstan,1.0,56.7,3‑3‑0
9055,23088,NaN,28.4,36.2,30.3,0.9,14.7,14.7,100.2,164.0,Kazakhstan,1.0,59.7,7‑4‑0

In [5]:
wlt = pd.concat([data["Team Number"], data["Event W-L-T"]], axis = 1)

In [6]:
x = lambda a,b: (int(a.split("-")[0])+ int(b.split("-")[0])) +"-" +(int(a.split("-")[1])+ int(b.split("-")[1]))+"-" +(int(a.split("-")[2])+ int(b.split("-")[2]))

In [7]:
w = []
l = []
t = []
for index, row in wlt.iterrows():
    arr = row["Event W-L-T"].split("‑")
    
    w.append(int(arr[0]))
    l.append(int(arr[1]))
    t.append(int(arr[2]))
    
wlt["W"] = w
wlt["L"] = l
wlt["T"] = t

In [8]:
wlt

       Team Number Event W-L-T   W  L  T
0            12599       9‑0‑0   9  0  0
1             8644      10‑0‑0  10  0  0
2            15637       8‑0‑0   8  0  0
3            11329       9‑0‑0   9  0  0
4            18438      10‑0‑0  10  0  0
...            ...         ...  .. .. ..
16785        22673       0‑5‑0   0  5  0
16786        14165       2‑3‑0   2  3  0
16787        21886       1‑4‑0   1  4  0
16788        13402       0‑5‑0   0  5  0
16789        19734       2‑3‑0   2  3  0

[16790 rows x 5 columns]

In [9]:
wlt = wlt.drop("Event W-L-T", axis = 1)

In [10]:
wlt

       Team Number   W  L  T
0            12599   9  0  0
1             8644  10  0  0
2            15637   8  0  0
3            11329   9  0  0
4            18438  10  0  0
...            ...  .. .. ..
16785        22673   0  5  0
16786        14165   2  3  0
16787        21886   1  4  0
16788        13402   0  5  0
16789        19734   2  3  0

[16790 rows x 4 columns]

In [ ]:
wlt[]

In [11]:
wlt.groupby("Team Number").sum()

              W   L  T
Team Number
1            16  11  0
7            15   8  1
18            3   7  0
22            5  20  0
25           14  14  0
...          ..  .. ..
23069         6   5  0
23072         1   5  0
23073         1   5  0
23085         3   3  0
23088         7   4  0

[5483 rows x 3 columns]

In [28]:
data.groupby("Team Number").mean()

,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Avg RP,Avg Opp
Team Number,,,,,,,,,,
1,40.900000,51.800000,42.650,10.700000,20.450000,11.50,97.65,137.000000,1.300000,50.650000
7,80.666667,86.933333,81.500,26.366667,40.633333,14.50,153.40,182.333333,1.466667,88.533333
18,33.900000,36.200000,32.100,0.000000,22.600000,9.50,69.60,83.500000,0.600000,79.500000
22,17.600000,19.880000,17.180,4.140000,6.580000,6.44,43.72,72.000000,0.400000,77.160000
25,39.850000,43.750000,37.375,16.750000,11.350000,9.30,71.80,114.750000,1.100000,59.950000
...,...,...,...,...,...,...,...,...,...,...
23015,64.900000,71.900000,61.900,20.100000,21.300000,20.50,131.00,182.000000,1.300000,96.300000
23050,7.300000,11.300000,5.400,1.500000,0.000000,3.90,59.30,146.000000,0.300000,147.800000
23056,28.200000,30.300000,24.900,1.700000,19.300000,3.80,53.50,78.000000,0.700000,95.300000
23085,3.000000,14.700000,6.300,0.000000,4.500000,1.80,69.50,112.000000,1.000000,56.700000
23088,28.400000,36.200000,30.300,0.900000,14.700000,14.70,100.20,164.000000,1.000000,59.700000

In [12]:
data

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg RP,Avg Opp,Event W-L-T
0,12599,Overcharged,187.2,187.1,182.0,45.5,76.8,59.7,205.6,233.0,Oregon,2.0,34.8,9‑0‑0
1,8644,The Brainstormers,179.7,185.1,178.7,45.8,105.9,27.0,212.0,229.0,Massachusetts,2.0,63.2,10‑0‑0
2,15637,Fata Morgana,171.1,182.9,171.3,41.6,87.5,42.3,214.7,250.0,Israel,2.0,106.3,8‑0‑0
3,11329,I.C.E. Robotics,171.0,174.9,170.1,49.7,77.5,42.8,209.4,241.0,Indiana,2.0,84.0,9‑0‑0
4,18438,Wolfpack Machina,169.8,174.1,169.8,40.4,71.4,58.0,202.2,243.0,Massachusetts,2.0,84.7,10‑0‑0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,22673,Error 422,-19.6,-12.4,0.0,0.0,0.0,0.0,18.4,33.0,Texas North,0.0,103.8,0‑5‑0
16786,14165,Pebblebrook OG Team,-20.4,-15.2,0.0,0.0,0.0,0.0,23.6,23.0,Georgia,0.8,55.8,2‑3‑0
16787,21886,Lithium,-23.6,-12.0,0.0,0.0,0.0,0.0,47.8,90.0,Chesapeake,0.4,89.4,1‑4‑0
16788,13402,Team with No Name,-27.3,-26.6,0.0,0.0,0.0,0.0,21.6,51.0,Indiana,0.0,70.0,0‑5‑0
16789,19734,Frenship Middle School 2,-27.3,-22.8,0.0,0.0,0.0,0.0,40.6,71.0,Texas West & Panhandle,0.8,72.0,2‑3‑0

In [19]:
wlt

       Team Number   W  L  T
0            12599   9  0  0
1             8644  10  0  0
2            15637   8  0  0
3            11329   9  0  0
4            18438  10  0  0
...            ...  .. .. ..
16785        22673   0  5  0
16786        14165   2  3  0
16787        21886   1  4  0
16788        13402   0  5  0
16789        19734   2  3  0

[16790 rows x 4 columns]

In [21]:
data2 = pd.concat([data, wlt.drop('Team Number', axis = 1)], axis = 1)

In [22]:
data2[1000:1100]

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg RP,Avg Opp,Event W-L-T,W,L,T
1000,16265,ENIGMA,88.3,88.9,86.5,17.6,33.3,35.6,157.8,172.0,Utah,0.8,125.0,4‑5‑0,4,5,0
1001,9415,Wrench Dressing,88.2,87.1,88.2,27.6,35.6,24.9,174.0,226.0,Minnesota,1.7,101.7,9‑2‑0,9,2,0
1002,417,S.K.I.D. (Space Koalas In Disguise),88.2,104.7,87.6,20.9,48.5,18.3,159.6,179.0,Washington,1.2,124.4,3‑4‑0,3,4,0
1003,15229,Team KUDOS,88.2,91.9,89.1,21.4,48.2,19.5,130.2,148.0,Michigan,0.8,148.2,3‑5‑0,3,5,0
1004,14840,DCS MechWarriors,88.2,86.9,88.5,25.2,30.3,33.0,129.8,169.0,Illinois,2.0,56.0,5‑0‑0,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,10615,Jefferson CyDogs,86.3,88.6,86.5,14.3,51.6,20.6,166.0,226.0,Michigan,1.3,118.2,4‑2‑0,4,2,0
1096,12977,Rust In Peace,86.4,86.6,77.7,18.1,28.0,31.6,110.4,170.0,Texas North,0.8,126.8,6‑4‑0,6,4,0
1097,10644,CyBugs,86.3,86.2,85.0,26.5,29.6,28.8,105.8,146.0,Michigan,1.6,53.4,4‑1‑0,4,1,0
1098,3805,Atomic Robotics,86.3,85.1,86.2,12.3,52.0,21.9,114.0,172.0,Washington,2.0,46.3,6‑0‑0,6,0,0
1099,11254,Robo Rhinos,86.3,90.9,86.0,24.4,42.3,19.3,147.8,160.0,Michigan,1.8,100.2,5‑2‑1,5,2,1

In [23]:
data3 = data2.drop('Event W-L-T', axis = 1)

In [24]:
data3

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg RP,Avg Opp,W,L,T
0,12599,Overcharged,187.2,187.1,182.0,45.5,76.8,59.7,205.6,233.0,Oregon,2.0,34.8,9,0,0
1,8644,The Brainstormers,179.7,185.1,178.7,45.8,105.9,27.0,212.0,229.0,Massachusetts,2.0,63.2,10,0,0
2,15637,Fata Morgana,171.1,182.9,171.3,41.6,87.5,42.3,214.7,250.0,Israel,2.0,106.3,8,0,0
3,11329,I.C.E. Robotics,171.0,174.9,170.1,49.7,77.5,42.8,209.4,241.0,Indiana,2.0,84.0,9,0,0
4,18438,Wolfpack Machina,169.8,174.1,169.8,40.4,71.4,58.0,202.2,243.0,Massachusetts,2.0,84.7,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,22673,Error 422,-19.6,-12.4,0.0,0.0,0.0,0.0,18.4,33.0,Texas North,0.0,103.8,0,5,0
16786,14165,Pebblebrook OG Team,-20.4,-15.2,0.0,0.0,0.0,0.0,23.6,23.0,Georgia,0.8,55.8,2,3,0
16787,21886,Lithium,-23.6,-12.0,0.0,0.0,0.0,0.0,47.8,90.0,Chesapeake,0.4,89.4,1,4,0
16788,13402,Team with No Name,-27.3,-26.6,0.0,0.0,0.0,0.0,21.6,51.0,Indiana,0.0,70.0,0,5,0
16789,19734,Frenship Middle School 2,-27.3,-22.8,0.0,0.0,0.0,0.0,40.6,71.0,Texas West & Panhandle,0.8,72.0,2,3,0

In [31]:
data4 = data3.sort_values('Team Number').reset_index(drop = True)

In [32]:
data4[:10]

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg RP,Avg Opp,W,L,T
0,1,Team Unlimited,24.6,31.5,24.8,0.0,12.2,12.6,69.3,109.0,Massachusetts,1.3,38.3,4,4,0
1,1,Team Unlimited,57.2,72.1,60.5,21.4,28.7,10.4,126.0,165.0,Massachusetts,1.3,63.0,5,4,0
2,1,Team Unlimited,83.8,113.5,86.1,13.9,51.3,20.9,175.0,219.0,Massachusetts,2.0,70.2,7,3,0
3,7,Tactical Sheep,31.6,49.3,32.3,9.1,16.5,6.7,102.4,123.0,Chesapeake,1.2,83.4,3,4,0
4,7,Tactical Sheep,94.8,102.9,94.3,30.4,42.8,21.1,181.2,216.0,Chesapeake,1.2,137.8,3,4,1
5,7,Tactical Sheep,115.6,108.6,117.9,39.6,62.6,15.7,176.6,208.0,Chesapeake,2.0,44.4,9,0,0
6,18,Techno Chix,48.0,60.2,51.2,0.0,34.2,17.0,108.4,126.0,New York Excelsior,0.8,86.8,2,3,0
7,18,Techno Chix,19.8,12.2,13.0,0.0,11.0,2.0,30.8,41.0,New York Excelsior,0.4,72.2,1,4,0
8,22,100 Scholars,34.2,43.4,33.1,10.3,13.7,9.1,66.2,115.0,Georgia,0.4,100.0,1,4,0
9,22,100 Scholars,9.6,14.1,6.7,1.8,3.5,1.3,31.4,57.0,Georgia,0.0,52.6,0,5,0

In [33]:
noRP= data4.drop("Avg RP", axis = 1)

In [34]:
noRP

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg Opp,W,L,T
0,1,Team Unlimited,24.6,31.5,24.8,0.0,12.2,12.6,69.3,109.0,Massachusetts,38.3,4,4,0
1,1,Team Unlimited,57.2,72.1,60.5,21.4,28.7,10.4,126.0,165.0,Massachusetts,63.0,5,4,0
2,1,Team Unlimited,83.8,113.5,86.1,13.9,51.3,20.9,175.0,219.0,Massachusetts,70.2,7,3,0
3,7,Tactical Sheep,31.6,49.3,32.3,9.1,16.5,6.7,102.4,123.0,Chesapeake,83.4,3,4,0
4,7,Tactical Sheep,94.8,102.9,94.3,30.4,42.8,21.1,181.2,216.0,Chesapeake,137.8,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,23069,NaN,60.0,64.8,58.2,18.1,25.8,14.4,113.7,177.0,Brazil,70.8,6,5,0
16786,23072,NaN,32.8,40.2,31.2,7.2,14.4,9.6,73.0,107.0,Brazil,92.0,1,5,0
16787,23073,NaN,-6.5,0.8,1.4,0.0,0.0,1.4,41.2,86.0,Brazil,90.0,1,5,0
16788,23085,NaN,3.0,14.7,6.3,0.0,4.5,1.8,69.5,112.0,Kazakhstan,56.7,3,3,0
16789,23088,NaN,28.4,36.2,30.3,0.9,14.7,14.7,100.2,164.0,Kazakhstan,59.7,7,4,0

In [41]:
max_score = noRP.groupby("Team Number").max()["Max Norm Score"]

In [42]:
max_score

Team Number
1        219.0
7        216.0
18       126.0
22       115.0
25       161.0
         ...
23069    177.0
23072    107.0
23073     86.0
23085    112.0
23088    164.0
Name: Max Norm Score, Length: 5483, dtype: float64

In [40]:
noRP[noRP['Team Number']==15118]

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg Opp,W,L,T
8342,15118,CogChamp,43.8,45.9,43.8,7.7,22.3,13.9,86.8,179.0,Illinois,92.4,1,4,0
8343,15118,CogChamp,69.7,74.7,68.3,17.0,26.8,24.5,145.4,202.0,Illinois,107.0,3,2,0
8344,15118,CogChamp,45.0,66.2,44.4,16.4,18.7,9.3,123.4,137.0,Illinois,118.4,2,6,0
8345,15118,CogChamp,79.4,78.9,76.9,14.2,31.8,30.9,119.0,191.0,Illinois,74.0,3,2,0

In [56]:
wlt_df = noRP.groupby("Team Number").sum()[["W", "L", "T"]]

In [48]:
max_score

Team Number
1        219.0
7        216.0
18       126.0
22       115.0
25       161.0
         ...
23069    177.0
23072    107.0
23073     86.0
23085    112.0
23088    164.0
Name: Max Norm Score, Length: 5483, dtype: float64

In [50]:
path = os.getcwd().replace("scripts", "data/")
wlt_df.to_csv(path +'wlt.csv', index = False)

In [57]:
wlt_df

              W   L  T
Team Number
1            16  11  0
7            15   8  1
18            3   7  0
22            5  20  0
25           14  14  0
...          ..  .. ..
23069         6   5  0
23072         1   5  0
23073         1   5  0
23085         3   3  0
23088         7   4  0

[5483 rows x 3 columns]

In [51]:
max_score.to_csv(path +'max_score.csv', index = False)

In [52]:
noRP

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg Opp,W,L,T
0,1,Team Unlimited,24.6,31.5,24.8,0.0,12.2,12.6,69.3,109.0,Massachusetts,38.3,4,4,0
1,1,Team Unlimited,57.2,72.1,60.5,21.4,28.7,10.4,126.0,165.0,Massachusetts,63.0,5,4,0
2,1,Team Unlimited,83.8,113.5,86.1,13.9,51.3,20.9,175.0,219.0,Massachusetts,70.2,7,3,0
3,7,Tactical Sheep,31.6,49.3,32.3,9.1,16.5,6.7,102.4,123.0,Chesapeake,83.4,3,4,0
4,7,Tactical Sheep,94.8,102.9,94.3,30.4,42.8,21.1,181.2,216.0,Chesapeake,137.8,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,23069,NaN,60.0,64.8,58.2,18.1,25.8,14.4,113.7,177.0,Brazil,70.8,6,5,0
16786,23072,NaN,32.8,40.2,31.2,7.2,14.4,9.6,73.0,107.0,Brazil,92.0,1,5,0
16787,23073,NaN,-6.5,0.8,1.4,0.0,0.0,1.4,41.2,86.0,Brazil,90.0,1,5,0
16788,23085,NaN,3.0,14.7,6.3,0.0,4.5,1.8,69.5,112.0,Kazakhstan,56.7,3,3,0
16789,23088,NaN,28.4,36.2,30.3,0.9,14.7,14.7,100.2,164.0,Kazakhstan,59.7,7,4,0

In [60]:
teams = noRP["Team Number"].unique()

In [87]:
regions = []
names = []
for team in teams:
    regions.append(noRP[noRP["Team Number"]==team].iloc[[0]]["Region"].to_string(header=False, index=False))
    names.append(noRP[noRP["Team Number"]==team].iloc[[0]]["Team Name"].to_string(header=False, index=False))

In [90]:
names

['Team Unlimited',
 'Tactical Sheep',
 'Techno Chix',
 '100 Scholars',
 "Rock N' Roll Robots",
 'HAX Robotics',
 'Gr3y Matt3r',
 'Junior Bomb Squad',
 'RoboKnights Team 112',
 'Steel Hornets',
 'Syosset Supersonics',
 'The Fighting Pickles',
 'Blazing Spirits',
 'Arrows',
 'Hawks',
 'Phoenix',
 'ILITE - Ingenuity',
 'BroncoBotsONE',
 'BroncoBotsTOO',
 'Critical Mass',
 'The Highlighters',
 'Oakton Cougar Robotics 226',
 'Reboot',
 'Fatal Error',
 'Mech-alodons',
 'Electric Quahogs',
 'Viking Robotics',
 'EMP',
 'Spare Parts',
 'Robohawks 289',
 'Robohawks 290',
 'Robohawks 291',
 'Medium Builders',
 'Stuy Fission',
 'The Lobotomists',
 'ILITE - Inspiration',
 'Gaulbots',
 'WEBB.exe',
 'MOE (The Miracle Workerz)',
 'Salad',
 'Oakton Cougar Robotics 369',
 'The Swarm',
 'ILITE - Imagination',
 "Boulson's Revenge",
 'S.K.I.D. (Space Koalas In Disguise)',
 'Children of the Swamp',
 'Stuy Fusion',
 'Pandara',
 'Gears of Fire',
 'Epsilon Delta Too',
 'Boss Bots',
 'Success',
 'TOBOR',
 'WHS Robotics',
 'SpectreBots',
 'Dragon Slayers',
 'Cougars',
 "Occam's Razor Clams",
 'Roboscotia',
 'Underdogs',
 'Barrington Bionics',
 'Subatomic Tomahawks',
 'The GONKa Trucks',
 'RedNek Robotics Wun',
 'Wannabee Strange',
 'Gears in Motion',
 'The GreenVillains',
 'Delbotics',
 'Golden Govies',
 'The League of Incompetent Gentlemen',
 'Hacksaw',
 'CircuitRunners Robotics - Surge',
 'Team Spyder',
 'ILITE - The Legacy',
 'Shrapnel Sergeants',
 'Hydra',
 'G-FORCE',
 'Artificial Stupidity',
 'Trobots',
 'Valley X Robotics',
 'Team Duct Tape',
 'Sparbots, FTC Green',
 'Territory of Static, Pattonville High School',
 'Degrees of Freedom, Pattonville High School',
 'Technical Difficulty',
 'Bucket Brigade',
 'Purple Gears',
 'Kaybots',
 'MekoNeko',
 'Blue RoboDragons',
 'TeraBots',
 'Hyperion',
 'Techno Riderz',
 'G-Bots',
 'Live Wire',
 'Bobblebots',
 'The Metal Mercenaries',
 'Boom Bots',
 'Robo Warriors',
 'Spontaneous Combustion',
 'Squiggle Splat Bang',
 'Rapid Unscheduled Disassembly',
 'L8 Lynx',
 'Robophins',
 'NekoMeko',
 'Bots in Blue',
 'Innovators Robotics',
 'Tater Bots',
 'BÃ¶tley CrÃ¼e',
 'Essex Robotics',
 'Astromechs',
 'Lancers',
 'The Patriots',
 'Generals',
 'FIX IT',
 'Cadet Bot Crew',
 'Robotheosis',
 'Marlbots',
 'The MechaHamsters',
 'RoboBoogie',
 'Titan Robotics Club',
 'FireBots',
 'Ghost Robotics',
 'Cybirds',
 'Unparalleled Processing',
 'The QUARKS',
 'The MESONS',
 'Polar Technics',
 'Arlington Automatons',
 'Atomic Shock',
 'The BoilerBots',
 'PPS Robotics',
 'Torrey Techies',
 'The BOSONS',
 'Leopold GearHeads',
 'Hawks Robotics',
 'Iron Eagles Optimus',
 'Iron Giant',
 'Serious Business',
 "Hank's Tanks",
 'Jag-Wires',
 'NECO Robo Knights',
 'The Hive',
 'Good Enough',
 'Rush Henrietta Royal Robotics',
 'Piece of Cake',
 'Since Sliced Bread',
 'Happy Dave',
 'Hive Voltage',
 'Mecha Lion',
 'Pi-Rho Maniacs',
 'C.A.T. S (Chaos Applied to Science)',
 'Ziptiez',
 'JagWired',
 'Talons',
 'Team Snuffleupagus',
 'Atomic Robotics',
 'Green RoboDragons',
 'Lightning Lynx',
 'Violet Fusion',
 'Mechanical Geniuses',
 'Maelstrom',
 'Shockwave',
 'Vashon Pi-r8s "Pirates"',
 'Greased Lightning',
 'Mechasharks',
 'Apex Robotics',
 'Modibot',
 'Team Mercury',
 'Pink to the Future',
 'Iron Legion',
 'Twisted Metal',
 'The Griffins',
 'Bronc Botz - Atlas',
 'RoboPandas',
 '2 Bits and a Byte',
 'Nonstandard Deviation',
 'Mavens of Mayhem',
 'Gradle Demons',
 'Midwest Oilers',
 'T-10   (\\"T minus Ten\\")',
 'The Pac-Bots',
 'Darbots 1',
 'CHS Cougars',
 'Robo Lobo',
 'Supposable Thumbs',
 'Men in Kilts',
 'Volta Robotics',
 'Fusion',
 'IslandBots',
 'Terabytes',
 'Dark Matter',
 'Neptune',
 "M.I.T (Muskogee's Innovative Team)",
 'RoboCats Red',
 'H.A.R.I.S.H.',
 'Atomic Theory',
 'MechaMETROzilla',
 'Finger Tightans',
 'Silver Soldiers',
 'Those Guys',
 'Silent Reign',
 'The X-Squared Factor',
 'Hypnotic Robotics',
 'Rise of Hephaestus',
 'SmÃ\xadÃ°a Syndicate',
 'Metal Morphosis',
 'Gears Of Other Dimensions',
 'Energizer Bunnies',
 'Engineered Chaos',
 'CBOT',
 'Viridescent Vipers',
 'Iron Devils',
 'LIGHTSABERS',
 'Ridgebots',
 "Makin' Stuff Move",
 'RoboChix',
 'Aluminati',
 'Dragonoids',
 'Lost In Time',
 'Basement Lions',
 'Silver Titans',
 "C'est la vie",
 'Aragon Robotics',
 'NanoGurus',
 'RoboKnights',
 'Neuro Link',
 'Raider Robotics',
 'Westside Gold',
 'ARC Lightning',
 'Steel Stallions',
 'PokÃ¨bots',
 'Sock Monkeys',
 'Whitefield Robocats',
 'FireFoxes',
 'Mohawk Warriors Green',
 'R.A.B.B.I.',
 'Purple Reign',
 'Excalibots',
 'Maker Industries',
 'Gearwigs',
 'DRSS Enterprise',
 'ViperBots Ouroboros',
 'ViperBots SnakeByte',
 'Bronc Botz - Prometheus',
 'L.O.C.S.',
 'Kings and Queens',
 'Suit Bots',
 'FROGbots - Purple',
 'RoboSharks',
 'Crusader Robotics',
 'Jellyfish',
 'Adamas Robotics',
 'Midway Predators',
 'Ursa Mechanica',
 'Mechromancers',
 'STEAM Galileo',
 'STEAM Newton',
 'STEAM Einstein',
 'Grand Tech Automation',
 'Fairfield Prep JesuBots',
 'Robolution',
 'MechaKnights',
 'The Super Troublemakers',
 'Dynamic',
 'Tetricons',
 'Anonymous Autonomous',
 'ROBUFFS Dough Boys 4798',
 'Botman',
 'ROBUFFS Rangers 4812',
 'EngiNERDS',
 'Chaos',
 'Sabotage',
 'Westerner Mechnoblades',
 'OmegaBotz',
 'Robo Junkies',
 'AArcHive',
 "Waggish Walen's Western Warblers",
 'The Dueling Westerners',
 'Bodacious Bulldawgs',
 'Team Novabots',
 'Junkyard Dawgs',
 'SCH FTC XCalibur',
 'The Dropouts',
 'Red Beard Pandas',
 'Sparks',
 'RoboFusion',
 'Robo Raiders',
 'Cougarobotics Alpha',
 'Warriors',
 'Traffic Cones',
 'Dimond Legendary Lynx',
 'FM Robotics Team',
 'Rolla Patriots',
 'Animatores Romani',
 'Robot-X',
 'Loose Screws',
 'Cafe Bot',
 'Gear Freaks',
 'Titanium Tigers',
 'Masquerade',
 'SPQR - SenÄ\x81tus Populusque RÅ\x8dboticus',
 'Helios',
 'Bot Squad 5011',
 'Future Gadget Lab',
 'Buffalo Wings',
 'RoboEpic',
 'KilaBots',
 'Tesla Coils',
 'got robot?',
 'DevilBots',
 'Nuts & Bolts',
 'Black Pearl Robotics',
 'Clearwater Atomic Robotic Technicians',
 'Milton Static',
 'The Four Horsemen',
 'Aperture Science',
 'N.U.T.S.',
 'Wildcats',
 'Still Under Development',
 'The LEPTONS',
 'Dragons',
 'Amish Electricians',
 'Wizards Robotics 5115',
 'The HADRONS',
 'The BARYONS',
 'Raiderbots',
 'DICE',
 'Pointers',
 'Crusader Creators',
 'WACO Aerobotics',
 'Warrior Bots',
 'Xcentrics',
 'R.O.A.R (Robots on a Rampage)',
 'Ramifications',
 'X-bots',
 'Eaglemaniacs',
 'Vector Robotics',
 'Mech Hawks',
 'Transistor Titans',
 'Team Phoenix',
 'Team Wolves',
 'Robo Yetis',
 'Wingnuts',
 'Duct Tape and a Prayer',
 'The Knights of Ni',
 'QLS Human Resources',
 'Javabots',
 'Sidwell Varsity',
 'Galactech',
 'Vector',
 'Loose Screws',
 'Team Griffin',
 'The FERMIONS',
 'ILITE - Innovation',
 'Cary Academy & Cary Academy',
 'ARC Thunder',
 'Broken Code',
 'LAIMO',
 'Robo Knights',
 'Martians',
 'Steel Eagles',
 'TOWR The Oxford Wildcats Robotics',
 'Red Storm Robotics-White',
 'The Dirty Dozen',
 'Plan B',
 'Buff Sci-borgs',
 'RoboLancers Gold',
 'TechHeroes',
 'The Muses',
 'TARDIS',
 'Lionotics',
 'YULA Varsity',
 'Neutrinos Breaking the Laws of Physics',
 'Emergency Situation Evacuate Now',
 'Enigma Riddlers',
 'Fabricators',
 'TecHounds',
 'Wired Wolves',
 'Vistamar 5390',
 'Team Clutch',
 'Titanium Titans',
 'G3 Geeks, Gears, and Gadgets Green',
 'Quioxte',
 'Aluminum Cobblers',
 'The GLUONS',
 "Blazin' Circuits",
 'Scramblers',
 '1.21 Gigawatts',
 'Montwood Rambotics',
 'Innovo',
 'Cerberus Robotics',
 'The EnderBots',
 'GorillaBots',
 'Robo Dragons',
 'Iron Eagles',
 'Cougarobotics Omega',
 'VW Robotics',
 "Dutchman's Derivatives",
 'Team X',
 'Blue Shift',
 'RoboComets',
 'Holmes RoboHawks',
 'Payne Bots 5573',
 'The PIT Crew',
 'Thunderbots',
 'Control Freaks RED',
 'Robotics Quasar Alliance',
 'The Tau Manifesto',
 'Red Devil Robotics',
 'Wolves Robotics 1',
 'Robominers',
 'Robo Pirates',
 'Midway Robotics',
 'Doppler Effect',
 'Gators',
 'Titans',
 'Crusader Robotics',
 'CVU RoboHawks',
 'Marburn Academy Marbotics',
 'Midwest Robotics',
 'Ink and Metal',
 'Mechanical Drop Bears',
 'Back  To The Drawing Board',
 'E.M.P. Chaos',
 'AutoVortex',
 'Tungsteel',
 'Redneck Engineering',
 'Direct Current',
 'HackHers',
 'Galactic Lions - Andromeda',
 'L.A.S.E.R.',
 'Camdenton FTC  LASER Middle School #1',
 'Camdenton FTC LASER Middle School #2',
 'Camdenton FTC LASER Middle School #3',
 'Mean Green Machine',
 "Drop It Like It's Bot",
 'RegisOwls',
 'La CaÃ±ada Engineering Club',
 'Roarbotics',
 'Lightning Boltz',
 'Sonic Eagles',
 'Iron Dams',
 'Nordic Storm',
 'WR That Hertz',
 'Brain Bots',
 'Brandon Tech',
 'CyberStingers Blue',
 'Titanium Tech Vikes',
 'Thunder Stone',
 'Ironwolves',
 'Error ID Ten-T',
 'Lightning Hawks',
 'W.A.G.S. (We Are Girl Scouts) Robotics',
 'Tino Koalas',
 'Canton Robodogs',
 'Commandobots',
 'Twisted Axles',
 'Quantum Mechanics',
 'GearTicks',
 'Pingry Robotics',
 'Wildbot Robotics',
 'MUS Robotics',
 'Cut the Red Wire',
 'Bionic Broncos',
 'Electro/Mechanically Controlled Chaos',
 'Bolts, Nuts, and Bots',
 'Deviation From The Norm',
 'Energized Hazard',
 'E=MK2',
 'Radiant Rivals',
 'Cougarbots',
 'The Dragons 1.0',
 'The "NUTS!"',
 'Black Frogs',
 'Newbotics',
 'Birdhouse Frogs',
 'Spartabots',
 'MSET CuttleFish',
 'Maniacal Mechanics',
 'System Surfers',
 'Automatons',
 'License To Shred',
 'Thunderducks',
 'MHS Tech Club',
 'SiBorgs',
 'High Voltage',
 'Red Alert: CyberStorm',
 'Bread Admirers',
 'Crash Test Dummies',
 'Despicable Machine',
 'SCARLET',
 'Ohms Olympians',
 'ViperBots Venom',
 'ViperBots  Stryke',
 'DRIFT (Dinosaurs Racing in Food Trucks)',
 'Panther Bots Alpha',
 'Bambusa',
 'The Wacky Waving Inflatable Arm Flailing Tube M...',
 'RoboJackets',
 'Iron Eagles Prime',
 'Technocats',
 'Dwayne',
 'Genetic Advantage',
 'Simi Valley Robotics',
 'Statesbots - Black',
 'Falcon Hi Flyers',
 'Atomic Toads',
 'Tech Titans',
 'ViperBots QuadX',
 'Odyssey',
 'RoboRaiders',
 'WiredCats Origin',
 'The Pink Team',
 'Aluminati',
 'Tech Titans',
 'OOPS',
 'Nerds of a Feather',
 'Top Dogs',
 'T-Robots',
 'Machine Kings',
 'Patriotic Robotics',
 'SuperBots',
 'JayBots',
 'Wizards Robotics 6382',
 'HHS Robotics - Error Code 301',
 'Brobots',
 'Falcons',
 'Mariners',
 'First Tech Coyotes',
 'Mechanical Mustangs Secretariat',
 'Blu Cru',
 'NDCL Robotics',
 'SabreHOOF Tigers',
 'Oly Cow',
 'RoboHodags',
 'Wright Angle Robotics',
 'Neutrinos',
 'AlphaGenesis',
 'Mad Hatters',
 'Blue Jays',
 'Saints Robotics',
 'MoHawk Warriors Red',
 'Burgbots',
 'RoboWarriors',
 'Red Storm Robotics-Red',
 'Control Freaks WHITE',
 'SEP Nerd Herd',
 'Warrior Bots',
 'ChargerBots',
 'Westside Black',
 'The Indecision Matrices',
 'Railsplitters',
 'Knight Riders',
 'RoboCats',
 'Cobalt Colts',
 'Whoa!Bots',
 'Northeast High School',
 'Tempest',
 'Geared Reaction',
 'Circuit Breakers',
 'Roboraiders',
 'Rhinos',
 'Robotic Rams',
 'Ballen Pretzels Central Lyon',
 'Guild of Gears',
 'Dobbins Force',
 'Allerton 2.0',
 'Gamma Shift',
 'Roboticus Maximus',
 'Cone Nappers',
 'Starmont Sundevils',
 'Robo Falcons A',
 'Quad Six',
 'RoboLancers Crimson',
 'Tempest',
 'Bot Shop',
 'Sour Patch Kids',
 'Aluminumati',
 'Ringers',
 'N R G (Northwestern Robotics Gearheads)',
 'Hardcore Hard Drives',
 'Robo Bearcats',
 'Iron Reign',
 'Robo Crusaders',
 'The Waterboys',
 'Blue Bots',
 'Droid Rage - Phantom',
 'Charging Chaos',
 'The TranSisters',
 'CodeRunners',
 'Pandemonium',
 'System Overload',
 'Einstein Eagles',
 'RoBovines',
 'PokÃ©bolts',
 'Radical Robotics',
 'Monsters of Mechanics',
 'Bronc Botz',
 'CouGEARS',
 'STEMpocalypse Awakened',
 'Droid Rage Rewired',
 'CyberStingers Gold',
 'Spartans',
 'Static Void',
 'Oncoming Storm',
 'RoboSharks',
 'Couch Potatoes',
 'RoboTitans',
 'Robotic Fallout',
 'RoboEagles',
 'JDroids',
 'RoboMinds',
 'Battle Blazers',
 'Singularity Technology 7034',
 'Lord of the Bricks',
 'CyberFalcons',
 'Golden Gears',
 'BLOWNFUSES',
 'Mechanical Monkeys',
 'Purple Protons',
 'R-Cubed',
 'JunkYard Bots',
 'Ov3r1y K0mp13x',
 'FalTech',
 'BACON',
 'TundraBots',
 'F.L.A.G. Fight Like a Girl',
 'RaiderBots',
 'S.T.O.R.M.',
 'Good Enough',
 'SWIFT Intergalactic Space Llamas',
 'The Element of Surprise',
 'Bionica',
 'TINO PIOBOTS',
 'Robo Raiders',
 'Royal Robots',
 'Hornets',
 'Higgs Bosons',
 'KHS Robotics',
 'Knightmares',
 'ENFORCERS',
 'Vindicem',
 'Wolves Robotics 2',
 'Robo Ravens',
 'ViperBots Hydra',
 'The Bazinga Project',
 'FalconBots',
 'Technical Difficulties',
 'Walbots',
 'South Spencer High School',
 "Everything That's Radical",
 'Mechanical Minks',
 'Tech Hogs Robotics',
 'Turning Gears',
 'West Grand Robotics-Mechanical Mustangs 1.0',
 'bzBots',
 'SAS Atoms',
 'The Purple Circuits',
 'Blue and White Lightning Strikes',
 'BC Robocats',
 'OUT of the BOX Robotics',
 'Big Green',
 'The H2O Loo Bots',
 'Comets',
 'Vicious Volts',
 'Raging Robots',
 'STEAM Stingers',
 'Epsilon Robotics',
 'Void Robotics',
 'Mandela United Squadron - First Unit',
 'LibraryBots',
 'Cyber Knights',
 'RoboGlaciers',
 'JagWires',
 'Timber Bots',
 'RoboAvatars',
 'The GearCats - Clague Middle School',
 'Iron Panthers',
 'Oxymorons',
 'Nocturnal',
 'DodgerBOTS',
 'F.R.E.N.C.H. F.R.I.E.S.',
 'Mustachio Peanuts',
 "Watt's NXT?",
 'Eagle Robotics - Carbon Fiber',
 'MSET JellyFish',
 'electron Volts',
 'Shmizmin',
 'Team VEGA',
 'Deceptibots',
 'Silver Spartans',
 'Portledge Robotics',
 'Batteries Not Included',
 'MechaSpartans',
 'Flaming Phoenix',
 'Robotic Warriors',
 'Hot Spot Robotics',
 'Sisters of the Motherboard',
 'Thunder',
 'Not to Scale',
 'Abstract Bots',
 'The no-namers',
 'The Devitos',
 'Super 7',
 'Axel-otls',
 'Suffern Robotics',
 'Axtell 2.0',
 'Robotic Nerds',
 'Bomb Shell',
 'Classified',
 'OH... That One Team',
 'System Overload',
 'QO CouGears',
 'QO CougarBotics',
 'Nerdy Birds',
 'The Core in Blue',
 'JoeBotics Green',
 'Team Loki',
 'Alumineers',
 'Bad News Bots',
 'Catlateral Damage',
 'Roarbots',
 'TigerBots',
 'DWAI',
 'Lions',
 'Cone-querors',
 'Sinagua Robotics',
 'Mechanical Mustangs Affirmed',
 'Breaking Bot 7627',
 'Instant Oats',
 'MSET BettaFish',
 'Tiger Tech Orange 7643',
 'Dragons',
 'Dragons & Tiaras FTC 7673',
 'Whidbey Island Wildcats',
 'Eldon Gearheads Maroon Team',
 'Clarkston Chicken Bots',
 'TECHNADOS',
 'Robotic Lions',
 'Knight Tech Robotics',
 'RISE',
 'TAF@Saghalie Skyrise',
 'The Electric Sheep',
 'Autonomous Prime',
 'Mishap',
 'Blueprints',
 'P.A.N.T.H.E.R.S.',
 'Electric Wave',
 'MT Blue Streaks',
 'Travis Fiddlerbots',
 'Q^2',
 'Victorian Voltage',
 'Alpha Hawks',
 'Roadrunner Robotics',
 'Stewart Robotics Co.',
 'DCAC',
 'Drastic Measures',
 'VEXX',
 'The Thunder Colts',
 'Ballen Pretzels 2',
 'Browncoats',
 'Ratchet Bots',
 'MidKnight Madness',
 'Cougarbots',
 'The Carnivorous Rabbits',
 'Iron Patriots',
 'Royal Screw-Ups',
 'Squires of the Circular Countertop',
 'The Sentinels',
 'Black Knights',
 'Robotigers',
 'Red Toques',
 'The Dragons 2.0',
 'The KAONS',
 'Vertigo',
 'Cougar Cubs',
 'MotorDame',
 'Great Scott!',
 'Brogrammers',
 'Autonomous Rex',
 'Team Kuiper',
 'Twisted Devils Blue',
 'Easy as Pi',
 'Mechanical Menace',
 'Ironclad',
 'Knights of the Lab Table',
 'Seahorse Stallions',
 'Team Cephalopods',
 'Mainframe Meltdown',
 'Robotic Rampage',
 'NAnobots',
 'Botcats',
 'Hanford Falcons',
 'Metalmorphosis',
 'null robotics',
 'RISE Robotics',
 'Invicta',
 'Lewisville HS',
 'Electric Hornets',
 'Sons of Liberty',
 'Vikings',
 'Gear Heads',
 'Laker Robotics, Bionic Sailors Team 8133',
 'Fire and Ice',
 'Mountie Redbot',
 'Red Alert: Panic in the Build Room',
 'Team #8153',
 'Robogoats',
 'Gear Heads',
 'Digi-Gators',
 "Lil' Gibbies",
 'Blue Machine',
 'Enginuity',
 'Vicious Vassar Vulcans',
 'CohBots',
 'E-Hackers',
 'CC Sparks',
 'Calamity',
 'Soap Dispenser',
 'Bulldog Robotics',
 'Baron Alpha',
 'Pi Rho Eagles',
 'Wired Cats',
 'Spartans',
 'Gearmasters',
 'ACME Robotics',
 'Diva Force',
 'Vulcan Robotics',
 'The Parity Bits',
 'UC Robotics',
 'Family Friends',
 'The Giant Diencephalic BrainSTEM Robotics Team',
 'The A-Team',
 'Beta',
 'Perfect Paradox',
 'Quixilver',
 'Millburn Robotics',
 'The Horde',
 'SHARP',
 'The Bucket Bots',
 "'Lectric Legends",
 'Tigers',
 'Cyber Eagles',
 'CyberStingers Green',
 'KnightBots',
 'Elementary  My Dear Botson',
 'The Javengers',
 'Dinomite',
 'E-Bots',
 'RoboCavs Gold',
 'Technabots',
 'Robo Toasters Orange',
 'Mamaroneck Tigers',
 'Titanium Trojans',
 'Robo Hawks',
 'The Generals',
 'STEEL Serpents',
 'Greenhillls School Lawnmowers I',
 'Joe Bots - Maize',
 'BA GREEN: Robotonics',
 'Bond Bots',
 'Team R.O.B.O.T.I.C.S.',
 'GA Bots',
 'CSA MS Miners',
 'Techno Tardigrades',
 'Blue Chargerbots',
 'Bearly Functioning',
 'Thunder Goats',
 'TechnicBots',
 'RoboKnights',
 'Wall-Y Robotics',
 'Juden-Ki Robotics',
 'Classical Engineers',
 'Oakview CyberDragons',
 'Ã\x86dificatores',
 'Heavy Metal',
 'Finger Puppet Mafia',
 'The Fighting Gnomes',
 'ToborTech',
 'Techno Tigers',
 'Wormgear Warriors',
 'G3: Geeks, Gears & Gadgets Blue',
 'Spectrum',
 'RHS Robotix',
 'ProtoSurge',
 'FIRE',
 'Glitchy Bears',
 'tadpole',
 'The Masters',
 '8 to Automate FTC',
 'The Brainstormers',
 'Robotic Doges',
 'Team KAOS',
 'Super Cell',
 'Manual High School RoboRams',
 'Warewolves',
 'Wait For It...',
 "Queen Bee's",
 'UBett',
 'Controlled Chaos',
 'Kraken-Pinion',
 'Marysville Jr Vi-Bots',
 'Twisted Circuits',
 'Scarabs',
 'Tri Hards',
 'Trobotix',
 'Guilford RoboVikings',
 'The League of Extraordinary Roboticist',
 'Innovotics',
 'Tiger Robotics',
 'Roosevelt High School',
 'T Falls Robotics',
 'Quantum Leap',
 'Mighty Mechanics',
 'Bionic Wolves',
 'Robogriffins',
 'Thunderbotz',
 'RoboVikings',
 "'Iobotics",
 "'Iobotics",
 'Raw Bacon',
 'E-Storm',
 'RoboWildcats',
 'The Goonies',
 'Mohawk Warriors Purple',
 'Green Machine',
 'Wired Woodmen',
 'Clay',
 'Oakleaf High School',
 'Aluminati Industries',
 'Robo Tigers',
 'Sioux Center',
 'Molten Sprockets',
 'Robo*Bison Amistad',
 'CyberRaptors',
 'The Winter Soldiers',
 '22nd Century Robotics',
 'Portledge Hit the Switch!',
 'Mariner Mayhem',
 'N-Bots RoboStorm',
 'CADfish',
 'The Wild Bees',
 'Springfield Robotics',
 'RaiderTek',
 'Precision Cut-Ups',
 'Cybernetics',
 'Robopocalypse',
 'Saber Robotics',
 'Marshalltown BotCats',
 'Infinity Factor',
 'PHRED',
 'Clueless Robotics (Team ADHD^2)',
 'Loose Screws',
 "'Iobotics",
 'EP Robo Raiders',
 'Cosmic Goose',
 'Statesbots- Orange',
 'Blue Box Bots',
 'STEAMpunks',
 'TWIST',
 'Tech-Nical Difficulties',
 'NBC Robocats',
 'Team Max',
 'Techtonics',
 'Team Pyrogen',
 'TimeCrafters',
 'Custom Settings',
 'Diamond Blades',
 'Bellevue Blockheads',
 'Austin Prep Crusaders',
 'Robotic Rangers',
 'Matrix',
 'iCreek',
 'TMSA Batteries',
 'Synergistic Effect',
 'Savage Warriors',
 'Mustangs',
 'STEAMpunks Alpha',
 "NERD-Hinsin's Legacy",
 'Motorhead',
 'RoboPuffs',
 'Viridian Robotics',
 'Smarties',
 'Claws of Steel',
 'Firefly',
 'Knightrix',
 'Sketchy Engineering',
 'Twisted Devils Green',
 'Ravonics Orion',
 'Ravonics Rover',
 'WiredCats Omega',
 'Minimum Cache',
 'Falcon Force',
 'Mounties',
 'Robo Dawgs',
 'BECA Hexabots',
 'Overload',
 'Zorrobots',
 'Warrior Bots',
 ...]

In [94]:
team_info = pd.DataFrame({'Team Number' : teams,
                                'Team Name' : names,
                                'Region' : regions }, 
                                )

In [ ]:
[teams, names, regions]

In [96]:
team_info.to_csv(path +'team_info.csv', index = False)